// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Microsoft.Graph.PowerShell.DeviceManagement.Client.Models
{
    /// <summary>
    /// Imported windows autopilot devices.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ImportedWindowsAutopilotDeviceIdentity : global::Microsoft.Graph.PowerShell.DeviceManagement.Client.Models.Entity, IParsable
    {
        /// <summary>UPN of the user the device will be assigned</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssignedUserPrincipalName { get; set; }
#nullable restore
#else
        public string AssignedUserPrincipalName { get; set; }
#endif
        /// <summary>Group Tag of the Windows autopilot device.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupTag { get; set; }
#nullable restore
#else
        public string GroupTag { get; set; }
#endif
        /// <summary>Hardware Blob of the Windows autopilot device.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public byte[]? HardwareIdentifier { get; set; }
#nullable restore
#else
        public byte[] HardwareIdentifier { get; set; }
#endif
        /// <summary>The Import Id of the Windows autopilot device.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImportId { get; set; }
#nullable restore
#else
        public string ImportId { get; set; }
#endif
        /// <summary>Product Key of the Windows autopilot device.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductKey { get; set; }
#nullable restore
#else
        public string ProductKey { get; set; }
#endif
        /// <summary>Serial number of the Windows autopilot device.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SerialNumber { get; set; }
#nullable restore
#else
        public string SerialNumber { get; set; }
#endif
        /// <summary>Current state of the imported device.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Microsoft.Graph.PowerShell.DeviceManagement.Client.Models.ImportedWindowsAutopilotDeviceIdentityState? State { get; set; }
#nullable restore
#else
        public global::Microsoft.Graph.PowerShell.DeviceManagement.Client.Models.ImportedWindowsAutopilotDeviceIdentityState State { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Microsoft.Graph.PowerShell.DeviceManagement.Client.Models.ImportedWindowsAutopilotDeviceIdentity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Microsoft.Graph.PowerShell.DeviceManagement.Client.Models.ImportedWindowsAutopilotDeviceIdentity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Microsoft.Graph.PowerShell.DeviceManagement.Client.Models.ImportedWindowsAutopilotDeviceIdentity();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "assignedUserPrincipalName", n => { AssignedUserPrincipalName = n.GetStringValue(); } },
                { "groupTag", n => { GroupTag = n.GetStringValue(); } },
                { "hardwareIdentifier", n => { HardwareIdentifier = n.GetByteArrayValue(); } },
                { "importId", n => { ImportId = n.GetStringValue(); } },
                { "productKey", n => { ProductKey = n.GetStringValue(); } },
                { "serialNumber", n => { SerialNumber = n.GetStringValue(); } },
                { "state", n => { State = n.GetObjectValue<global::Microsoft.Graph.PowerShell.DeviceManagement.Client.Models.ImportedWindowsAutopilotDeviceIdentityState>(global::Microsoft.Graph.PowerShell.DeviceManagement.Client.Models.ImportedWindowsAutopilotDeviceIdentityState.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteStringValue("assignedUserPrincipalName", AssignedUserPrincipalName);
            writer.WriteStringValue("groupTag", GroupTag);
            writer.WriteByteArrayValue("hardwareIdentifier", HardwareIdentifier);
            writer.WriteStringValue("importId", ImportId);
            writer.WriteStringValue("productKey", ProductKey);
            writer.WriteStringValue("serialNumber", SerialNumber);
            writer.WriteObjectValue<global::Microsoft.Graph.PowerShell.DeviceManagement.Client.Models.ImportedWindowsAutopilotDeviceIdentityState>("state", State);
        }
    }
}
#pragma warning restore CS0618
