#
# Module manifest for module 'Microsoft.Graph.Identity.SignIns'
#
# Generated by: Microsoft Corporation
#
# Generated on: 10/24/2023
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Identity.SignIns.psm1'

# Version number of this module.
ModuleVersion = '2.9.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '60f889fa-f873-43ad-b7d3-b7fc1273a44f'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.9.0'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.Identity.SignIns.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.Identity.SignIns.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Confirm-MgRiskyServicePrincipalCompromised', 
               'Confirm-MgRiskyUserCompromised', 'Get-MgDataPolicyOperation', 
               'Get-MgDataPolicyOperationCount', 'Get-MgIdentityApiConnector', 
               'Get-MgIdentityApiConnectorCount', 'Get-MgIdentityB2XUserFlow', 
               'Get-MgIdentityB2XUserFlowApiConnectorConfiguration', 
               'Get-MgIdentityB2XUserFlowCount', 
               'Get-MgIdentityB2XUserFlowIdentityProvider', 
               'Get-MgIdentityB2XUserFlowIdentityProviderByRef', 
               'Get-MgIdentityB2XUserFlowIdentityProviderCount', 
               'Get-MgIdentityB2XUserFlowLanguage', 
               'Get-MgIdentityB2XUserFlowLanguageCount', 
               'Get-MgIdentityB2XUserFlowLanguageDefaultPage', 
               'Get-MgIdentityB2XUserFlowLanguageDefaultPageContent', 
               'Get-MgIdentityB2XUserFlowLanguageDefaultPageCount', 
               'Get-MgIdentityB2XUserFlowLanguageOverridePage', 
               'Get-MgIdentityB2XUserFlowLanguageOverridePageContent', 
               'Get-MgIdentityB2XUserFlowLanguageOverridePageCount', 
               'Get-MgIdentityB2XUserFlowPostAttributeCollection', 
               'Get-MgIdentityB2XUserFlowPostAttributeCollectionByRef', 
               'Get-MgIdentityB2XUserFlowPostFederationSignup', 
               'Get-MgIdentityB2XUserFlowPostFederationSignupByRef', 
               'Get-MgIdentityB2XUserFlowUserAttributeAssignment', 
               'Get-MgIdentityB2XUserFlowUserAttributeAssignmentCount', 
               'Get-MgIdentityB2XUserFlowUserAttributeAssignmentOrder', 
               'Get-MgIdentityB2XUserFlowUserAttributeAssignmentUserAttribute', 
               'Get-MgIdentityConditionalAccess', 
               'Get-MgIdentityConditionalAccessAuthenticationContextClassReference', 
               'Get-MgIdentityConditionalAccessAuthenticationContextClassReferenceCount', 
               'Get-MgIdentityConditionalAccessNamedLocation', 
               'Get-MgIdentityConditionalAccessNamedLocationCount', 
               'Get-MgIdentityConditionalAccessPolicy', 
               'Get-MgIdentityConditionalAccessPolicyCount', 
               'Get-MgIdentityConditionalAccessTemplate', 
               'Get-MgIdentityConditionalAccessTemplateCount', 
               'Get-MgIdentityProvider', 'Get-MgIdentityProviderCount', 
               'Get-MgIdentityUserFlowAttribute', 
               'Get-MgIdentityUserFlowAttributeCount', 
               'Get-MgInformationProtection', 
               'Get-MgInformationProtectionBitlocker', 
               'Get-MgInformationProtectionBitlockerRecoveryKey', 
               'Get-MgInformationProtectionBitlockerRecoveryKeyCount', 
               'Get-MgInformationProtectionThreatAssessmentRequest', 
               'Get-MgInformationProtectionThreatAssessmentRequestCount', 
               'Get-MgInformationProtectionThreatAssessmentRequestResult', 
               'Get-MgInformationProtectionThreatAssessmentRequestResultCount', 
               'Get-MgInvitation', 'Get-MgInvitationCount', 
               'Get-MgInvitationInvitedUserMailboxSetting', 
               'Get-MgInvitationInvitedUserServiceProvisioningError', 
               'Get-MgInvitationInvitedUserServiceProvisioningErrorCount', 
               'Get-MgOauth2PermissionGrant', 'Get-MgOauth2PermissionGrantCount', 
               'Get-MgOauth2PermissionGrantDelta', 
               'Get-MgOrganizationCertificateBasedAuthConfiguration', 
               'Get-MgOrganizationCertificateBasedAuthConfigurationCount', 
               'Get-MgPolicyActivityBasedTimeoutPolicy', 
               'Get-MgPolicyActivityBasedTimeoutPolicyApplyTo', 
               'Get-MgPolicyActivityBasedTimeoutPolicyApplyToCount', 
               'Get-MgPolicyActivityBasedTimeoutPolicyCount', 
               'Get-MgPolicyAdminConsentRequestPolicy', 
               'Get-MgPolicyAppManagementPolicy', 
               'Get-MgPolicyAppManagementPolicyApplyTo', 
               'Get-MgPolicyAppManagementPolicyApplyToCount', 
               'Get-MgPolicyAppManagementPolicyCount', 
               'Get-MgPolicyAuthenticationFlowPolicy', 
               'Get-MgPolicyAuthenticationMethodPolicy', 
               'Get-MgPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration', 
               'Get-MgPolicyAuthenticationMethodPolicyAuthenticationMethodConfigurationCount', 
               'Get-MgPolicyAuthenticationStrengthPolicy', 
               'Get-MgPolicyAuthenticationStrengthPolicyCombinationConfiguration', 
               'Get-MgPolicyAuthenticationStrengthPolicyCombinationConfigurationCount', 
               'Get-MgPolicyAuthenticationStrengthPolicyCount', 
               'Get-MgPolicyAuthorizationPolicy', 'Get-MgPolicyClaimMappingPolicy', 
               'Get-MgPolicyClaimMappingPolicyApplyTo', 
               'Get-MgPolicyClaimMappingPolicyApplyToCount', 
               'Get-MgPolicyClaimMappingPolicyCount', 
               'Get-MgPolicyConditionalAccessPolicyCount', 
               'Get-MgPolicyCrossTenantAccessPolicy', 
               'Get-MgPolicyCrossTenantAccessPolicyDefault', 
               'Get-MgPolicyCrossTenantAccessPolicyPartner', 
               'Get-MgPolicyCrossTenantAccessPolicyPartnerCount', 
               'Get-MgPolicyCrossTenantAccessPolicyPartnerIdentitySynchronization', 
               'Get-MgPolicyDefaultAppManagementPolicy', 
               'Get-MgPolicyFeatureRolloutPolicy', 
               'Get-MgPolicyFeatureRolloutPolicyApplyTo', 
               'Get-MgPolicyFeatureRolloutPolicyApplyToById', 
               'Get-MgPolicyFeatureRolloutPolicyApplyToByRef', 
               'Get-MgPolicyFeatureRolloutPolicyApplyToCount', 
               'Get-MgPolicyFeatureRolloutPolicyApplyToDelta', 
               'Get-MgPolicyFeatureRolloutPolicyCount', 
               'Get-MgPolicyHomeRealmDiscoveryPolicy', 
               'Get-MgPolicyHomeRealmDiscoveryPolicyApplyTo', 
               'Get-MgPolicyHomeRealmDiscoveryPolicyApplyToCount', 
               'Get-MgPolicyHomeRealmDiscoveryPolicyCount', 
               'Get-MgPolicyIdentitySecurityDefaultEnforcementPolicy', 
               'Get-MgPolicyPermissionGrantPolicy', 
               'Get-MgPolicyPermissionGrantPolicyCount', 
               'Get-MgPolicyPermissionGrantPolicyExclude', 
               'Get-MgPolicyPermissionGrantPolicyExcludeCount', 
               'Get-MgPolicyPermissionGrantPolicyInclude', 
               'Get-MgPolicyPermissionGrantPolicyIncludeCount', 
               'Get-MgPolicyRoleManagementPolicy', 
               'Get-MgPolicyRoleManagementPolicyAssignment', 
               'Get-MgPolicyRoleManagementPolicyAssignmentCount', 
               'Get-MgPolicyRoleManagementPolicyAssignmentPolicy', 
               'Get-MgPolicyRoleManagementPolicyCount', 
               'Get-MgPolicyRoleManagementPolicyEffectiveRule', 
               'Get-MgPolicyRoleManagementPolicyEffectiveRuleCount', 
               'Get-MgPolicyRoleManagementPolicyRule', 
               'Get-MgPolicyRoleManagementPolicyRuleCount', 
               'Get-MgPolicyTokenIssuancePolicy', 
               'Get-MgPolicyTokenIssuancePolicyApplyTo', 
               'Get-MgPolicyTokenIssuancePolicyApplyToCount', 
               'Get-MgPolicyTokenIssuancePolicyCount', 
               'Get-MgPolicyTokenLifetimePolicy', 
               'Get-MgPolicyTokenLifetimePolicyApplyTo', 
               'Get-MgPolicyTokenLifetimePolicyApplyToCount', 
               'Get-MgPolicyTokenLifetimePolicyCount', 'Get-MgRiskDetection', 
               'Get-MgRiskDetectionCount', 'Get-MgRiskyServicePrincipal', 
               'Get-MgRiskyServicePrincipalCount', 
               'Get-MgRiskyServicePrincipalHistory', 
               'Get-MgRiskyServicePrincipalHistoryCount', 'Get-MgRiskyUser', 
               'Get-MgRiskyUserCount', 'Get-MgRiskyUserHistory', 
               'Get-MgRiskyUserHistoryCount', 
               'Get-MgServicePrincipalRiskDetection', 
               'Get-MgServicePrincipalRiskDetectionCount', 
               'Get-MgUserAuthenticationEmailMethod', 
               'Get-MgUserAuthenticationEmailMethodCount', 
               'Get-MgUserAuthenticationFido2Method', 
               'Get-MgUserAuthenticationFido2MethodCount', 
               'Get-MgUserAuthenticationMethod', 
               'Get-MgUserAuthenticationMethodCount', 
               'Get-MgUserAuthenticationMicrosoftAuthenticatorMethod', 
               'Get-MgUserAuthenticationMicrosoftAuthenticatorMethodCount', 
               'Get-MgUserAuthenticationMicrosoftAuthenticatorMethodDevice', 
               'Get-MgUserAuthenticationOperation', 
               'Get-MgUserAuthenticationOperationCount', 
               'Get-MgUserAuthenticationPasswordMethod', 
               'Get-MgUserAuthenticationPasswordMethodCount', 
               'Get-MgUserAuthenticationPhoneMethod', 
               'Get-MgUserAuthenticationPhoneMethodCount', 
               'Get-MgUserAuthenticationSoftwareOathMethod', 
               'Get-MgUserAuthenticationSoftwareOathMethodCount', 
               'Get-MgUserAuthenticationTemporaryAccessPassMethod', 
               'Get-MgUserAuthenticationTemporaryAccessPassMethodCount', 
               'Get-MgUserAuthenticationWindowsHelloForBusinessMethod', 
               'Get-MgUserAuthenticationWindowsHelloForBusinessMethodCount', 
               'Get-MgUserAuthenticationWindowsHelloForBusinessMethodDevice', 
               'Invoke-MgAvailableIdentityProviderType', 
               'Invoke-MgDismissRiskyServicePrincipal', 
               'Invoke-MgDismissRiskyUser', 
               'Invoke-MgUploadIdentityApiConnectorClientCertificate', 
               'Invoke-MgUploadIdentityB2XUserFlowApiConnectorConfigurationPostAttributeCollectionClientCertificate', 
               'Invoke-MgUploadIdentityB2XUserFlowApiConnectorConfigurationPostFederationSignupClientCertificate', 
               'Invoke-MgUsageIdentityConditionalAccessAuthenticationStrengthPolicy', 
               'Invoke-MgUsagePolicyAuthenticationStrengthPolicy', 
               'New-MgDataPolicyOperation', 'New-MgIdentityApiConnector', 
               'New-MgIdentityB2XUserFlow', 
               'New-MgIdentityB2XUserFlowIdentityProviderByRef', 
               'New-MgIdentityB2XUserFlowLanguage', 
               'New-MgIdentityB2XUserFlowLanguageDefaultPage', 
               'New-MgIdentityB2XUserFlowLanguageOverridePage', 
               'New-MgIdentityB2XUserFlowUserAttributeAssignment', 
               'New-MgIdentityConditionalAccessAuthenticationContextClassReference', 
               'New-MgIdentityConditionalAccessAuthenticationStrengthPolicyCombinationConfiguration', 
               'New-MgIdentityConditionalAccessNamedLocation', 
               'New-MgIdentityConditionalAccessPolicy', 'New-MgIdentityProvider', 
               'New-MgIdentityUserFlowAttribute', 
               'New-MgInformationProtectionThreatAssessmentRequest', 
               'New-MgInformationProtectionThreatAssessmentRequestResult', 
               'New-MgInvitation', 'New-MgOauth2PermissionGrant', 
               'New-MgOrganizationCertificateBasedAuthConfiguration', 
               'New-MgPolicyActivityBasedTimeoutPolicy', 
               'New-MgPolicyAppManagementPolicy', 
               'New-MgPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration', 
               'New-MgPolicyAuthenticationStrengthPolicy', 
               'New-MgPolicyAuthenticationStrengthPolicyCombinationConfiguration', 
               'New-MgPolicyClaimMappingPolicy', 
               'New-MgPolicyCrossTenantAccessPolicyPartner', 
               'New-MgPolicyFeatureRolloutPolicy', 
               'New-MgPolicyFeatureRolloutPolicyApplyTo', 
               'New-MgPolicyFeatureRolloutPolicyApplyToByRef', 
               'New-MgPolicyHomeRealmDiscoveryPolicy', 
               'New-MgPolicyPermissionGrantPolicy', 
               'New-MgPolicyPermissionGrantPolicyExclude', 
               'New-MgPolicyPermissionGrantPolicyInclude', 
               'New-MgPolicyRoleManagementPolicy', 
               'New-MgPolicyRoleManagementPolicyAssignment', 
               'New-MgPolicyRoleManagementPolicyEffectiveRule', 
               'New-MgPolicyRoleManagementPolicyRule', 
               'New-MgPolicyTokenIssuancePolicy', 
               'New-MgPolicyTokenLifetimePolicy', 'New-MgRiskDetection', 
               'New-MgRiskyServicePrincipal', 'New-MgRiskyServicePrincipalHistory', 
               'New-MgRiskyUser', 'New-MgRiskyUserHistory', 
               'New-MgServicePrincipalRiskDetection', 
               'New-MgUserAuthenticationEmailMethod', 
               'New-MgUserAuthenticationMethod', 
               'New-MgUserAuthenticationOperation', 
               'New-MgUserAuthenticationPhoneMethod', 
               'New-MgUserAuthenticationTemporaryAccessPassMethod', 
               'Remove-MgDataPolicyOperation', 'Remove-MgIdentityApiConnector', 
               'Remove-MgIdentityB2XUserFlow', 
               'Remove-MgIdentityB2XUserFlowIdentityProvider', 
               'Remove-MgIdentityB2XUserFlowIdentityProviderByRef', 
               'Remove-MgIdentityB2XUserFlowLanguage', 
               'Remove-MgIdentityB2XUserFlowLanguageDefaultPage', 
               'Remove-MgIdentityB2XUserFlowLanguageOverridePage', 
               'Remove-MgIdentityB2XUserFlowPostAttributeCollection', 
               'Remove-MgIdentityB2XUserFlowPostAttributeCollectionByRef', 
               'Remove-MgIdentityB2XUserFlowPostFederationSignup', 
               'Remove-MgIdentityB2XUserFlowPostFederationSignupByRef', 
               'Remove-MgIdentityB2XUserFlowUserAttributeAssignment', 
               'Remove-MgIdentityConditionalAccess', 
               'Remove-MgIdentityConditionalAccessAuthenticationContextClassReference', 
               'Remove-MgIdentityConditionalAccessNamedLocation', 
               'Remove-MgIdentityConditionalAccessPolicy', 
               'Remove-MgIdentityProvider', 'Remove-MgIdentityUserFlowAttribute', 
               'Remove-MgInformationProtectionThreatAssessmentRequest', 
               'Remove-MgInformationProtectionThreatAssessmentRequestResult', 
               'Remove-MgInvitation', 'Remove-MgOauth2PermissionGrant', 
               'Remove-MgOrganizationCertificateBasedAuthConfiguration', 
               'Remove-MgPolicyActivityBasedTimeoutPolicy', 
               'Remove-MgPolicyAdminConsentRequestPolicy', 
               'Remove-MgPolicyAppManagementPolicy', 
               'Remove-MgPolicyAuthenticationFlowPolicy', 
               'Remove-MgPolicyAuthenticationMethodPolicy', 
               'Remove-MgPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration', 
               'Remove-MgPolicyAuthenticationStrengthPolicy', 
               'Remove-MgPolicyAuthenticationStrengthPolicyCombinationConfiguration', 
               'Remove-MgPolicyAuthorizationPolicy', 
               'Remove-MgPolicyClaimMappingPolicy', 
               'Remove-MgPolicyCrossTenantAccessPolicy', 
               'Remove-MgPolicyCrossTenantAccessPolicyDefault', 
               'Remove-MgPolicyCrossTenantAccessPolicyPartner', 
               'Remove-MgPolicyCrossTenantAccessPolicyPartnerIdentitySynchronization', 
               'Remove-MgPolicyDefaultAppManagementPolicy', 
               'Remove-MgPolicyFeatureRolloutPolicy', 
               'Remove-MgPolicyFeatureRolloutPolicyApplyToByRef', 
               'Remove-MgPolicyHomeRealmDiscoveryPolicy', 
               'Remove-MgPolicyIdentitySecurityDefaultEnforcementPolicy', 
               'Remove-MgPolicyPermissionGrantPolicy', 
               'Remove-MgPolicyPermissionGrantPolicyExclude', 
               'Remove-MgPolicyPermissionGrantPolicyInclude', 
               'Remove-MgPolicyRoleManagementPolicy', 
               'Remove-MgPolicyRoleManagementPolicyAssignment', 
               'Remove-MgPolicyRoleManagementPolicyEffectiveRule', 
               'Remove-MgPolicyRoleManagementPolicyRule', 
               'Remove-MgPolicyTokenIssuancePolicy', 
               'Remove-MgPolicyTokenLifetimePolicy', 'Remove-MgRiskDetection', 
               'Remove-MgRiskyServicePrincipal', 
               'Remove-MgRiskyServicePrincipalHistory', 'Remove-MgRiskyUser', 
               'Remove-MgRiskyUserHistory', 
               'Remove-MgServicePrincipalRiskDetection', 
               'Remove-MgUserAuthenticationEmailMethod', 
               'Remove-MgUserAuthenticationFido2Method', 
               'Remove-MgUserAuthenticationMicrosoftAuthenticatorMethod', 
               'Remove-MgUserAuthenticationOperation', 
               'Remove-MgUserAuthenticationPhoneMethod', 
               'Remove-MgUserAuthenticationSoftwareOathMethod', 
               'Remove-MgUserAuthenticationTemporaryAccessPassMethod', 
               'Remove-MgUserAuthenticationWindowsHelloForBusinessMethod', 
               'Reset-MgPolicyCrossTenantAccessPolicyDefaultToSystemDefault', 
               'Set-MgIdentityB2XUserFlowLanguageDefaultPageContent', 
               'Set-MgIdentityB2XUserFlowLanguageOverridePageContent', 
               'Set-MgIdentityB2XUserFlowPostAttributeCollectionByRef', 
               'Set-MgIdentityB2XUserFlowPostFederationSignupByRef', 
               'Set-MgIdentityB2XUserFlowUserAttributeAssignmentOrder', 
               'Set-MgPolicyCrossTenantAccessPolicyPartnerIdentitySynchronization', 
               'Test-MgPolicyFeatureRolloutPolicyApplyToProperty', 
               'Update-MgDataPolicyOperation', 'Update-MgIdentityApiConnector', 
               'Update-MgIdentityB2XUserFlow', 
               'Update-MgIdentityB2XUserFlowLanguage', 
               'Update-MgIdentityB2XUserFlowLanguageDefaultPage', 
               'Update-MgIdentityB2XUserFlowLanguageOverridePage', 
               'Update-MgIdentityB2XUserFlowPostAttributeCollection', 
               'Update-MgIdentityB2XUserFlowPostFederationSignup', 
               'Update-MgIdentityB2XUserFlowUserAttributeAssignment', 
               'Update-MgIdentityConditionalAccess', 
               'Update-MgIdentityConditionalAccessAuthenticationContextClassReference', 
               'Update-MgIdentityConditionalAccessNamedLocation', 
               'Update-MgIdentityConditionalAccessPolicy', 
               'Update-MgIdentityProvider', 'Update-MgIdentityUserFlowAttribute', 
               'Update-MgInformationProtection', 
               'Update-MgInformationProtectionThreatAssessmentRequest', 
               'Update-MgInformationProtectionThreatAssessmentRequestResult', 
               'Update-MgInvitation', 
               'Update-MgInvitationInvitedUserMailboxSetting', 
               'Update-MgOauth2PermissionGrant', 
               'Update-MgPolicyActivityBasedTimeoutPolicy', 
               'Update-MgPolicyAdminConsentRequestPolicy', 
               'Update-MgPolicyAppManagementPolicy', 
               'Update-MgPolicyAuthenticationFlowPolicy', 
               'Update-MgPolicyAuthenticationMethodPolicy', 
               'Update-MgPolicyAuthenticationMethodPolicyAuthenticationMethodConfiguration', 
               'Update-MgPolicyAuthenticationStrengthPolicy', 
               'Update-MgPolicyAuthenticationStrengthPolicyAllowedCombination', 
               'Update-MgPolicyAuthenticationStrengthPolicyCombinationConfiguration', 
               'Update-MgPolicyAuthorizationPolicy', 
               'Update-MgPolicyClaimMappingPolicy', 
               'Update-MgPolicyCrossTenantAccessPolicy', 
               'Update-MgPolicyCrossTenantAccessPolicyDefault', 
               'Update-MgPolicyCrossTenantAccessPolicyPartner', 
               'Update-MgPolicyDefaultAppManagementPolicy', 
               'Update-MgPolicyFeatureRolloutPolicy', 
               'Update-MgPolicyHomeRealmDiscoveryPolicy', 
               'Update-MgPolicyIdentitySecurityDefaultEnforcementPolicy', 
               'Update-MgPolicyPermissionGrantPolicy', 
               'Update-MgPolicyPermissionGrantPolicyExclude', 
               'Update-MgPolicyPermissionGrantPolicyInclude', 
               'Update-MgPolicyRoleManagementPolicy', 
               'Update-MgPolicyRoleManagementPolicyAssignment', 
               'Update-MgPolicyRoleManagementPolicyEffectiveRule', 
               'Update-MgPolicyRoleManagementPolicyRule', 
               'Update-MgPolicyTokenIssuancePolicy', 
               'Update-MgPolicyTokenLifetimePolicy', 'Update-MgRiskDetection', 
               'Update-MgRiskyServicePrincipal', 
               'Update-MgRiskyServicePrincipalHistory', 'Update-MgRiskyUser', 
               'Update-MgRiskyUserHistory', 
               'Update-MgServicePrincipalRiskDetection', 
               'Update-MgUserAuthenticationEmailMethod', 
               'Update-MgUserAuthenticationMethod', 
               'Update-MgUserAuthenticationOperation', 
               'Update-MgUserAuthenticationPhoneMethod'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/dev/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIIoKQYJKoZIhvcNAQcCoIIoGjCCKBYCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCC8si5kpilOC8WI
# hPZpwFJhBLEw6GE6NW/ROEJWCeI/q6CCDXYwggX0MIID3KADAgECAhMzAAADTrU8
# esGEb+srAAAAAANOMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjMwMzE2MTg0MzI5WhcNMjQwMzE0MTg0MzI5WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQDdCKiNI6IBFWuvJUmf6WdOJqZmIwYs5G7AJD5UbcL6tsC+EBPDbr36pFGo1bsU
# p53nRyFYnncoMg8FK0d8jLlw0lgexDDr7gicf2zOBFWqfv/nSLwzJFNP5W03DF/1
# 1oZ12rSFqGlm+O46cRjTDFBpMRCZZGddZlRBjivby0eI1VgTD1TvAdfBYQe82fhm
# WQkYR/lWmAK+vW/1+bO7jHaxXTNCxLIBW07F8PBjUcwFxxyfbe2mHB4h1L4U0Ofa
# +HX/aREQ7SqYZz59sXM2ySOfvYyIjnqSO80NGBaz5DvzIG88J0+BNhOu2jl6Dfcq
# jYQs1H/PMSQIK6E7lXDXSpXzAgMBAAGjggFzMIIBbzAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQUnMc7Zn/ukKBsBiWkwdNfsN5pdwAw
# RQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEW
# MBQGA1UEBRMNMjMwMDEyKzUwMDUxNjAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzci
# tW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEG
# CCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0
# MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBAD21v9pHoLdBSNlFAjmk
# mx4XxOZAPsVxxXbDyQv1+kGDe9XpgBnT1lXnx7JDpFMKBwAyIwdInmvhK9pGBa31
# TyeL3p7R2s0L8SABPPRJHAEk4NHpBXxHjm4TKjezAbSqqbgsy10Y7KApy+9UrKa2
# kGmsuASsk95PVm5vem7OmTs42vm0BJUU+JPQLg8Y/sdj3TtSfLYYZAaJwTAIgi7d
# hzn5hatLo7Dhz+4T+MrFd+6LUa2U3zr97QwzDthx+RP9/RZnur4inzSQsG5DCVIM
# pA1l2NWEA3KAca0tI2l6hQNYsaKL1kefdfHCrPxEry8onJjyGGv9YKoLv6AOO7Oh
# JEmbQlz/xksYG2N/JSOJ+QqYpGTEuYFYVWain7He6jgb41JbpOGKDdE/b+V2q/gX
# UgFe2gdwTpCDsvh8SMRoq1/BNXcr7iTAU38Vgr83iVtPYmFhZOVM0ULp/kKTVoir
# IpP2KCxT4OekOctt8grYnhJ16QMjmMv5o53hjNFXOxigkQWYzUO+6w50g0FAeFa8
# 5ugCCB6lXEk21FFB1FdIHpjSQf+LP/W2OV/HfhC3uTPgKbRtXo83TZYEudooyZ/A
# Vu08sibZ3MkGOJORLERNwKm2G7oqdOv4Qj8Z0JrGgMzj46NFKAxkLSpE5oHQYP1H
# tPx1lPfD7iNSbJsP6LiUHXH1MIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
# hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
# IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
# Q29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
# CgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03
# a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akr
# rnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0Rrrg
# OGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
# 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9
# sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAh
# dCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
# A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTB
# w3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmn
# Eyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90
# lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0w
# ggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2o
# ynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBa
# BgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsG
# AQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
# HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsG
# AQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABl
# AG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKb
# C5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11l
# hJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6
# I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0
# wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
# STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQam
# ASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGa
# J+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
# XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA
# 9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33Vt
# Y5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr
# /Xmfwb1tbWrJUnMTDXpQzTGCGgkwghoFAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNp
# Z25pbmcgUENBIDIwMTECEzMAAANOtTx6wYRv6ysAAAAAA04wDQYJYIZIAWUDBAIB
# BQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIHjzmIx1qfzhAVv/w/A+9Ibh
# 9jM/mINz1tF5kefPyBxFMEIGCisGAQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8A
# cwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEB
# BQAEggEAKRoKKDCxb+GUS8GbcXm/sK/oOQaiWjKi76V2KFR+SHPFrqWmd5w0abyn
# wnukcCLYSHMIlhEn41PTHHn/alHNSIvHLS2pvTz+5hzSTbP/3t6G5r9eUqUu/I+Y
# aKh+rgOshUhbHiszYxrSxXP0FJ7gweUqrHsyXlqKPgZ1eK+1z/YhF8I8ADpcJV/U
# 84Ef03KSejvF5jaNmwMjNaO3259s3DgzP3Q9ev/fU+b89mbf+caGFur0PdhEGpSu
# wo9PFXdIWWwPRgMuOSaNGMF4Aanxtlt4ldtvj5sXtyLualLlNR9UoCkFszHqhW+z
# ah6mkd92mnwjYhpbLoLb6W0+Aj7woqGCF5MwghePBgorBgEEAYI3AwMBMYIXfzCC
# F3sGCSqGSIb3DQEHAqCCF2wwghdoAgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFRBgsq
# hkiG9w0BCRABBKCCAUAEggE8MIIBOAIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
# AwQCAQUABCCddFWP/1+S+eGWYZ4VjhsbpLpoMVYIU0EdsmAcJ0HSjQIGZSiGjgUz
# GBIyMDIzMTAyNDE1MzczMy45M1owBIACAfSggdGkgc4wgcsxCzAJBgNVBAYTAlVT
# MRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQK
# ExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJTAjBgNVBAsTHE1pY3Jvc29mdCBBbWVy
# aWNhIE9wZXJhdGlvbnMxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVTTjo4NjAzLTA1
# RTAtRDk0NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2VydmljZaCC
# EeowggcgMIIFCKADAgECAhMzAAAB15sNHlcujFGOAAEAAAHXMA0GCSqGSIb3DQEB
# CwUAMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
# EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNV
# BAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMB4XDTIzMDUyNTE5MTIz
# N1oXDTI0MDIwMTE5MTIzN1owgcsxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
# aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
# cG9yYXRpb24xJTAjBgNVBAsTHE1pY3Jvc29mdCBBbWVyaWNhIE9wZXJhdGlvbnMx
# JzAlBgNVBAsTHm5TaGllbGQgVFNTIEVTTjo4NjAzLTA1RTAtRDk0NzElMCMGA1UE
# AxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2VydmljZTCCAiIwDQYJKoZIhvcNAQEB
# BQADggIPADCCAgoCggIBAMSsYKQ3Zf9S+40Jx+XTJUE2j4sgjLMbsDXRfmRWAaen
# 2zyZ/hpmy6Rm7mu8uzs2po0TFzCc+4chZ2nqSzCNrVjD1LFNf4TSV6r5YG5whEpZ
# 1wy6YgMGAsTQRv/f8Fj3lm1PVeyedq0EVmGvS4uQOJP0eCtFvXbaybv9iTIyKAWR
# PQm6iJI9egsvvBpQT214j1A6SiOqNGVwgLhhU1j7ZQgEzlCiso1o53P+yj5MgXqb
# PFfmfLZT+j+IwVVN+/CbhPyD9irHDJ76U6Zr0or3y/q/B7+KLvZMxNVbApcV1c7K
# w/0aKhxe3fxy4/1zxoTV4fergV0ZOAo53Ssb7GEKCxEXwaotPuTnxWlCcny77KNF
# bouia3lFyuimB/0Qfx7h+gNShTJTlDuI+DA4nFiGgrFGMZmW2EOanl7H7pTrO/3m
# t33vfrrykakKS7QgHjcv8FPMxwMBXj/G7pF9xUXBqs3/Imrmp9nIyykfmBxpMJUC
# i5eRBNzwvC1/G2AjPneoxJVH1z2CRKfEzlzW0eCIxfcPYYGdBqf3m3L4J1NgACGO
# AFNzKP0/s4YQyGveXJpnGOveCmzpmajjtU5Mjy2xJgeEe0PwGkGiDf0vl7j+UMmD
# 86risawUpLExe4hFnUTTx2Zfrtczuqa+bbs7zTgKESZv4I5HxZvjowUQTPraO77F
# AgMBAAGjggFJMIIBRTAdBgNVHQ4EFgQUrqfAu/1ZAvc0jEQnI+4kxnowjY0wHwYD
# VR0jBBgwFoAUn6cVXQBeYl2D9OXSZacbUzUZ6XIwXwYDVR0fBFgwVjBUoFKgUIZO
# aHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWljcm9zb2Z0JTIw
# VGltZS1TdGFtcCUyMFBDQSUyMDIwMTAoMSkuY3JsMGwGCCsGAQUFBwEBBGAwXjBc
# BggrBgEFBQcwAoZQaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jZXJ0
# cy9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcnQwDAYD
# VR0TAQH/BAIwADAWBgNVHSUBAf8EDDAKBggrBgEFBQcDCDAOBgNVHQ8BAf8EBAMC
# B4AwDQYJKoZIhvcNAQELBQADggIBAFIF3dQn4iy90wJf4rvGodrlQG1ULUJpdm8d
# F36y1bSVcD91M2d4JbRMWsGgljn1v1+dtOi49F5qS7aXdfluaGxqjoMJFW6pyaFU
# 8BnJJcZ6hV+PnZwsaLJksTDpNDO7oP76+M04aZKJs7QoT0Z2/yFARHHlEbQqCtOa
# TxyR4LVVSq55RAcpUIRKpMNQMPx1dMtYKaboeqZBfr/6AoNJeCDClzvmGLYBspKj
# i26UzBN9cl0Z3CuyIeOTPyfMhb9nc+cyAYVTvoq7NgVXRfIf0NNL8M87zpEu1CMD
# lmVUbKZM99OfDuTGiIsk3/KW4wciQdLOlom8KKpf4OfVAZEQSc0hl5F6S8ui6uo9
# EQg5ObVslEnTrlz1hftsnSdo+LHObnLxjYH5gggQCLiNSto6HegTtrgm8hbcSDeg
# 2o/uqGl3vEwvGrZacz5T1upZN5PhUKikCFe7a4ZB7F0urttZ1xjDIQUOFLhn03S7
# DeHpuMHtLgxf3ql9hIRXQwoUY4puZ8JRLtZ6aS4WpnLSg0c8/H5x901h5IXpuE48
# d2yujURV3fNYiR0PUbmQQM+cRC0Vqu0zwf5u/nNSEBQmzyovO4UB0FlAu54P1dl7
# KeNArAR4DPrfEBMgKHy05QzbMyBISFUvwebjlIHp+h6zgFMLRjxJlai/chqG2/DI
# cVtSqzViMIIHcTCCBVmgAwIBAgITMwAAABXF52ueAptJmQAAAAAAFTANBgkqhkiG
# 9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
# BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEy
# MDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IDIw
# MTAwHhcNMjEwOTMwMTgyMjI1WhcNMzAwOTMwMTgzMjI1WjB8MQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGlt
# ZS1TdGFtcCBQQ0EgMjAxMDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
# AOThpkzntHIhC3miy9ckeb0O1YLT/e6cBwfSqWxOdcjKNVf2AX9sSuDivbk+F2Az
# /1xPx2b3lVNxWuJ+Slr+uDZnhUYjDLWNE893MsAQGOhgfWpSg0S3po5GawcU88V2
# 9YZQ3MFEyHFcUTE3oAo4bo3t1w/YJlN8OWECesSq/XJprx2rrPY2vjUmZNqYO7oa
# ezOtgFt+jBAcnVL+tuhiJdxqD89d9P6OU8/W7IVWTe/dvI2k45GPsjksUZzpcGkN
# yjYtcI4xyDUoveO0hyTD4MmPfrVUj9z6BVWYbWg7mka97aSueik3rMvrg0XnRm7K
# MtXAhjBcTyziYrLNueKNiOSWrAFKu75xqRdbZ2De+JKRHh09/SDPc31BmkZ1zcRf
# NN0Sidb9pSB9fvzZnkXftnIv231fgLrbqn427DZM9ituqBJR6L8FA6PRc6ZNN3SU
# HDSCD/AQ8rdHGO2n6Jl8P0zbr17C89XYcz1DTsEzOUyOArxCaC4Q6oRRRuLRvWoY
# WmEBc8pnol7XKHYC4jMYctenIPDC+hIK12NvDMk2ZItboKaDIV1fMHSRlJTYuVD5
# C4lh8zYGNRiER9vcG9H9stQcxWv2XFJRXRLbJbqvUAV6bMURHXLvjflSxIUXk8A8
# FdsaN8cIFRg/eKtFtvUeh17aj54WcmnGrnu3tz5q4i6tAgMBAAGjggHdMIIB2TAS
# BgkrBgEEAYI3FQEEBQIDAQABMCMGCSsGAQQBgjcVAgQWBBQqp1L+ZMSavoKRPEY1
# Kc8Q/y8E7jAdBgNVHQ4EFgQUn6cVXQBeYl2D9OXSZacbUzUZ6XIwXAYDVR0gBFUw
# UzBRBgwrBgEEAYI3TIN9AQEwQTA/BggrBgEFBQcCARYzaHR0cDovL3d3dy5taWNy
# b3NvZnQuY29tL3BraW9wcy9Eb2NzL1JlcG9zaXRvcnkuaHRtMBMGA1UdJQQMMAoG
# CCsGAQUFBwMIMBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIAQwBBMAsGA1UdDwQEAwIB
# hjAPBgNVHRMBAf8EBTADAQH/MB8GA1UdIwQYMBaAFNX2VsuP6KJcYmjRPZSQW9fO
# mhjEMFYGA1UdHwRPME0wS6BJoEeGRWh0dHA6Ly9jcmwubWljcm9zb2Z0LmNvbS9w
# a2kvY3JsL3Byb2R1Y3RzL01pY1Jvb0NlckF1dF8yMDEwLTA2LTIzLmNybDBaBggr
# BgEFBQcBAQROMEwwSgYIKwYBBQUHMAKGPmh0dHA6Ly93d3cubWljcm9zb2Z0LmNv
# bS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0XzIwMTAtMDYtMjMuY3J0MA0GCSqGSIb3
# DQEBCwUAA4ICAQCdVX38Kq3hLB9nATEkW+Geckv8qW/qXBS2Pk5HZHixBpOXPTEz
# tTnXwnE2P9pkbHzQdTltuw8x5MKP+2zRoZQYIu7pZmc6U03dmLq2HnjYNi6cqYJW
# AAOwBb6J6Gngugnue99qb74py27YP0h1AdkY3m2CDPVtI1TkeFN1JFe53Z/zjj3G
# 82jfZfakVqr3lbYoVSfQJL1AoL8ZthISEV09J+BAljis9/kpicO8F7BUhUKz/Aye
# ixmJ5/ALaoHCgRlCGVJ1ijbCHcNhcy4sa3tuPywJeBTpkbKpW99Jo3QMvOyRgNI9
# 5ko+ZjtPu4b6MhrZlvSP9pEB9s7GdP32THJvEKt1MMU0sHrYUP4KWN1APMdUbZ1j
# dEgssU5HLcEUBHG/ZPkkvnNtyo4JvbMBV0lUZNlz138eW0QBjloZkWsNn6Qo3GcZ
# KCS6OEuabvshVGtqRRFHqfG3rsjoiV5PndLQTHa1V1QJsWkBRH58oWFsc/4Ku+xB
# Zj1p/cvBQUl+fpO+y/g75LcVv7TOPqUxUYS8vwLBgqJ7Fx0ViY1w/ue10CgaiQuP
# Ntq6TPmb/wrpNPgkNWcr4A245oyZ1uEi6vAnQj0llOZ0dFtq0Z4+7X6gMTN9vMvp
# e784cETRkPHIqzqKOghif9lwY1NNje6CbaUFEMFxBmoQtB1VM1izoXBm8qGCA00w
# ggI1AgEBMIH5oYHRpIHOMIHLMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
# Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
# cmF0aW9uMSUwIwYDVQQLExxNaWNyb3NvZnQgQW1lcmljYSBPcGVyYXRpb25zMScw
# JQYDVQQLEx5uU2hpZWxkIFRTUyBFU046ODYwMy0wNUUwLUQ5NDcxJTAjBgNVBAMT
# HE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2WiIwoBATAHBgUrDgMCGgMVADFb
# 26LMbeERjz24va675f6Yb+t1oIGDMIGApH4wfDELMAkGA1UEBhMCVVMxEzARBgNV
# BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
# c29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAg
# UENBIDIwMTAwDQYJKoZIhvcNAQELBQACBQDo4i31MCIYDzIwMjMxMDI0MTE1MDEz
# WhgPMjAyMzEwMjUxMTUwMTNaMHQwOgYKKwYBBAGEWQoEATEsMCowCgIFAOjiLfUC
# AQAwBwIBAAICII0wBwIBAAICEvowCgIFAOjjf3UCAQAwNgYKKwYBBAGEWQoEAjEo
# MCYwDAYKKwYBBAGEWQoDAqAKMAgCAQACAwehIKEKMAgCAQACAwGGoDANBgkqhkiG
# 9w0BAQsFAAOCAQEARVQQBm0ru/4nBQZ8YEcMVbeLdR0InKcrhKgGcI+19ANDiY3I
# CuNKtFKK7E9L/ElEPbxbVFEle9UadWvEJf1AsLddOYvh2kf3k0rr11/EkqpVSBMp
# EO4o1knH5I95UdDqHqkrayVOsj0jUzuG3oW8qSMUiX5phvQkfmN+lhDvQxehcwAd
# L0Podm2eLaba0zppdzP3zPFo0C44YXVx4lTYQShjcqrVd9nC1hzrMVbvr4S5SA8p
# peKXwfoib+0Azd+n3Ke8BYBVyHpUn2Q9gfb3lvpZHcVP7R6fGZrlTw3vCkuLhvKV
# td9K8RubQRu5ESmZOZ7rF+RqFpMi3/VSlHvAWzGCBA0wggQJAgEBMIGTMHwxCzAJ
# BgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25k
# MR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jv
# c29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAAB15sNHlcujFGOAAEAAAHXMA0G
# CWCGSAFlAwQCAQUAoIIBSjAaBgkqhkiG9w0BCQMxDQYLKoZIhvcNAQkQAQQwLwYJ
# KoZIhvcNAQkEMSIEINmex/NxiGVAxG5Zt9xFED1DwnSBQri0cpscR2ByDybwMIH6
# BgsqhkiG9w0BCRACLzGB6jCB5zCB5DCBvQQgnN4+XktefU+Ko2PHxg3tM3VkjR3V
# lf/bNF2cj3usmjswgZgwgYCkfjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2Fz
# aGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
# cnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAx
# MAITMwAAAdebDR5XLoxRjgABAAAB1zAiBCDLzULneyVCEVWUdWr7wPrYtMKoIRGX
# 6c6p354d2659bTANBgkqhkiG9w0BAQsFAASCAgBjM9jXt8rlN9L5sGj4d00zUQNl
# vb0nDaW2hE441jhu4w8VYVKPZoUBq1LpFkH5TNF4PjOnxdoc3Pu+pYSFcGcEHdxx
# 1t3a9XsgRAg9ZGj1+R8Uhqbds6nKR1h8QgWIMh8iOhkwePMGg+CJHrWsKzZTKtYC
# /NiM0Glv/KIKezeD1PFWzx2UZLdBg5ubL1Tbimh63NbicyFiTBDydWdjmmcLuXJa
# LuPRaERK+8JwMiDmXGBCqfMXHY2HxqXNF7llvRefwEYpU45tDOZPgIex4ghdwkod
# q19I/K0EHiDpgCh4ClbqH2NU5NC6PxikEXQDtMsdjmrGt2ZBAVK6F1gAWaeKHwFq
# me5e997W3A8eNKgmjYV+Und56SkXY5yZxfRIHTmkd9Gy9qvu0SYbkm+c245igmI4
# VjkUGZQSlPzBPuitHucVXEe3RNMfTnDpK2mAIPHIn4/21izBJ5DGQV27bKr3SO0D
# eU4DWb9KXaFMRCGh6Vf8Vjkt0J4lsiOOLI8B6wi8aNVhFMteKXQJfobAEbOdjA6t
# Qj/UsZVn17SaRgLBProHFj08APwU7UQhpdrwxDeevHKMCqB5+gLkgbFFrNts+cvI
# qVTTprHOT1bX8BEL3BNelvoKhHkD21D1vQCibWADnBetspWM8vDSO7jcLvrsGdPT
# NLSR+lCb3Ze2I9rprw==
# SIG # End signature block
