// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.TermStore;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Entity : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The unique identifier for an entity. Read-only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The OdataType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OdataType { get; set; }
#nullable restore
#else
        public string OdataType { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Entity"/> and sets the default values.
        /// </summary>
        public Entity()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Entity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Entity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("@odata.type")?.GetStringValue();
            return mappingValue switch
            {
                "#microsoft.graph.activitiesContainer" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ActivitiesContainer(),
                "#microsoft.graph.activityHistoryItem" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ActivityHistoryItem(),
                "#microsoft.graph.adhocCall" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.AdhocCall(),
                "#microsoft.graph.agreementAcceptance" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.AgreementAcceptance(),
                "#microsoft.graph.appRoleAssignment" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.AppRoleAssignment(),
                "#microsoft.graph.associatedTeamInfo" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.AssociatedTeamInfo(),
                "#microsoft.graph.attachment" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Attachment(),
                "#microsoft.graph.attachmentBase" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.AttachmentBase(),
                "#microsoft.graph.attachmentSession" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.AttachmentSession(),
                "#microsoft.graph.attendanceRecord" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.AttendanceRecord(),
                "#microsoft.graph.authentication" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Authentication(),
                "#microsoft.graph.authenticationMethod" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.AuthenticationMethod(),
                "#microsoft.graph.baseItem" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.BaseItem(),
                "#microsoft.graph.baseItemVersion" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.BaseItemVersion(),
                "#microsoft.graph.baseSitePage" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.BaseSitePage(),
                "#microsoft.graph.calendar" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Calendar(),
                "#microsoft.graph.calendarGroup" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.CalendarGroup(),
                "#microsoft.graph.calendarPermission" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.CalendarPermission(),
                "#microsoft.graph.callRecording" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.CallRecording(),
                "#microsoft.graph.callTranscript" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.CallTranscript(),
                "#microsoft.graph.changeTrackedEntity" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ChangeTrackedEntity(),
                "#microsoft.graph.channel" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Channel(),
                "#microsoft.graph.chat" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Chat(),
                "#microsoft.graph.chatMessage" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ChatMessage(),
                "#microsoft.graph.chatMessageHostedContent" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ChatMessageHostedContent(),
                "#microsoft.graph.chatMessageInfo" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ChatMessageInfo(),
                "#microsoft.graph.checklistItem" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ChecklistItem(),
                "#microsoft.graph.cloudClipboardItem" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.CloudClipboardItem(),
                "#microsoft.graph.cloudClipboardRoot" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.CloudClipboardRoot(),
                "#microsoft.graph.cloudPC" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.CloudPC(),
                "#microsoft.graph.columnDefinition" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ColumnDefinition(),
                "#microsoft.graph.columnLink" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ColumnLink(),
                "#microsoft.graph.contact" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Contact(),
                "#microsoft.graph.contactFolder" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ContactFolder(),
                "#microsoft.graph.contentActivity" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ContentActivity(),
                "#microsoft.graph.contentType" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ContentType(),
                "#microsoft.graph.conversation" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Conversation(),
                "#microsoft.graph.conversationMember" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ConversationMember(),
                "#microsoft.graph.conversationThread" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ConversationThread(),
                "#microsoft.graph.dataSecurityAndGovernance" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.DataSecurityAndGovernance(),
                "#microsoft.graph.dayNote" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.DayNote(),
                "#microsoft.graph.device" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Device(),
                "#microsoft.graph.deviceCategory" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.DeviceCategory(),
                "#microsoft.graph.deviceCompliancePolicyState" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.DeviceCompliancePolicyState(),
                "#microsoft.graph.deviceConfigurationState" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.DeviceConfigurationState(),
                "#microsoft.graph.deviceLogCollectionResponse" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.DeviceLogCollectionResponse(),
                "#microsoft.graph.deviceManagementTroubleshootingEvent" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.DeviceManagementTroubleshootingEvent(),
                "#microsoft.graph.directoryObject" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.DirectoryObject(),
                "#microsoft.graph.documentSetVersion" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.DocumentSetVersion(),
                "#microsoft.graph.drive" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Drive(),
                "#microsoft.graph.driveItem" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.DriveItem(),
                "#microsoft.graph.driveItemVersion" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.DriveItemVersion(),
                "#microsoft.graph.emailAuthenticationMethod" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.EmailAuthenticationMethod(),
                "#microsoft.graph.employeeExperienceUser" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.EmployeeExperienceUser(),
                "#microsoft.graph.engagementRole" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.EngagementRole(),
                "#microsoft.graph.engagementRoleMember" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.EngagementRoleMember(),
                "#microsoft.graph.event" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Event(),
                "#microsoft.graph.exchangeSettings" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ExchangeSettings(),
                "#microsoft.graph.extension" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Extension(),
                "#microsoft.graph.externalAuthenticationMethod" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ExternalAuthenticationMethod(),
                "#microsoft.graph.fido2AuthenticationMethod" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Fido2AuthenticationMethod(),
                "#microsoft.graph.fieldValueSet" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.FieldValueSet(),
                "#microsoft.graph.group" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Group(),
                "#microsoft.graph.groupLifecyclePolicy" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.GroupLifecyclePolicy(),
                "#microsoft.graph.groupSetting" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.GroupSetting(),
                "#microsoft.graph.inferenceClassification" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.InferenceClassification(),
                "#microsoft.graph.inferenceClassificationOverride" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.InferenceClassificationOverride(),
                "#microsoft.graph.itemActivity" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ItemActivity(),
                "#microsoft.graph.itemActivityStat" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ItemActivityStat(),
                "#microsoft.graph.itemAnalytics" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ItemAnalytics(),
                "#microsoft.graph.itemInsights" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ItemInsights(),
                "#microsoft.graph.itemRetentionLabel" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ItemRetentionLabel(),
                "#microsoft.graph.learningCourseActivity" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.LearningCourseActivity(),
                "#microsoft.graph.licenseDetails" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.LicenseDetails(),
                "#microsoft.graph.linkedResource" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.LinkedResource(),
                "#microsoft.graph.list" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.List(),
                "#microsoft.graph.listItem" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ListItem(),
                "#microsoft.graph.listItemVersion" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ListItemVersion(),
                "#microsoft.graph.longRunningOperation" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.LongRunningOperation(),
                "#microsoft.graph.mailFolder" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.MailFolder(),
                "#microsoft.graph.managedAppOperation" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ManagedAppOperation(),
                "#microsoft.graph.managedAppPolicy" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ManagedAppPolicy(),
                "#microsoft.graph.managedAppRegistration" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ManagedAppRegistration(),
                "#microsoft.graph.managedDevice" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ManagedDevice(),
                "#microsoft.graph.meetingAttendanceReport" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.MeetingAttendanceReport(),
                "#microsoft.graph.message" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Message(),
                "#microsoft.graph.messageRule" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.MessageRule(),
                "#microsoft.graph.microsoftAuthenticatorAuthenticationMethod" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.MicrosoftAuthenticatorAuthenticationMethod(),
                "#microsoft.graph.multiValueLegacyExtendedProperty" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.MultiValueLegacyExtendedProperty(),
                "#microsoft.graph.notebook" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Notebook(),
                "#microsoft.graph.oAuth2PermissionGrant" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.OAuth2PermissionGrant(),
                "#microsoft.graph.offerShiftRequest" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.OfferShiftRequest(),
                "#microsoft.graph.officeGraphInsights" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.OfficeGraphInsights(),
                "#microsoft.graph.onenote" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Onenote(),
                "#microsoft.graph.onenoteEntityBaseModel" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.OnenoteEntityBaseModel(),
                "#microsoft.graph.onenoteEntityHierarchyModel" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.OnenoteEntityHierarchyModel(),
                "#microsoft.graph.onenoteEntitySchemaObjectModel" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.OnenoteEntitySchemaObjectModel(),
                "#microsoft.graph.onenoteOperation" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.OnenoteOperation(),
                "#microsoft.graph.onenotePage" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.OnenotePage(),
                "#microsoft.graph.onenoteResource" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.OnenoteResource(),
                "#microsoft.graph.onenoteSection" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.OnenoteSection(),
                "#microsoft.graph.onlineMeeting" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.OnlineMeeting(),
                "#microsoft.graph.onlineMeetingBase" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.OnlineMeetingBase(),
                "#microsoft.graph.onPremisesSyncBehavior" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.OnPremisesSyncBehavior(),
                "#microsoft.graph.openShift" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.OpenShift(),
                "#microsoft.graph.openShiftChangeRequest" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.OpenShiftChangeRequest(),
                "#microsoft.graph.operation" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Operation(),
                "#microsoft.graph.outlookCategory" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.OutlookCategory(),
                "#microsoft.graph.outlookItem" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.OutlookItem(),
                "#microsoft.graph.outlookUser" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.OutlookUser(),
                "#microsoft.graph.passwordAuthenticationMethod" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.PasswordAuthenticationMethod(),
                "#microsoft.graph.permission" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Permission(),
                "#microsoft.graph.person" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Person(),
                "#microsoft.graph.phoneAuthenticationMethod" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.PhoneAuthenticationMethod(),
                "#microsoft.graph.pinnedChatMessageInfo" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.PinnedChatMessageInfo(),
                "#microsoft.graph.plannerAssignedToTaskBoardTaskFormat" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.PlannerAssignedToTaskBoardTaskFormat(),
                "#microsoft.graph.plannerBucket" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.PlannerBucket(),
                "#microsoft.graph.plannerBucketTaskBoardTaskFormat" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.PlannerBucketTaskBoardTaskFormat(),
                "#microsoft.graph.plannerGroup" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.PlannerGroup(),
                "#microsoft.graph.plannerPlan" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.PlannerPlan(),
                "#microsoft.graph.plannerPlanDetails" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.PlannerPlanDetails(),
                "#microsoft.graph.plannerProgressTaskBoardTaskFormat" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.PlannerProgressTaskBoardTaskFormat(),
                "#microsoft.graph.plannerTask" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.PlannerTask(),
                "#microsoft.graph.plannerTaskDetails" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.PlannerTaskDetails(),
                "#microsoft.graph.plannerUser" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.PlannerUser(),
                "#microsoft.graph.platformCredentialAuthenticationMethod" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.PlatformCredentialAuthenticationMethod(),
                "#microsoft.graph.post" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Post(),
                "#microsoft.graph.presence" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Presence(),
                "#microsoft.graph.printConnector" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.PrintConnector(),
                "#microsoft.graph.printDocument" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.PrintDocument(),
                "#microsoft.graph.printer" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Printer(),
                "#microsoft.graph.printerBase" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.PrinterBase(),
                "#microsoft.graph.printerShare" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.PrinterShare(),
                "#microsoft.graph.printJob" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.PrintJob(),
                "#microsoft.graph.printOperation" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.PrintOperation(),
                "#microsoft.graph.printService" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.PrintService(),
                "#microsoft.graph.printServiceEndpoint" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.PrintServiceEndpoint(),
                "#microsoft.graph.printTask" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.PrintTask(),
                "#microsoft.graph.printTaskDefinition" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.PrintTaskDefinition(),
                "#microsoft.graph.printTaskTrigger" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.PrintTaskTrigger(),
                "#microsoft.graph.profilePhoto" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ProfilePhoto(),
                "#microsoft.graph.resourceSpecificPermissionGrant" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ResourceSpecificPermissionGrant(),
                "#microsoft.graph.richLongRunningOperation" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.RichLongRunningOperation(),
                "#microsoft.graph.schedule" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Schedule(),
                "#microsoft.graph.scheduleChangeRequest" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ScheduleChangeRequest(),
                "#microsoft.graph.schedulingGroup" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.SchedulingGroup(),
                "#microsoft.graph.scopedRoleMembership" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ScopedRoleMembership(),
                "#microsoft.graph.sectionGroup" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.SectionGroup(),
                "#microsoft.graph.sensitivityLabel" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.SensitivityLabel(),
                "#microsoft.graph.serviceStorageQuotaBreakdown" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ServiceStorageQuotaBreakdown(),
                "#microsoft.graph.sharedInsight" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.SharedInsight(),
                "#microsoft.graph.sharedWithChannelTeamInfo" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.SharedWithChannelTeamInfo(),
                "#microsoft.graph.shift" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Shift(),
                "#microsoft.graph.shiftPreferences" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ShiftPreferences(),
                "#microsoft.graph.singleValueLegacyExtendedProperty" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.SingleValueLegacyExtendedProperty(),
                "#microsoft.graph.site" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Site(),
                "#microsoft.graph.softwareOathAuthenticationMethod" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.SoftwareOathAuthenticationMethod(),
                "#microsoft.graph.storageQuotaBreakdown" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.StorageQuotaBreakdown(),
                "#microsoft.graph.subscription" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Subscription(),
                "#microsoft.graph.swapShiftsChangeRequest" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.SwapShiftsChangeRequest(),
                "#microsoft.graph.targetedChatMessage" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.TargetedChatMessage(),
                "#microsoft.graph.team" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Team(),
                "#microsoft.graph.teamInfo" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.TeamInfo(),
                "#microsoft.graph.teamsApp" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.TeamsApp(),
                "#microsoft.graph.teamsAppDefinition" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.TeamsAppDefinition(),
                "#microsoft.graph.teamsAppInstallation" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.TeamsAppInstallation(),
                "#microsoft.graph.teamsAsyncOperation" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.TeamsAsyncOperation(),
                "#microsoft.graph.teamsTab" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.TeamsTab(),
                "#microsoft.graph.teamsTemplate" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.TeamsTemplate(),
                "#microsoft.graph.teamworkBot" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.TeamworkBot(),
                "#microsoft.graph.teamworkHostedContent" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.TeamworkHostedContent(),
                "#microsoft.graph.teamworkTag" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.TeamworkTag(),
                "#microsoft.graph.teamworkTagMember" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.TeamworkTagMember(),
                "#microsoft.graph.temporaryAccessPassAuthenticationMethod" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.TemporaryAccessPassAuthenticationMethod(),
                "#microsoft.graph.termStore.group" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.TermStore.Group(),
                "#microsoft.graph.termStore.relation" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.TermStore.Relation(),
                "#microsoft.graph.termStore.set" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.TermStore.Set(),
                "#microsoft.graph.termStore.store" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.TermStore.Store(),
                "#microsoft.graph.termStore.term" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.TermStore.Term(),
                "#microsoft.graph.thumbnailSet" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.ThumbnailSet(),
                "#microsoft.graph.timeCard" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.TimeCard(),
                "#microsoft.graph.timeOff" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.TimeOff(),
                "#microsoft.graph.timeOffReason" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.TimeOffReason(),
                "#microsoft.graph.timeOffRequest" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.TimeOffRequest(),
                "#microsoft.graph.todo" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Todo(),
                "#microsoft.graph.todoTask" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.TodoTask(),
                "#microsoft.graph.todoTaskList" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.TodoTaskList(),
                "#microsoft.graph.trending" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Trending(),
                "#microsoft.graph.unifiedStorageQuota" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.UnifiedStorageQuota(),
                "#microsoft.graph.usageRightsIncluded" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.UsageRightsIncluded(),
                "#microsoft.graph.usedInsight" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.UsedInsight(),
                "#microsoft.graph.user" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.User(),
                "#microsoft.graph.userActivity" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.UserActivity(),
                "#microsoft.graph.userDataSecurityAndGovernance" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.UserDataSecurityAndGovernance(),
                "#microsoft.graph.userInsightsSettings" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.UserInsightsSettings(),
                "#microsoft.graph.userProtectionScopeContainer" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.UserProtectionScopeContainer(),
                "#microsoft.graph.userScopeTeamsAppInstallation" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.UserScopeTeamsAppInstallation(),
                "#microsoft.graph.userSettings" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.UserSettings(),
                "#microsoft.graph.userSolutionRoot" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.UserSolutionRoot(),
                "#microsoft.graph.userStorage" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.UserStorage(),
                "#microsoft.graph.userTeamwork" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.UserTeamwork(),
                "#microsoft.graph.windowsDeviceMalwareState" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WindowsDeviceMalwareState(),
                "#microsoft.graph.windowsHelloForBusinessAuthenticationMethod" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WindowsHelloForBusinessAuthenticationMethod(),
                "#microsoft.graph.windowsProtectionState" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WindowsProtectionState(),
                "#microsoft.graph.windowsSetting" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WindowsSetting(),
                "#microsoft.graph.windowsSettingInstance" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WindowsSettingInstance(),
                "#microsoft.graph.workbook" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Workbook(),
                "#microsoft.graph.workbookApplication" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookApplication(),
                "#microsoft.graph.workbookChart" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookChart(),
                "#microsoft.graph.workbookChartAreaFormat" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookChartAreaFormat(),
                "#microsoft.graph.workbookChartAxes" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookChartAxes(),
                "#microsoft.graph.workbookChartAxis" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookChartAxis(),
                "#microsoft.graph.workbookChartAxisFormat" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookChartAxisFormat(),
                "#microsoft.graph.workbookChartAxisTitle" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookChartAxisTitle(),
                "#microsoft.graph.workbookChartAxisTitleFormat" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookChartAxisTitleFormat(),
                "#microsoft.graph.workbookChartDataLabelFormat" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookChartDataLabelFormat(),
                "#microsoft.graph.workbookChartDataLabels" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookChartDataLabels(),
                "#microsoft.graph.workbookChartFill" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookChartFill(),
                "#microsoft.graph.workbookChartFont" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookChartFont(),
                "#microsoft.graph.workbookChartGridlines" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookChartGridlines(),
                "#microsoft.graph.workbookChartGridlinesFormat" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookChartGridlinesFormat(),
                "#microsoft.graph.workbookChartLegend" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookChartLegend(),
                "#microsoft.graph.workbookChartLegendFormat" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookChartLegendFormat(),
                "#microsoft.graph.workbookChartLineFormat" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookChartLineFormat(),
                "#microsoft.graph.workbookChartPoint" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookChartPoint(),
                "#microsoft.graph.workbookChartPointFormat" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookChartPointFormat(),
                "#microsoft.graph.workbookChartSeries" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookChartSeries(),
                "#microsoft.graph.workbookChartSeriesFormat" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookChartSeriesFormat(),
                "#microsoft.graph.workbookChartTitle" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookChartTitle(),
                "#microsoft.graph.workbookChartTitleFormat" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookChartTitleFormat(),
                "#microsoft.graph.workbookComment" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookComment(),
                "#microsoft.graph.workbookCommentReply" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookCommentReply(),
                "#microsoft.graph.workbookFilter" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookFilter(),
                "#microsoft.graph.workbookFunctions" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookFunctions(),
                "#microsoft.graph.workbookNamedItem" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookNamedItem(),
                "#microsoft.graph.workbookOperation" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookOperation(),
                "#microsoft.graph.workbookPivotTable" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookPivotTable(),
                "#microsoft.graph.workbookTable" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookTable(),
                "#microsoft.graph.workbookTableColumn" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookTableColumn(),
                "#microsoft.graph.workbookTableRow" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookTableRow(),
                "#microsoft.graph.workbookTableSort" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookTableSort(),
                "#microsoft.graph.workbookWorksheet" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookWorksheet(),
                "#microsoft.graph.workbookWorksheetProtection" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkbookWorksheetProtection(),
                "#microsoft.graph.workHoursAndLocationsSetting" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkHoursAndLocationsSetting(),
                "#microsoft.graph.workingTimeSchedule" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkingTimeSchedule(),
                "#microsoft.graph.workPlanOccurrence" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkPlanOccurrence(),
                "#microsoft.graph.workPlanRecurrence" => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.WorkPlanRecurrence(),
                _ => new global::Microsoft.Graph.PowerShell.Devices.CloudPrint.Client.Models.Entity(),
            };
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "id", n => { Id = n.GetStringValue(); } },
                { "@odata.type", n => { OdataType = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("@odata.type", OdataType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
