// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Microsoft.Graph.PowerShell.DeviceManagement.Client.Models
{
    /// <summary>Setting RiskLevel</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    [Flags]
    public enum DeviceManagementConfigurationSettingRiskLevel
    {
        /// <summary>Default. Low Risk Setting</summary>
        [EnumMember(Value = "low")]
        Low = 1,
        /// <summary>Medium Risk Setting</summary>
        [EnumMember(Value = "medium")]
        Medium = 2,
        /// <summary>High Risk Setting</summary>
        [EnumMember(Value = "high")]
        High = 4,
    }
}
