// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Microsoft.Graph.PowerShell.DeviceManagement.Client.Models
{
    /// <summary>Indicates the device scope status after the device scope has been enabled. Possible values are: none, computing, insufficientData or completed. Default value is none.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DeviceScopeStatus
    {
        /// <summary>Indicates the device scope is not enabled and there are no calculations in progress.</summary>
        [EnumMember(Value = "none")]
        None,
        /// <summary>Indicates the device scope is enabled and report metrics data are being recalculated by the service.</summary>
        [EnumMember(Value = "computing")]
        Computing,
        /// <summary>Indicates the device scope is enabled but there is insufficient data to calculate results. The system requires information from at least 5 devices before calculations can occur.</summary>
        [EnumMember(Value = "insufficientData")]
        InsufficientData,
        /// <summary>Device scope is enabled and finished recalculating the report metric. Device scope is now ready to be used.</summary>
        [EnumMember(Value = "completed")]
        Completed,
        /// <summary>Evolvable enumeration sentinel value. Do not use.</summary>
        [EnumMember(Value = "unknownFutureValue")]
        UnknownFutureValue,
    }
}
