// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Microsoft.Graph.PowerShell.DeviceManagement.Client.Models
{
    /// <summary>
    /// The security baseline compliance state of a setting for a device
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SecurityBaselineSettingState : global::Microsoft.Graph.PowerShell.DeviceManagement.Client.Models.Entity, IParsable
    {
        /// <summary>The policies that contribute to this setting instance</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Microsoft.Graph.PowerShell.DeviceManagement.Client.Models.SecurityBaselineContributingPolicy>? ContributingPolicies { get; set; }
#nullable restore
#else
        public List<global::Microsoft.Graph.PowerShell.DeviceManagement.Client.Models.SecurityBaselineContributingPolicy> ContributingPolicies { get; set; }
#endif
        /// <summary>The error code if the setting is in error state</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorCode { get; set; }
#nullable restore
#else
        public string ErrorCode { get; set; }
#endif
        /// <summary>The setting category id which this setting belongs to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SettingCategoryId { get; set; }
#nullable restore
#else
        public string SettingCategoryId { get; set; }
#endif
        /// <summary>The setting category name which this setting belongs to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SettingCategoryName { get; set; }
#nullable restore
#else
        public string SettingCategoryName { get; set; }
#endif
        /// <summary>The setting id guid</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SettingId { get; set; }
#nullable restore
#else
        public string SettingId { get; set; }
#endif
        /// <summary>The setting name that is being reported</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SettingName { get; set; }
#nullable restore
#else
        public string SettingName { get; set; }
#endif
        /// <summary>The policies that contribute to this setting instance</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Microsoft.Graph.PowerShell.DeviceManagement.Client.Models.SettingSource>? SourcePolicies { get; set; }
#nullable restore
#else
        public List<global::Microsoft.Graph.PowerShell.DeviceManagement.Client.Models.SettingSource> SourcePolicies { get; set; }
#endif
        /// <summary>Security Baseline Compliance State</summary>
        public global::Microsoft.Graph.PowerShell.DeviceManagement.Client.Models.SecurityBaselineComplianceState? State { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Microsoft.Graph.PowerShell.DeviceManagement.Client.Models.SecurityBaselineSettingState"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Microsoft.Graph.PowerShell.DeviceManagement.Client.Models.SecurityBaselineSettingState CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Microsoft.Graph.PowerShell.DeviceManagement.Client.Models.SecurityBaselineSettingState();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "contributingPolicies", n => { ContributingPolicies = n.GetCollectionOfObjectValues<global::Microsoft.Graph.PowerShell.DeviceManagement.Client.Models.SecurityBaselineContributingPolicy>(global::Microsoft.Graph.PowerShell.DeviceManagement.Client.Models.SecurityBaselineContributingPolicy.CreateFromDiscriminatorValue)?.AsList(); } },
                { "errorCode", n => { ErrorCode = n.GetStringValue(); } },
                { "settingCategoryId", n => { SettingCategoryId = n.GetStringValue(); } },
                { "settingCategoryName", n => { SettingCategoryName = n.GetStringValue(); } },
                { "settingId", n => { SettingId = n.GetStringValue(); } },
                { "settingName", n => { SettingName = n.GetStringValue(); } },
                { "sourcePolicies", n => { SourcePolicies = n.GetCollectionOfObjectValues<global::Microsoft.Graph.PowerShell.DeviceManagement.Client.Models.SettingSource>(global::Microsoft.Graph.PowerShell.DeviceManagement.Client.Models.SettingSource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "state", n => { State = n.GetEnumValue<global::Microsoft.Graph.PowerShell.DeviceManagement.Client.Models.SecurityBaselineComplianceState>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfObjectValues<global::Microsoft.Graph.PowerShell.DeviceManagement.Client.Models.SecurityBaselineContributingPolicy>("contributingPolicies", ContributingPolicies);
            writer.WriteStringValue("errorCode", ErrorCode);
            writer.WriteStringValue("settingCategoryId", SettingCategoryId);
            writer.WriteStringValue("settingCategoryName", SettingCategoryName);
            writer.WriteStringValue("settingId", SettingId);
            writer.WriteStringValue("settingName", SettingName);
            writer.WriteCollectionOfObjectValues<global::Microsoft.Graph.PowerShell.DeviceManagement.Client.Models.SettingSource>("sourcePolicies", SourcePolicies);
            writer.WriteEnumValue<global::Microsoft.Graph.PowerShell.DeviceManagement.Client.Models.SecurityBaselineComplianceState>("state", State);
        }
    }
}
#pragma warning restore CS0618
