# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Managed code static analysis (aka.ms/sdtvsts)
# https://marketplace.visualstudio.com/items?itemName=securedevelopmentteam.vss-secure-development-tools

steps:
  - task: RoslynAnalyzers@3
    inputs:
      userProvideBuildInfo: 'msBuildInfo'
      msBuildVersion: '17.0'
      msBuildArchitecture: 'x64'
      setupCommandlinePicker: 'vs2022'
      rulesetName: Recommended
      rulesetVersion: Latest
      policyName: 'M365'
      loadRoslynConfiguredAnalyzersOption: Enable # Keep code generators running
    env:
      SYSTEM_ACCESSTOKEN: $(system.accesstoken)
