# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

steps:
  - task: UseDotNet@2
    displayName: Use .NET SDK
    inputs:
      version: 8.x 

  - task: UseDotNet@2
    displayName: Use .NET SDK
    inputs:
      version: 6.x 
      
  - task: NuGetToolInstaller@1
    displayName: Install Nuget

  - task: NuGetAuthenticate@1

  - task: PowerShell@2
    displayName: Version Check
    inputs:
      targetType: inline
      pwsh: true
      script: |
        Write-Output $PSVersionTable

  - task: NodeTool@0
    displayName: Install NodeJs
    inputs:
      versionSpec: 18.x

  - task: PowerShell@2
    displayName: Configure private npm feed
    inputs:
      targetType: filePath
      pwsh: true
      filePath: $(Build.SourcesDirectory)/tools/Configure-PrivateNpmFeed.ps1
      arguments: -SourcesDirectory "$(Build.SourcesDirectory)"

  - task: npmAuthenticate@0
    displayName: Authenticate to private npm feed
    inputs:
      workingFile: $(Build.SourcesDirectory)/.npmrc

  - task: npmAuthenticate@0
    displayName: Authenticate to private npm feed (Rush)
    inputs:
      workingFile: $(Build.SourcesDirectory)/autorest.powershell/common/config/rush/.npmrc

  - task: PowerShell@2
    displayName: Set npm userconfig for all npm subprocesses
    inputs:
      targetType: inline
      pwsh: true
      script: |
        Write-Host "##vso[task.setvariable variable=NPM_CONFIG_USERCONFIG]$(Build.SourcesDirectory)/.npmrc"

  - task: Npm@1
    displayName: Install AutoRest
    inputs:
      command: custom
      workingDir: $(Build.SourcesDirectory)
      customCommand: install -g autorest@3.7.2 --registry https://microsoftgraph.pkgs.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_packaging/PowerShell_V2_Build/npm/registry/

  - task: Npm@1
    displayName: Install AutorestCore
    inputs:
      command: custom
      workingDir: $(Build.SourcesDirectory)
      customCommand: install -g @autorest/core@3.10.4 --registry https://microsoftgraph.pkgs.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_packaging/PowerShell_V2_Build/npm/registry/

  - task: Npm@1
    displayName: Install Rush
    inputs:
      command: custom
      workingDir: $(Build.SourcesDirectory)
      customCommand: install -g @microsoft/rush --registry https://microsoftgraph.pkgs.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_packaging/PowerShell_V2_Build/npm/registry/
  
  - task: PowerShell@2
    displayName: Rush Build
    inputs:
      targetType: inline
      pwsh: true
      workingDirectory: "autorest.powershell"
      script: |
        rush install
        rush link
        rush rebuild