# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
steps:
  - task: PublishSecurityAnalysisLogs@3
    displayName: "Publish Security Analysis Logs"
    inputs:
      ArtifactName: "CodeAnalysisLogs"
      ArtifactType: "Container"

  - task: PostAnalysis@2
    displayName: "Post Analysis"
    inputs:
      CredScan: true
      PoliCheck: true
      GdnBreakAllTools: false
      GdnBreakGdnToolPoliCheck: true
      GdnBreakGdnToolPoliCheckSeverity: Error
