// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Microsoft.Graph.PowerShell.CloudCommunications.Client.Models.CallRecords
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CallType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "groupCall")]
        #pragma warning disable CS1591
        GroupCall,
        #pragma warning restore CS1591
        [EnumMember(Value = "peerToPeer")]
        #pragma warning disable CS1591
        PeerToPeer,
        #pragma warning restore CS1591
        [EnumMember(Value = "unknownFutureValue")]
        #pragma warning disable CS1591
        UnknownFutureValue,
        #pragma warning restore CS1591
    }
}
