// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Microsoft.Graph.PowerShell.Reports.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProvisionedIdentity : global::Microsoft.Graph.PowerShell.Reports.Client.Models.Identity, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Details of the identity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Microsoft.Graph.PowerShell.Reports.Client.Models.DetailsInfo? Details { get; set; }
#nullable restore
#else
        public global::Microsoft.Graph.PowerShell.Reports.Client.Models.DetailsInfo Details { get; set; }
#endif
        /// <summary>Type of identity that has been provisioned, such as &apos;user&apos; or &apos;group&apos;. Supports $filter (eq, contains).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IdentityType { get; set; }
#nullable restore
#else
        public string IdentityType { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Microsoft.Graph.PowerShell.Reports.Client.Models.ProvisionedIdentity"/> and sets the default values.
        /// </summary>
        public ProvisionedIdentity() : base()
        {
            OdataType = "#microsoft.graph.provisionedIdentity";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Microsoft.Graph.PowerShell.Reports.Client.Models.ProvisionedIdentity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Microsoft.Graph.PowerShell.Reports.Client.Models.ProvisionedIdentity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Microsoft.Graph.PowerShell.Reports.Client.Models.ProvisionedIdentity();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "details", n => { Details = n.GetObjectValue<global::Microsoft.Graph.PowerShell.Reports.Client.Models.DetailsInfo>(global::Microsoft.Graph.PowerShell.Reports.Client.Models.DetailsInfo.CreateFromDiscriminatorValue); } },
                { "identityType", n => { IdentityType = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteObjectValue<global::Microsoft.Graph.PowerShell.Reports.Client.Models.DetailsInfo>("details", Details);
            writer.WriteStringValue("identityType", IdentityType);
        }
    }
}
#pragma warning restore CS0618
