openapi: 3.0.1
info:
  title: Identity.TrustFramework
  version: v1.0
servers:
  - url: https://graph.microsoft.com/v1.0/
    description: Core
paths: { }
components:
  securitySchemes:
    azureaadv2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
          tokenUrl: https://login.microsoftonline.com/common/oauth2/v2.0/token
          scopes: { }
security:
  - azureaadv2: [ ]