#
# Module manifest for module 'Microsoft.Graph.Beta.Applications'
#
# Generated by: Microsoft Corporation
#
# Generated on: 12/5/2023
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Beta.Applications.psm1'

# Version number of this module.
ModuleVersion = '2.11.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'fae868a9-cfb4-4875-82ce-3954ba828375'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.11.0'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.Beta.Applications.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.Beta.Applications.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Add-MgBetaApplicationKey', 'Add-MgBetaApplicationPassword', 
               'Add-MgBetaServicePrincipalTokenSigningCertificate', 
               'Clear-MgBetaApplicationVerifiedPublisher', 
               'Confirm-MgBetaApplicationMemberGroup', 
               'Confirm-MgBetaApplicationMemberObject', 
               'Confirm-MgBetaServicePrincipalMemberGroup', 
               'Confirm-MgBetaServicePrincipalMemberObject', 
               'Find-MgBetaApplicationSynchronizationJobSchemaDirectory', 
               'Find-MgBetaApplicationSynchronizationTemplateSchemaDirectory', 
               'Find-MgBetaServicePrincipalSynchronizationJobSchemaDirectory', 
               'Find-MgBetaServicePrincipalSynchronizationTemplateSchemaDirectory', 
               'Get-MgBetaApplication', 'Get-MgBetaApplicationAppManagementPolicy', 
               'Get-MgBetaApplicationAppManagementPolicyByRef', 
               'Get-MgBetaApplicationAppManagementPolicyCount', 
               'Get-MgBetaApplicationByAppId', 'Get-MgBetaApplicationById', 
               'Get-MgBetaApplicationByUniqueName', 
               'Get-MgBetaApplicationConnectorGroup', 
               'Get-MgBetaApplicationConnectorGroupByRef', 
               'Get-MgBetaApplicationCount', 
               'Get-MgBetaApplicationCreatedOnBehalfOf', 
               'Get-MgBetaApplicationDelta', 
               'Get-MgBetaApplicationExtensionProperty', 
               'Get-MgBetaApplicationExtensionPropertyCount', 
               'Get-MgBetaApplicationFederatedIdentityCredential', 
               'Get-MgBetaApplicationFederatedIdentityCredentialCount', 
               'Get-MgBetaApplicationHomeRealmDiscoveryPolicy', 
               'Get-MgBetaApplicationHomeRealmDiscoveryPolicyCount', 
               'Get-MgBetaApplicationLogo', 'Get-MgBetaApplicationMemberGroup', 
               'Get-MgBetaApplicationMemberObject', 'Get-MgBetaApplicationOwner', 
               'Get-MgBetaApplicationOwnerAsEndpoint', 
               'Get-MgBetaApplicationOwnerAsServicePrincipal', 
               'Get-MgBetaApplicationOwnerAsUser', 
               'Get-MgBetaApplicationOwnerByRef', 
               'Get-MgBetaApplicationOwnerCount', 
               'Get-MgBetaApplicationOwnerCountAsEndpoint', 
               'Get-MgBetaApplicationOwnerCountAsServicePrincipal', 
               'Get-MgBetaApplicationOwnerCountAsUser', 
               'Get-MgBetaApplicationSynchronization', 
               'Get-MgBetaApplicationSynchronizationAccessToken', 
               'Get-MgBetaApplicationSynchronizationJob', 
               'Get-MgBetaApplicationSynchronizationJobBulkUpload', 
               'Get-MgBetaApplicationSynchronizationJobBulkUploadContent', 
               'Get-MgBetaApplicationSynchronizationJobCount', 
               'Get-MgBetaApplicationSynchronizationJobSchema', 
               'Get-MgBetaApplicationSynchronizationJobSchemaDirectory', 
               'Get-MgBetaApplicationSynchronizationJobSchemaDirectoryCount', 
               'Get-MgBetaApplicationSynchronizationSecretCount', 
               'Get-MgBetaApplicationSynchronizationTemplate', 
               'Get-MgBetaApplicationSynchronizationTemplateCount', 
               'Get-MgBetaApplicationSynchronizationTemplateSchema', 
               'Get-MgBetaApplicationSynchronizationTemplateSchemaDirectory', 
               'Get-MgBetaApplicationSynchronizationTemplateSchemaDirectoryCount', 
               'Get-MgBetaApplicationTemplate', 
               'Get-MgBetaApplicationTemplateCount', 
               'Get-MgBetaApplicationTokenIssuancePolicy', 
               'Get-MgBetaApplicationTokenIssuancePolicyByRef', 
               'Get-MgBetaApplicationTokenIssuancePolicyCount', 
               'Get-MgBetaApplicationTokenLifetimePolicy', 
               'Get-MgBetaApplicationTokenLifetimePolicyByRef', 
               'Get-MgBetaApplicationTokenLifetimePolicyCount', 
               'Get-MgBetaApplicationUserOwnedObject', 
               'Get-MgBetaGroupAppRoleAssignment', 
               'Get-MgBetaGroupAppRoleAssignmentCount', 
               'Get-MgBetaOnPremisePublishingProfile', 
               'Get-MgBetaOnPremisePublishingProfileAgent', 
               'Get-MgBetaOnPremisePublishingProfileAgentCount', 
               'Get-MgBetaOnPremisePublishingProfileAgentGroup', 
               'Get-MgBetaOnPremisePublishingProfileAgentGroupAgent', 
               'Get-MgBetaOnPremisePublishingProfileAgentGroupAgentCount', 
               'Get-MgBetaOnPremisePublishingProfileAgentGroupByRef', 
               'Get-MgBetaOnPremisePublishingProfileAgentGroupCount', 
               'Get-MgBetaOnPremisePublishingProfileAgentGroupPublishedResource', 
               'Get-MgBetaOnPremisePublishingProfileAgentGroupPublishedResourceAgentGroup', 
               'Get-MgBetaOnPremisePublishingProfileAgentGroupPublishedResourceAgentGroupByRef', 
               'Get-MgBetaOnPremisePublishingProfileAgentGroupPublishedResourceAgentGroupCount', 
               'Get-MgBetaOnPremisePublishingProfileAgentGroupPublishedResourceCount', 
               'Get-MgBetaOnPremisePublishingProfileConnector', 
               'Get-MgBetaOnPremisePublishingProfileConnectorCount', 
               'Get-MgBetaOnPremisePublishingProfileConnectorGroup', 
               'Get-MgBetaOnPremisePublishingProfileConnectorGroupApplication', 
               'Get-MgBetaOnPremisePublishingProfileConnectorGroupApplicationCount', 
               'Get-MgBetaOnPremisePublishingProfileConnectorGroupApplicationLogo', 
               'Get-MgBetaOnPremisePublishingProfileConnectorGroupCount', 
               'Get-MgBetaOnPremisePublishingProfileConnectorGroupMember', 
               'Get-MgBetaOnPremisePublishingProfileConnectorGroupMemberByRef', 
               'Get-MgBetaOnPremisePublishingProfileConnectorGroupMemberCount', 
               'Get-MgBetaOnPremisePublishingProfileConnectorMemberOf', 
               'Get-MgBetaOnPremisePublishingProfileConnectorMemberOfByRef', 
               'Get-MgBetaOnPremisePublishingProfileConnectorMemberOfCount', 
               'Get-MgBetaOnPremisePublishingProfileCount', 
               'Get-MgBetaOnPremisePublishingProfilePublishedResource', 
               'Get-MgBetaOnPremisePublishingProfilePublishedResourceAgentGroup', 
               'Get-MgBetaOnPremisePublishingProfilePublishedResourceAgentGroupByRef', 
               'Get-MgBetaOnPremisePublishingProfilePublishedResourceAgentGroupCount', 
               'Get-MgBetaOnPremisePublishingProfilePublishedResourceCount', 
               'Get-MgBetaServicePrincipal', 
               'Get-MgBetaServicePrincipalAppManagementPolicy', 
               'Get-MgBetaServicePrincipalAppManagementPolicyCount', 
               'Get-MgBetaServicePrincipalAppRoleAssignedTo', 
               'Get-MgBetaServicePrincipalAppRoleAssignedToCount', 
               'Get-MgBetaServicePrincipalAppRoleAssignment', 
               'Get-MgBetaServicePrincipalAppRoleAssignmentCount', 
               'Get-MgBetaServicePrincipalByAppId', 
               'Get-MgBetaServicePrincipalById', 
               'Get-MgBetaServicePrincipalClaimMappingPolicy', 
               'Get-MgBetaServicePrincipalClaimMappingPolicyByRef', 
               'Get-MgBetaServicePrincipalClaimMappingPolicyCount', 
               'Get-MgBetaServicePrincipalCount', 
               'Get-MgBetaServicePrincipalCreatedObject', 
               'Get-MgBetaServicePrincipalCreatedObjectAsServicePrincipal', 
               'Get-MgBetaServicePrincipalCreatedObjectCount', 
               'Get-MgBetaServicePrincipalCreatedObjectCountAsServicePrincipal', 
               'Get-MgBetaServicePrincipalDelegatedPermissionClassification', 
               'Get-MgBetaServicePrincipalDelegatedPermissionClassificationCount', 
               'Get-MgBetaServicePrincipalDelta', 
               'Get-MgBetaServicePrincipalEndpoint', 
               'Get-MgBetaServicePrincipalEndpointCount', 
               'Get-MgBetaServicePrincipalHomeRealmDiscoveryPolicy', 
               'Get-MgBetaServicePrincipalHomeRealmDiscoveryPolicyByRef', 
               'Get-MgBetaServicePrincipalHomeRealmDiscoveryPolicyCount', 
               'Get-MgBetaServicePrincipalLicenseDetail', 
               'Get-MgBetaServicePrincipalLicenseDetailCount', 
               'Get-MgBetaServicePrincipalMemberGroup', 
               'Get-MgBetaServicePrincipalMemberObject', 
               'Get-MgBetaServicePrincipalMemberOf', 
               'Get-MgBetaServicePrincipalMemberOfAsAdministrativeUnit', 
               'Get-MgBetaServicePrincipalMemberOfAsDirectoryRole', 
               'Get-MgBetaServicePrincipalMemberOfAsGroup', 
               'Get-MgBetaServicePrincipalMemberOfCount', 
               'Get-MgBetaServicePrincipalMemberOfCountAsAdministrativeUnit', 
               'Get-MgBetaServicePrincipalMemberOfCountAsDirectoryRole', 
               'Get-MgBetaServicePrincipalMemberOfCountAsGroup', 
               'Get-MgBetaServicePrincipalOauth2PermissionGrant', 
               'Get-MgBetaServicePrincipalOauth2PermissionGrantCount', 
               'Get-MgBetaServicePrincipalOwnedObject', 
               'Get-MgBetaServicePrincipalOwnedObjectAsApplication', 
               'Get-MgBetaServicePrincipalOwnedObjectAsEndpoint', 
               'Get-MgBetaServicePrincipalOwnedObjectAsGroup', 
               'Get-MgBetaServicePrincipalOwnedObjectAsServicePrincipal', 
               'Get-MgBetaServicePrincipalOwnedObjectCount', 
               'Get-MgBetaServicePrincipalOwnedObjectCountAsApplication', 
               'Get-MgBetaServicePrincipalOwnedObjectCountAsEndpoint', 
               'Get-MgBetaServicePrincipalOwnedObjectCountAsGroup', 
               'Get-MgBetaServicePrincipalOwnedObjectCountAsServicePrincipal', 
               'Get-MgBetaServicePrincipalOwner', 
               'Get-MgBetaServicePrincipalOwnerAsEndpoint', 
               'Get-MgBetaServicePrincipalOwnerAsServicePrincipal', 
               'Get-MgBetaServicePrincipalOwnerAsUser', 
               'Get-MgBetaServicePrincipalOwnerByRef', 
               'Get-MgBetaServicePrincipalOwnerCount', 
               'Get-MgBetaServicePrincipalOwnerCountAsEndpoint', 
               'Get-MgBetaServicePrincipalOwnerCountAsServicePrincipal', 
               'Get-MgBetaServicePrincipalOwnerCountAsUser', 
               'Get-MgBetaServicePrincipalPasswordSingleSignOnCredential', 
               'Get-MgBetaServicePrincipalRemoteDesktopSecurityConfiguration', 
               'Get-MgBetaServicePrincipalRemoteDesktopSecurityConfigurationTargetDeviceGroup', 
               'Get-MgBetaServicePrincipalRemoteDesktopSecurityConfigurationTargetDeviceGroupCount', 
               'Get-MgBetaServicePrincipalSynchronization', 
               'Get-MgBetaServicePrincipalSynchronizationAccessToken', 
               'Get-MgBetaServicePrincipalSynchronizationJob', 
               'Get-MgBetaServicePrincipalSynchronizationJobBulkUpload', 
               'Get-MgBetaServicePrincipalSynchronizationJobBulkUploadContent', 
               'Get-MgBetaServicePrincipalSynchronizationJobCount', 
               'Get-MgBetaServicePrincipalSynchronizationJobSchema', 
               'Get-MgBetaServicePrincipalSynchronizationJobSchemaDirectory', 
               'Get-MgBetaServicePrincipalSynchronizationJobSchemaDirectoryCount', 
               'Get-MgBetaServicePrincipalSynchronizationSecretCount', 
               'Get-MgBetaServicePrincipalSynchronizationTemplate', 
               'Get-MgBetaServicePrincipalSynchronizationTemplateCount', 
               'Get-MgBetaServicePrincipalSynchronizationTemplateSchema', 
               'Get-MgBetaServicePrincipalSynchronizationTemplateSchemaDirectory', 
               'Get-MgBetaServicePrincipalSynchronizationTemplateSchemaDirectoryCount', 
               'Get-MgBetaServicePrincipalTokenIssuancePolicy', 
               'Get-MgBetaServicePrincipalTokenIssuancePolicyCount', 
               'Get-MgBetaServicePrincipalTokenLifetimePolicy', 
               'Get-MgBetaServicePrincipalTokenLifetimePolicyCount', 
               'Get-MgBetaServicePrincipalTransitiveMemberOf', 
               'Get-MgBetaServicePrincipalTransitiveMemberOfAsAdministrativeUnit', 
               'Get-MgBetaServicePrincipalTransitiveMemberOfAsDirectoryRole', 
               'Get-MgBetaServicePrincipalTransitiveMemberOfAsGroup', 
               'Get-MgBetaServicePrincipalTransitiveMemberOfCount', 
               'Get-MgBetaServicePrincipalTransitiveMemberOfCountAsAdministrativeUnit', 
               'Get-MgBetaServicePrincipalTransitiveMemberOfCountAsDirectoryRole', 
               'Get-MgBetaServicePrincipalTransitiveMemberOfCountAsGroup', 
               'Get-MgBetaServicePrincipalUserOwnedObject', 
               'Get-MgBetaUserAppRoleAssignment', 
               'Get-MgBetaUserAppRoleAssignmentCount', 
               'Invoke-MgBetaFilterApplicationSynchronizationJobSchemaOperator', 
               'Invoke-MgBetaFilterApplicationSynchronizationTemplateSchemaOperator', 
               'Invoke-MgBetaFilterServicePrincipalSynchronizationJobSchemaOperator', 
               'Invoke-MgBetaFilterServicePrincipalSynchronizationTemplateSchemaOperator', 
               'Invoke-MgBetaFunctionApplicationSynchronizationJobSchema', 
               'Invoke-MgBetaFunctionApplicationSynchronizationTemplateSchema', 
               'Invoke-MgBetaFunctionServicePrincipalSynchronizationJobSchema', 
               'Invoke-MgBetaFunctionServicePrincipalSynchronizationTemplateSchema', 
               'Invoke-MgBetaInstantiateApplicationTemplate', 
               'Invoke-MgBetaParseApplicationSynchronizationJobSchemaExpression', 
               'Invoke-MgBetaParseApplicationSynchronizationTemplateSchemaExpression', 
               'Invoke-MgBetaParseServicePrincipalSynchronizationJobSchemaExpression', 
               'Invoke-MgBetaParseServicePrincipalSynchronizationTemplateSchemaExpression', 
               'New-MgBetaApplication', 
               'New-MgBetaApplicationAppManagementPolicyByRef', 
               'New-MgBetaApplicationExtensionProperty', 
               'New-MgBetaApplicationFederatedIdentityCredential', 
               'New-MgBetaApplicationOwnerByRef', 
               'New-MgBetaApplicationSynchronizationJob', 
               'New-MgBetaApplicationSynchronizationJobOnDemand', 
               'New-MgBetaApplicationSynchronizationJobSchemaDirectory', 
               'New-MgBetaApplicationSynchronizationTemplate', 
               'New-MgBetaApplicationSynchronizationTemplateSchemaDirectory', 
               'New-MgBetaApplicationTokenIssuancePolicyByRef', 
               'New-MgBetaApplicationTokenLifetimePolicyByRef', 
               'New-MgBetaGroupAppRoleAssignment', 
               'New-MgBetaOnPremisePublishingProfile', 
               'New-MgBetaOnPremisePublishingProfileAgent', 
               'New-MgBetaOnPremisePublishingProfileAgentGroup', 
               'New-MgBetaOnPremisePublishingProfileAgentGroupAgent', 
               'New-MgBetaOnPremisePublishingProfileAgentGroupByRef', 
               'New-MgBetaOnPremisePublishingProfileAgentGroupPublishedResource', 
               'New-MgBetaOnPremisePublishingProfileAgentGroupPublishedResourceAgentGroup', 
               'New-MgBetaOnPremisePublishingProfileAgentGroupPublishedResourceAgentGroupByRef', 
               'New-MgBetaOnPremisePublishingProfileConnector', 
               'New-MgBetaOnPremisePublishingProfileConnectorGroup', 
               'New-MgBetaOnPremisePublishingProfileConnectorGroupMemberByRef', 
               'New-MgBetaOnPremisePublishingProfileConnectorMemberOfByRef', 
               'New-MgBetaOnPremisePublishingProfilePublishedResource', 
               'New-MgBetaOnPremisePublishingProfilePublishedResourceAgentGroup', 
               'New-MgBetaOnPremisePublishingProfilePublishedResourceAgentGroupByRef', 
               'New-MgBetaServicePrincipal', 
               'New-MgBetaServicePrincipalAppRoleAssignedTo', 
               'New-MgBetaServicePrincipalAppRoleAssignment', 
               'New-MgBetaServicePrincipalClaimMappingPolicyByRef', 
               'New-MgBetaServicePrincipalDelegatedPermissionClassification', 
               'New-MgBetaServicePrincipalEndpoint', 
               'New-MgBetaServicePrincipalHomeRealmDiscoveryPolicyByRef', 
               'New-MgBetaServicePrincipalLicenseDetail', 
               'New-MgBetaServicePrincipalOwnerByRef', 
               'New-MgBetaServicePrincipalPasswordSingleSignOnCredential', 
               'New-MgBetaServicePrincipalRemoteDesktopSecurityConfigurationTargetDeviceGroup', 
               'New-MgBetaServicePrincipalSynchronizationJob', 
               'New-MgBetaServicePrincipalSynchronizationJobOnDemand', 
               'New-MgBetaServicePrincipalSynchronizationJobSchemaDirectory', 
               'New-MgBetaServicePrincipalSynchronizationTemplate', 
               'New-MgBetaServicePrincipalSynchronizationTemplateSchemaDirectory', 
               'New-MgBetaUserAppRoleAssignment', 
               'Ping-MgBetaApplicationSynchronization', 
               'Ping-MgBetaServicePrincipalSynchronization', 
               'Remove-MgBetaApplication', 
               'Remove-MgBetaApplicationAppManagementPolicyByRef', 
               'Remove-MgBetaApplicationByAppId', 
               'Remove-MgBetaApplicationByUniqueName', 
               'Remove-MgBetaApplicationConnectorGroupByRef', 
               'Remove-MgBetaApplicationExtensionProperty', 
               'Remove-MgBetaApplicationFederatedIdentityCredential', 
               'Remove-MgBetaApplicationKey', 'Remove-MgBetaApplicationOwnerByRef', 
               'Remove-MgBetaApplicationPassword', 
               'Remove-MgBetaApplicationSynchronization', 
               'Remove-MgBetaApplicationSynchronizationJob', 
               'Remove-MgBetaApplicationSynchronizationJobBulkUpload', 
               'Remove-MgBetaApplicationSynchronizationJobSchema', 
               'Remove-MgBetaApplicationSynchronizationJobSchemaDirectory', 
               'Remove-MgBetaApplicationSynchronizationTemplate', 
               'Remove-MgBetaApplicationSynchronizationTemplateSchema', 
               'Remove-MgBetaApplicationSynchronizationTemplateSchemaDirectory', 
               'Remove-MgBetaApplicationTokenIssuancePolicyByRef', 
               'Remove-MgBetaApplicationTokenLifetimePolicyByRef', 
               'Remove-MgBetaGroupAppRoleAssignment', 
               'Remove-MgBetaOnPremisePublishingProfile', 
               'Remove-MgBetaOnPremisePublishingProfileAgent', 
               'Remove-MgBetaOnPremisePublishingProfileAgentGroup', 
               'Remove-MgBetaOnPremisePublishingProfileAgentGroupAgent', 
               'Remove-MgBetaOnPremisePublishingProfileAgentGroupByRef', 
               'Remove-MgBetaOnPremisePublishingProfileAgentGroupPublishedResource', 
               'Remove-MgBetaOnPremisePublishingProfileAgentGroupPublishedResourceAgentGroupByRef', 
               'Remove-MgBetaOnPremisePublishingProfileConnector', 
               'Remove-MgBetaOnPremisePublishingProfileConnectorGroup', 
               'Remove-MgBetaOnPremisePublishingProfileConnectorGroupMemberByRef', 
               'Remove-MgBetaOnPremisePublishingProfileConnectorMemberOfByRef', 
               'Remove-MgBetaOnPremisePublishingProfilePublishedResource', 
               'Remove-MgBetaOnPremisePublishingProfilePublishedResourceAgentGroupByRef', 
               'Remove-MgBetaServicePrincipal', 
               'Remove-MgBetaServicePrincipalAppManagementPolicy', 
               'Remove-MgBetaServicePrincipalAppRoleAssignedTo', 
               'Remove-MgBetaServicePrincipalAppRoleAssignment', 
               'Remove-MgBetaServicePrincipalByAppId', 
               'Remove-MgBetaServicePrincipalClaimMappingPolicyByRef', 
               'Remove-MgBetaServicePrincipalDelegatedPermissionClassification', 
               'Remove-MgBetaServicePrincipalEndpoint', 
               'Remove-MgBetaServicePrincipalHomeRealmDiscoveryPolicyByRef', 
               'Remove-MgBetaServicePrincipalLicenseDetail', 
               'Remove-MgBetaServicePrincipalOwnerByRef', 
               'Remove-MgBetaServicePrincipalPasswordSingleSignOnCredential', 
               'Remove-MgBetaServicePrincipalRemoteDesktopSecurityConfiguration', 
               'Remove-MgBetaServicePrincipalRemoteDesktopSecurityConfigurationTargetDeviceGroup', 
               'Remove-MgBetaServicePrincipalSynchronization', 
               'Remove-MgBetaServicePrincipalSynchronizationJob', 
               'Remove-MgBetaServicePrincipalSynchronizationJobBulkUpload', 
               'Remove-MgBetaServicePrincipalSynchronizationJobSchema', 
               'Remove-MgBetaServicePrincipalSynchronizationJobSchemaDirectory', 
               'Remove-MgBetaServicePrincipalSynchronizationTemplate', 
               'Remove-MgBetaServicePrincipalSynchronizationTemplateSchema', 
               'Remove-MgBetaServicePrincipalSynchronizationTemplateSchemaDirectory', 
               'Remove-MgBetaUserAppRoleAssignment', 
               'Restart-MgBetaApplicationSynchronizationJob', 
               'Restart-MgBetaServicePrincipalSynchronizationJob', 
               'Set-MgBetaApplicationConnectorGroupByRef', 
               'Set-MgBetaApplicationLogo', 'Set-MgBetaApplicationSynchronization', 
               'Set-MgBetaApplicationSynchronizationJobBulkUploadContent', 
               'Set-MgBetaApplicationSynchronizationSecret', 
               'Set-MgBetaApplicationVerifiedPublisher', 
               'Set-MgBetaOnPremisePublishingProfileConnectorGroupApplicationLogo', 
               'Set-MgBetaServicePrincipalSynchronization', 
               'Set-MgBetaServicePrincipalSynchronizationJobBulkUploadContent', 
               'Set-MgBetaServicePrincipalSynchronizationSecret', 
               'Start-MgBetaApplicationSynchronizationJob', 
               'Start-MgBetaServicePrincipalSynchronizationJob', 
               'Suspend-MgBetaApplicationSynchronizationJob', 
               'Suspend-MgBetaServicePrincipalSynchronizationJob', 
               'Test-MgBetaApplicationProperty', 
               'Test-MgBetaApplicationSynchronizationJobCredential', 
               'Test-MgBetaServicePrincipalProperty', 
               'Test-MgBetaServicePrincipalSynchronizationJobCredential', 
               'Update-MgBetaApplication', 'Update-MgBetaApplicationByAppId', 
               'Update-MgBetaApplicationByUniqueName', 
               'Update-MgBetaApplicationExtensionProperty', 
               'Update-MgBetaApplicationFederatedIdentityCredential', 
               'Update-MgBetaApplicationSynchronizationJob', 
               'Update-MgBetaApplicationSynchronizationJobBulkUpload', 
               'Update-MgBetaApplicationSynchronizationJobSchema', 
               'Update-MgBetaApplicationSynchronizationJobSchemaDirectory', 
               'Update-MgBetaApplicationSynchronizationTemplate', 
               'Update-MgBetaApplicationSynchronizationTemplateSchema', 
               'Update-MgBetaApplicationSynchronizationTemplateSchemaDirectory', 
               'Update-MgBetaGroupAppRoleAssignment', 
               'Update-MgBetaOnPremisePublishingProfile', 
               'Update-MgBetaOnPremisePublishingProfileAgent', 
               'Update-MgBetaOnPremisePublishingProfileAgentGroup', 
               'Update-MgBetaOnPremisePublishingProfileAgentGroupAgent', 
               'Update-MgBetaOnPremisePublishingProfileAgentGroupPublishedResource', 
               'Update-MgBetaOnPremisePublishingProfileConnector', 
               'Update-MgBetaOnPremisePublishingProfileConnectorGroup', 
               'Update-MgBetaOnPremisePublishingProfilePublishedResource', 
               'Update-MgBetaServicePrincipal', 
               'Update-MgBetaServicePrincipalAppRoleAssignedTo', 
               'Update-MgBetaServicePrincipalAppRoleAssignment', 
               'Update-MgBetaServicePrincipalByAppId', 
               'Update-MgBetaServicePrincipalDelegatedPermissionClassification', 
               'Update-MgBetaServicePrincipalEndpoint', 
               'Update-MgBetaServicePrincipalLicenseDetail', 
               'Update-MgBetaServicePrincipalPasswordSingleSignOnCredential', 
               'Update-MgBetaServicePrincipalRemoteDesktopSecurityConfiguration', 
               'Update-MgBetaServicePrincipalRemoteDesktopSecurityConfigurationTargetDeviceGroup', 
               'Update-MgBetaServicePrincipalSynchronizationJob', 
               'Update-MgBetaServicePrincipalSynchronizationJobBulkUpload', 
               'Update-MgBetaServicePrincipalSynchronizationJobSchema', 
               'Update-MgBetaServicePrincipalSynchronizationJobSchemaDirectory', 
               'Update-MgBetaServicePrincipalSynchronizationTemplate', 
               'Update-MgBetaServicePrincipalSynchronizationTemplateSchema', 
               'Update-MgBetaServicePrincipalSynchronizationTemplateSchemaDirectory', 
               'Update-MgBetaUserAppRoleAssignment'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/dev/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIInvwYJKoZIhvcNAQcCoIInsDCCJ6wCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCAp+ekORMXfO2i+
# 6ZtVA8pftJDzyZgBMrHB1qicWQv9a6CCDXYwggX0MIID3KADAgECAhMzAAADTrU8
# esGEb+srAAAAAANOMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjMwMzE2MTg0MzI5WhcNMjQwMzE0MTg0MzI5WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQDdCKiNI6IBFWuvJUmf6WdOJqZmIwYs5G7AJD5UbcL6tsC+EBPDbr36pFGo1bsU
# p53nRyFYnncoMg8FK0d8jLlw0lgexDDr7gicf2zOBFWqfv/nSLwzJFNP5W03DF/1
# 1oZ12rSFqGlm+O46cRjTDFBpMRCZZGddZlRBjivby0eI1VgTD1TvAdfBYQe82fhm
# WQkYR/lWmAK+vW/1+bO7jHaxXTNCxLIBW07F8PBjUcwFxxyfbe2mHB4h1L4U0Ofa
# +HX/aREQ7SqYZz59sXM2ySOfvYyIjnqSO80NGBaz5DvzIG88J0+BNhOu2jl6Dfcq
# jYQs1H/PMSQIK6E7lXDXSpXzAgMBAAGjggFzMIIBbzAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQUnMc7Zn/ukKBsBiWkwdNfsN5pdwAw
# RQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEW
# MBQGA1UEBRMNMjMwMDEyKzUwMDUxNjAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzci
# tW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEG
# CCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0
# MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBAD21v9pHoLdBSNlFAjmk
# mx4XxOZAPsVxxXbDyQv1+kGDe9XpgBnT1lXnx7JDpFMKBwAyIwdInmvhK9pGBa31
# TyeL3p7R2s0L8SABPPRJHAEk4NHpBXxHjm4TKjezAbSqqbgsy10Y7KApy+9UrKa2
# kGmsuASsk95PVm5vem7OmTs42vm0BJUU+JPQLg8Y/sdj3TtSfLYYZAaJwTAIgi7d
# hzn5hatLo7Dhz+4T+MrFd+6LUa2U3zr97QwzDthx+RP9/RZnur4inzSQsG5DCVIM
# pA1l2NWEA3KAca0tI2l6hQNYsaKL1kefdfHCrPxEry8onJjyGGv9YKoLv6AOO7Oh
# JEmbQlz/xksYG2N/JSOJ+QqYpGTEuYFYVWain7He6jgb41JbpOGKDdE/b+V2q/gX
# UgFe2gdwTpCDsvh8SMRoq1/BNXcr7iTAU38Vgr83iVtPYmFhZOVM0ULp/kKTVoir
# IpP2KCxT4OekOctt8grYnhJ16QMjmMv5o53hjNFXOxigkQWYzUO+6w50g0FAeFa8
# 5ugCCB6lXEk21FFB1FdIHpjSQf+LP/W2OV/HfhC3uTPgKbRtXo83TZYEudooyZ/A
# Vu08sibZ3MkGOJORLERNwKm2G7oqdOv4Qj8Z0JrGgMzj46NFKAxkLSpE5oHQYP1H
# tPx1lPfD7iNSbJsP6LiUHXH1MIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
# hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
# IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
# Q29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
# CgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03
# a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akr
# rnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0Rrrg
# OGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
# 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9
# sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAh
# dCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
# A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTB
# w3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmn
# Eyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90
# lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0w
# ggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2o
# ynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBa
# BgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsG
# AQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
# HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsG
# AQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABl
# AG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKb
# C5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11l
# hJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6
# I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0
# wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
# STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQam
# ASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGa
# J+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
# XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA
# 9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33Vt
# Y5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr
# /Xmfwb1tbWrJUnMTDXpQzTGCGZ8wghmbAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNp
# Z25pbmcgUENBIDIwMTECEzMAAANOtTx6wYRv6ysAAAAAA04wDQYJYIZIAWUDBAIB
# BQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIIKWe6BjixX/Rntfidx6kuBr
# pu8tJ+zy4IBnjZYJZ+qFMEIGCisGAQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8A
# cwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEB
# BQAEggEA3NpQ6QrIN0lPwLjYgpacgZ2rozchnLOvgNQU0c3BKAQoB6JBbA2gz076
# tA7KPpHUCcuQX5nikj0Vj0E3GuRYVfeZahpSrbzHGh+qW4Sll2aDTA8HT1R5+OEC
# q9D+aEpPMM1LQotJaoD0p4RP81U020wnifTCvfkiEddGCzOFoTLbUDFAUG1E8HXQ
# lScLK3gJENkJ5tQUhl5auxgFUIA3l3syhSIKMbAX4dwDMF+9JKiSsKMKTScb0PKZ
# eTVqpJd5E396wyUR5CzzFLhwkcYaaEmqj07NubWE6KhJnq7fQh1H8BNEczKVyOme
# 7ReaDiuKDk4CfuPE2VGO+TQobDT2RaGCFykwghclBgorBgEEAYI3AwMBMYIXFTCC
# FxEGCSqGSIb3DQEHAqCCFwIwghb+AgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFZBgsq
# hkiG9w0BCRABBKCCAUgEggFEMIIBQAIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
# AwQCAQUABCAGf+PBzNwo8ZYvITbGKW6K8RUXmJQXux95VIFAm1S3EQIGZV4e1Yod
# GBMyMDIzMTIwNTIwMzgxNy43NTRaMASAAgH0oIHYpIHVMIHSMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
# bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJjAkBgNVBAsTHVRoYWxlcyBUU1MgRVNO
# OjE3OUUtNEJCMC04MjQ2MSUwIwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBT
# ZXJ2aWNloIIReDCCBycwggUPoAMCAQICEzMAAAHg1PwfExUffl0AAQAAAeAwDQYJ
# KoZIhvcNAQELBQAwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwHhcNMjMx
# MDEyMTkwNzE5WhcNMjUwMTEwMTkwNzE5WjCB0jELMAkGA1UEBhMCVVMxEzARBgNV
# BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
# c29mdCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0IElyZWxhbmQgT3Bl
# cmF0aW9ucyBMaW1pdGVkMSYwJAYDVQQLEx1UaGFsZXMgVFNTIEVTTjoxNzlFLTRC
# QjAtODI0NjElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2VydmljZTCC
# AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAKyHnPOhxbvRATnGjb/6fuBh
# h3ZLzotAxAgdLaZ/zkRFUdeSKzyNt3tqorMK7GDvcXdKs+qIMUbvenlH+w53ssPa
# 6rYP760ZuFrABrfserf0kFayNXVzwT7jarJOEjnFMBp+yi+uwQ2TnJuxczceG5FD
# HrII6sF6F879lP6ydY0BBZkZ9t39e/svNRieA5gUnv/YcM/bIMY/QYmd9F0B+ebF
# Yi+PH4AkXahNkFgK85OIaRrDGvhnxOa/5zGL7Oiii7+J9/QHkdJGlfnRfbQ3QXM/
# 5/umBOKG4JoFY1niZ5RVH5PT0+uCjwcqhTbnvUtfK+N+yB2b9rEZvp2Tv4ZwYzEd
# 9A9VsYMuZiCSbaFMk77LwVbklpnw4aHWJXJkEYmJvxRbcThE8FQyOoVkSuKc5OWZ
# 2+WM/j50oblA0tCU53AauvUOZRoQBh89nHK+m5pOXKXdYMJ+ceuLYF8h5y/cXLQM
# OmqLJz5l7MLqGwU0zHV+MEO8L1Fo2zEEQ4iL4BX8YknKXonHGQacSCaLZot2kyJV
# RsFSxn0PlPvHVp0YdsCMzdeiw9jAZ7K9s1WxsZGEBrK/obipX6uxjEpyUA9mbVPl
# jlb3R4MWI0E2xI/NM6F4Ac8Ceax3YWLT+aWCZeqiIMLxyyWZg+i1KY8ZEzMeNTKC
# EI5wF1wxqr6T1/MQo+8tAgMBAAGjggFJMIIBRTAdBgNVHQ4EFgQUcF4XP26dV+8S
# usoA1XXQ2TDSmdIwHwYDVR0jBBgwFoAUn6cVXQBeYl2D9OXSZacbUzUZ6XIwXwYD
# VR0fBFgwVjBUoFKgUIZOaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9j
# cmwvTWljcm9zb2Z0JTIwVGltZS1TdGFtcCUyMFBDQSUyMDIwMTAoMSkuY3JsMGwG
# CCsGAQUFBwEBBGAwXjBcBggrBgEFBQcwAoZQaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENBJTIw
# MjAxMCgxKS5jcnQwDAYDVR0TAQH/BAIwADAWBgNVHSUBAf8EDDAKBggrBgEFBQcD
# CDAOBgNVHQ8BAf8EBAMCB4AwDQYJKoZIhvcNAQELBQADggIBAMATzg6R/A0ldO7M
# qGxD1VJji5yVA1hHb0Hc0Yjtv7WkxQ8iwfflulX5Us64tD3+3NT1JkphWzaAWf2w
# KdAw35RxtQG1iON3HEZ0X23nde4Kg/Wfbx5rEHkZ9bzKnR/2N5A16+w/1pbwJzdf
# RcnJT3cLyawr/kYjMWd63OP0Glq70ua4WUE/Po5pU7rQRbWEoQozY24hAqOcwuRc
# m6Cb0JBeTOCeRBntEKgjKep4pRaQt7b9vusT97WeJcfaVosmmPtsZsawgnpIjbBa
# 55tHfuk0vDkZtbIXjU4mr5dns9dnanBdBS2PY3N3hIfCPEOszquwHLkfkFZ/9bxw
# 8/eRJldtoukHo16afE/AqP/smmGJh5ZR0pmgW6QcX+61rdi5kDJTzCFaoMyYzUS0
# SEbyrDZ/p2KOuKAYNngljiOlllct0uJVz2agfczGjjsKi2AS1WaXvOhgZNmGw42S
# FB1qaloa8Kaux9Q2HHLE8gee/5rgOnx9zSbfVUc7IcRNodq6R7v+Rz+P6XKtOgyC
# qW/+rhPmp/n7Fq2BGTRkcy//hmS32p6qyglr2K4OoJDJXxFs6lwc8D86qlUeGjUy
# o7hVy5VvyA+y0mGnEAuA85tsOcUPlzwWF5sv+B5fz35OW3X4Spk5SiNulnLFRPM5
# XCsSHqvcbC8R3qwj2w1evPhZxDuNMIIHcTCCBVmgAwIBAgITMwAAABXF52ueAptJ
# mQAAAAAAFTANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgT
# Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
# dCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNh
# dGUgQXV0aG9yaXR5IDIwMTAwHhcNMjEwOTMwMTgyMjI1WhcNMzAwOTMwMTgzMjI1
# WjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQD
# Ex1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDCCAiIwDQYJKoZIhvcNAQEB
# BQADggIPADCCAgoCggIBAOThpkzntHIhC3miy9ckeb0O1YLT/e6cBwfSqWxOdcjK
# NVf2AX9sSuDivbk+F2Az/1xPx2b3lVNxWuJ+Slr+uDZnhUYjDLWNE893MsAQGOhg
# fWpSg0S3po5GawcU88V29YZQ3MFEyHFcUTE3oAo4bo3t1w/YJlN8OWECesSq/XJp
# rx2rrPY2vjUmZNqYO7oaezOtgFt+jBAcnVL+tuhiJdxqD89d9P6OU8/W7IVWTe/d
# vI2k45GPsjksUZzpcGkNyjYtcI4xyDUoveO0hyTD4MmPfrVUj9z6BVWYbWg7mka9
# 7aSueik3rMvrg0XnRm7KMtXAhjBcTyziYrLNueKNiOSWrAFKu75xqRdbZ2De+JKR
# Hh09/SDPc31BmkZ1zcRfNN0Sidb9pSB9fvzZnkXftnIv231fgLrbqn427DZM9itu
# qBJR6L8FA6PRc6ZNN3SUHDSCD/AQ8rdHGO2n6Jl8P0zbr17C89XYcz1DTsEzOUyO
# ArxCaC4Q6oRRRuLRvWoYWmEBc8pnol7XKHYC4jMYctenIPDC+hIK12NvDMk2ZItb
# oKaDIV1fMHSRlJTYuVD5C4lh8zYGNRiER9vcG9H9stQcxWv2XFJRXRLbJbqvUAV6
# bMURHXLvjflSxIUXk8A8FdsaN8cIFRg/eKtFtvUeh17aj54WcmnGrnu3tz5q4i6t
# AgMBAAGjggHdMIIB2TASBgkrBgEEAYI3FQEEBQIDAQABMCMGCSsGAQQBgjcVAgQW
# BBQqp1L+ZMSavoKRPEY1Kc8Q/y8E7jAdBgNVHQ4EFgQUn6cVXQBeYl2D9OXSZacb
# UzUZ6XIwXAYDVR0gBFUwUzBRBgwrBgEEAYI3TIN9AQEwQTA/BggrBgEFBQcCARYz
# aHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9Eb2NzL1JlcG9zaXRvcnku
# aHRtMBMGA1UdJQQMMAoGCCsGAQUFBwMIMBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIA
# QwBBMAsGA1UdDwQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB8GA1UdIwQYMBaAFNX2
# VsuP6KJcYmjRPZSQW9fOmhjEMFYGA1UdHwRPME0wS6BJoEeGRWh0dHA6Ly9jcmwu
# bWljcm9zb2Z0LmNvbS9wa2kvY3JsL3Byb2R1Y3RzL01pY1Jvb0NlckF1dF8yMDEw
# LTA2LTIzLmNybDBaBggrBgEFBQcBAQROMEwwSgYIKwYBBQUHMAKGPmh0dHA6Ly93
# d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0XzIwMTAtMDYt
# MjMuY3J0MA0GCSqGSIb3DQEBCwUAA4ICAQCdVX38Kq3hLB9nATEkW+Geckv8qW/q
# XBS2Pk5HZHixBpOXPTEztTnXwnE2P9pkbHzQdTltuw8x5MKP+2zRoZQYIu7pZmc6
# U03dmLq2HnjYNi6cqYJWAAOwBb6J6Gngugnue99qb74py27YP0h1AdkY3m2CDPVt
# I1TkeFN1JFe53Z/zjj3G82jfZfakVqr3lbYoVSfQJL1AoL8ZthISEV09J+BAljis
# 9/kpicO8F7BUhUKz/AyeixmJ5/ALaoHCgRlCGVJ1ijbCHcNhcy4sa3tuPywJeBTp
# kbKpW99Jo3QMvOyRgNI95ko+ZjtPu4b6MhrZlvSP9pEB9s7GdP32THJvEKt1MMU0
# sHrYUP4KWN1APMdUbZ1jdEgssU5HLcEUBHG/ZPkkvnNtyo4JvbMBV0lUZNlz138e
# W0QBjloZkWsNn6Qo3GcZKCS6OEuabvshVGtqRRFHqfG3rsjoiV5PndLQTHa1V1QJ
# sWkBRH58oWFsc/4Ku+xBZj1p/cvBQUl+fpO+y/g75LcVv7TOPqUxUYS8vwLBgqJ7
# Fx0ViY1w/ue10CgaiQuPNtq6TPmb/wrpNPgkNWcr4A245oyZ1uEi6vAnQj0llOZ0
# dFtq0Z4+7X6gMTN9vMvpe784cETRkPHIqzqKOghif9lwY1NNje6CbaUFEMFxBmoQ
# tB1VM1izoXBm8qGCAtQwggI9AgEBMIIBAKGB2KSB1TCB0jELMAkGA1UEBhMCVVMx
# EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
# FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0IElyZWxh
# bmQgT3BlcmF0aW9ucyBMaW1pdGVkMSYwJAYDVQQLEx1UaGFsZXMgVFNTIEVTTjox
# NzlFLTRCQjAtODI0NjElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2Vy
# dmljZaIjCgEBMAcGBSsOAwIaAxUAbfPR1fBX6HxYfyPx8zYzJU5fIQyggYMwgYCk
# fjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQD
# Ex1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDANBgkqhkiG9w0BAQUFAAIF
# AOkZwJcwIhgPMjAyMzEyMDUyMzMwMzFaGA8yMDIzMTIwNjIzMzAzMVowdDA6Bgor
# BgEEAYRZCgQBMSwwKjAKAgUA6RnAlwIBADAHAgEAAgIpwzAHAgEAAgIRYTAKAgUA
# 6RsSFwIBADA2BgorBgEEAYRZCgQCMSgwJjAMBgorBgEEAYRZCgMCoAowCAIBAAID
# B6EgoQowCAIBAAIDAYagMA0GCSqGSIb3DQEBBQUAA4GBAAv7eeSjyRZhAFtU+06i
# Q+/P/rshu6hq2CtBxjFskYqvyrUQhBqt7LPCx/L3hUIGNq1w4/WnU0AEwhJpiix1
# cfJrGQeFNhmEDhZHrHRm4IO63ewQtoJVYSXqteXt2ZrpY7mk+gCgdjznjAd2VV5D
# 966oXnzDqSALnoAQf5PHetQaMYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMCVVMx
# EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
# FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUt
# U3RhbXAgUENBIDIwMTACEzMAAAHg1PwfExUffl0AAQAAAeAwDQYJYIZIAWUDBAIB
# BQCgggFKMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQx
# IgQgoXGECX+hRliqWA9u4b7oAVinsy8fSPV/+bmcpyLDWVkwgfoGCyqGSIb3DQEJ
# EAIvMYHqMIHnMIHkMIG9BCDj7lK/8jnlbTjPvc77DCCSb4TZApY9nJm5whsK/2kK
# wTCBmDCBgKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAw
# DgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24x
# JjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAAB4NT8
# HxMVH35dAAEAAAHgMCIEIM/FogrlsnAYiNMR2qbk9dKJ+rqnZErB/P2p0b3RRssR
# MA0GCSqGSIb3DQEBCwUABIICACH9nA+23AsbDEAZCdpjeqjlGU9EQ6fPOJjP1jpD
# 30aAw+rCRGjadxgIdol9UAfOQ0P56yS9mRCRFrW1sPuTMgM9JsMnXEe2ZYlDQUpC
# zLeKCGDZEwGM8Zo+wOnafBZqHj89rbBVH80okAvAZ/IRfy6P+L5RXC4f00IM4ECJ
# O9kD8hQ73L8bXUGzlA0pUj3JyfmpGKGYoXv80mnl78fhN9gJbOFH83yXTAne9+Xd
# FkNCeE9wDYHQNW+xBR42yihUx4R7CpqmnmlpZCh5cf/bqU95iTfFJqq9V4Xz0mpv
# oQd2mgKbMqiszoKoqvS2fKoHkLPU4Ecgr2/LMRgLJnO6O1mW6RFfSUtrMH0xjBn8
# 5NutS5R/3JTC8/YdP78neKZ3BPKgF64WXT1ZCYUfCBuNhCQJkh0s7P7p8GOPUoIM
# i+UhqBmxRwumNzRn0v+YZ2uyNHi+Go5DCUL2zJu+9YDJTwNoOZ7pgSMCf84uRgWB
# p1lCcRJX9yje9EMN5x2UV+kkAJXpyJhzhZ+vNK+uftN5ZcOHp5Fh4e1hLi26qHQa
# WnVN+pP42RXEYBIOJcwjObdDGWPNJfl9HX828bwG36yz8k0Hbtgr7qD+1vsnWARl
# sOIET2+QpZrPcFZKahqvclezBRhKI1Tr4KcVqVOC7iG3Ejj95WOGn6Bla71MCcJT
# J9z3
# SIG # End signature block
