// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Graph.PowerShell.Identity.SignIns.Client.Models.ODataErrors;
using Microsoft.Graph.PowerShell.Identity.SignIns.Client.Models;
using Microsoft.Graph.PowerShell.Identity.SignIns.Client.Users.Item.Authentication.Fido2Methods.Count;
using Microsoft.Graph.PowerShell.Identity.SignIns.Client.Users.Item.Authentication.Fido2Methods.CreationOptions;
using Microsoft.Graph.PowerShell.Identity.SignIns.Client.Users.Item.Authentication.Fido2Methods.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Microsoft.Graph.PowerShell.Identity.SignIns.Client.Users.Item.Authentication.Fido2Methods
{
    /// <summary>
    /// Builds and executes requests for operations under \users\{user-id}\authentication\fido2Methods
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Fido2MethodsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Count property</summary>
        public global::Microsoft.Graph.PowerShell.Identity.SignIns.Client.Users.Item.Authentication.Fido2Methods.Count.CountRequestBuilder Count
        {
            get => new global::Microsoft.Graph.PowerShell.Identity.SignIns.Client.Users.Item.Authentication.Fido2Methods.Count.CountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The creationOptions property</summary>
        public global::Microsoft.Graph.PowerShell.Identity.SignIns.Client.Users.Item.Authentication.Fido2Methods.CreationOptions.CreationOptionsRequestBuilder CreationOptions
        {
            get => new global::Microsoft.Graph.PowerShell.Identity.SignIns.Client.Users.Item.Authentication.Fido2Methods.CreationOptions.CreationOptionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Microsoft.Graph.PowerShell.Identity.SignIns.Client.users.item.authentication.fido2Methods.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Microsoft.Graph.PowerShell.Identity.SignIns.Client.Users.Item.Authentication.Fido2Methods.Item.Fido2AuthenticationMethodItemRequestBuilder"/></returns>
        public global::Microsoft.Graph.PowerShell.Identity.SignIns.Client.Users.Item.Authentication.Fido2Methods.Item.Fido2AuthenticationMethodItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("fido2AuthenticationMethod%2Did", position);
                return new global::Microsoft.Graph.PowerShell.Identity.SignIns.Client.Users.Item.Authentication.Fido2Methods.Item.Fido2AuthenticationMethodItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Microsoft.Graph.PowerShell.Identity.SignIns.Client.Users.Item.Authentication.Fido2Methods.Fido2MethodsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Fido2MethodsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users/{user%2Did}/authentication/fido2Methods{?%24count,%24expand,%24filter,%24orderby,%24search,%24select,%24skip,%24top}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Microsoft.Graph.PowerShell.Identity.SignIns.Client.Users.Item.Authentication.Fido2Methods.Fido2MethodsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Fido2MethodsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users/{user%2Did}/authentication/fido2Methods{?%24count,%24expand,%24filter,%24orderby,%24search,%24select,%24skip,%24top}", rawUrl)
        {
        }
        /// <summary>
        /// Represents the FIDO2 security keys registered to a user for authentication.
        /// </summary>
        /// <returns>A <see cref="global::Microsoft.Graph.PowerShell.Identity.SignIns.Client.Models.Fido2AuthenticationMethodCollectionResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Microsoft.Graph.PowerShell.Identity.SignIns.Client.Models.ODataErrors.ODataError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Microsoft.Graph.PowerShell.Identity.SignIns.Client.Models.Fido2AuthenticationMethodCollectionResponse?> GetAsync(Action<RequestConfiguration<global::Microsoft.Graph.PowerShell.Identity.SignIns.Client.Users.Item.Authentication.Fido2Methods.Fido2MethodsRequestBuilder.Fido2MethodsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Microsoft.Graph.PowerShell.Identity.SignIns.Client.Models.Fido2AuthenticationMethodCollectionResponse> GetAsync(Action<RequestConfiguration<global::Microsoft.Graph.PowerShell.Identity.SignIns.Client.Users.Item.Authentication.Fido2Methods.Fido2MethodsRequestBuilder.Fido2MethodsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Microsoft.Graph.PowerShell.Identity.SignIns.Client.Models.ODataErrors.ODataError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Microsoft.Graph.PowerShell.Identity.SignIns.Client.Models.Fido2AuthenticationMethodCollectionResponse>(requestInfo, global::Microsoft.Graph.PowerShell.Identity.SignIns.Client.Models.Fido2AuthenticationMethodCollectionResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Represents the FIDO2 security keys registered to a user for authentication.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Microsoft.Graph.PowerShell.Identity.SignIns.Client.Users.Item.Authentication.Fido2Methods.Fido2MethodsRequestBuilder.Fido2MethodsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Microsoft.Graph.PowerShell.Identity.SignIns.Client.Users.Item.Authentication.Fido2Methods.Fido2MethodsRequestBuilder.Fido2MethodsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Microsoft.Graph.PowerShell.Identity.SignIns.Client.Users.Item.Authentication.Fido2Methods.Fido2MethodsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Microsoft.Graph.PowerShell.Identity.SignIns.Client.Users.Item.Authentication.Fido2Methods.Fido2MethodsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Microsoft.Graph.PowerShell.Identity.SignIns.Client.Users.Item.Authentication.Fido2Methods.Fido2MethodsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Represents the FIDO2 security keys registered to a user for authentication.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Fido2MethodsRequestBuilderGetQueryParameters 
        {
            /// <summary>Include count of items</summary>
            [QueryParameter("%24count")]
            public bool? Count { get; set; }
            /// <summary>Expand related entities</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24expand")]
            public string[]? Expand { get; set; }
#nullable restore
#else
            [QueryParameter("%24expand")]
            public string[] Expand { get; set; }
#endif
            /// <summary>Filter items by property values</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24filter")]
            public string? Filter { get; set; }
#nullable restore
#else
            [QueryParameter("%24filter")]
            public string Filter { get; set; }
#endif
            /// <summary>Order items by property values</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24orderby")]
            public string[]? Orderby { get; set; }
#nullable restore
#else
            [QueryParameter("%24orderby")]
            public string[] Orderby { get; set; }
#endif
            /// <summary>Search items by search phrases</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24search")]
            public string? Search { get; set; }
#nullable restore
#else
            [QueryParameter("%24search")]
            public string Search { get; set; }
#endif
            /// <summary>Select properties to be returned</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24select")]
            public string[]? Select { get; set; }
#nullable restore
#else
            [QueryParameter("%24select")]
            public string[] Select { get; set; }
#endif
            /// <summary>Skip the first n items</summary>
            [QueryParameter("%24skip")]
            public int? Skip { get; set; }
            /// <summary>Show only the first n items</summary>
            [QueryParameter("%24top")]
            public int? Top { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Fido2MethodsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Microsoft.Graph.PowerShell.Identity.SignIns.Client.Users.Item.Authentication.Fido2Methods.Fido2MethodsRequestBuilder.Fido2MethodsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
