#
# Module manifest for module 'Microsoft.Graph.Beta.DeviceManagement'
#
# Generated by: Microsoft Corporation
#
# Generated on: 1/15/2024
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Beta.DeviceManagement.psm1'

# Version number of this module.
ModuleVersion = '2.12.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'e28788e6-ed86-49a3-9355-6f0045bd3647'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.12.0'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.Beta.DeviceManagement.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.Beta.DeviceManagement.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-MgBetaAdminEdge', 'Get-MgBetaAdminEdgeInternetExplorerMode', 
               'Get-MgBetaAdminEdgeInternetExplorerModeSiteList', 
               'Get-MgBetaAdminEdgeInternetExplorerModeSiteListCount', 
               'Get-MgBetaAdminEdgeInternetExplorerModeSiteListSharedCookie', 
               'Get-MgBetaAdminEdgeInternetExplorerModeSiteListSharedCookieCount', 
               'Get-MgBetaAdminEdgeInternetExplorerModeSiteListSite', 
               'Get-MgBetaAdminEdgeInternetExplorerModeSiteListSiteCount', 
               'Get-MgBetaDeviceManagement', 
               'Get-MgBetaDeviceManagementAdvancedThreatProtectionOnboardingStateSummary', 
               'Get-MgBetaDeviceManagementAdvancedThreatProtectionOnboardingStateSummaryAdvancedThreatProtectionOnboardingDeviceSettingState', 
               'Get-MgBetaDeviceManagementAdvancedThreatProtectionOnboardingStateSummaryAdvancedThreatProtectionOnboardingDeviceSettingStateCount', 
               'Get-MgBetaDeviceManagementAndroidForWorkAppConfigurationSchema', 
               'Get-MgBetaDeviceManagementAndroidForWorkAppConfigurationSchemaCount', 
               'Get-MgBetaDeviceManagementAndroidForWorkSetting', 
               'Get-MgBetaDeviceManagementAndroidManagedStoreAccountEnterpriseSetting', 
               'Get-MgBetaDeviceManagementAndroidManagedStoreAppConfigurationSchema', 
               'Get-MgBetaDeviceManagementAndroidManagedStoreAppConfigurationSchemaCount', 
               'Get-MgBetaDeviceManagementAssignmentFilter', 
               'Get-MgBetaDeviceManagementAssignmentFilterCount', 
               'Get-MgBetaDeviceManagementCategory', 
               'Get-MgBetaDeviceManagementCategoryCount', 
               'Get-MgBetaDeviceManagementCategorySettingDefinition', 
               'Get-MgBetaDeviceManagementCategorySettingDefinitionCount', 
               'Get-MgBetaDeviceManagementComanagedDevice', 
               'Get-MgBetaDeviceManagementComanagedDeviceAssignmentFilterEvaluationStatusDetail', 
               'Get-MgBetaDeviceManagementComanagedDeviceAssignmentFilterEvaluationStatusDetailCount', 
               'Get-MgBetaDeviceManagementComanagedDeviceCategory', 
               'Get-MgBetaDeviceManagementComanagedDeviceCompliancePolicyState', 
               'Get-MgBetaDeviceManagementComanagedDeviceCompliancePolicyStateCount', 
               'Get-MgBetaDeviceManagementComanagedDeviceConfigurationState', 
               'Get-MgBetaDeviceManagementComanagedDeviceConfigurationStateCount', 
               'Get-MgBetaDeviceManagementComanagedDeviceCount', 
               'Get-MgBetaDeviceManagementComanagedDeviceDetectedApp', 
               'Get-MgBetaDeviceManagementComanagedDeviceDetectedAppCount', 
               'Get-MgBetaDeviceManagementComanagedDeviceHealthScriptState', 
               'Get-MgBetaDeviceManagementComanagedDeviceHealthScriptStateCount', 
               'Get-MgBetaDeviceManagementComanagedDeviceLogCollectionRequest', 
               'Get-MgBetaDeviceManagementComanagedDeviceLogCollectionRequestCount', 
               'Get-MgBetaDeviceManagementComanagedDeviceManagedDeviceMobileAppConfigurationState', 
               'Get-MgBetaDeviceManagementComanagedDeviceManagedDeviceMobileAppConfigurationStateCount', 
               'Get-MgBetaDeviceManagementComanagedDeviceSecurityBaselineState', 
               'Get-MgBetaDeviceManagementComanagedDeviceSecurityBaselineStateCount', 
               'Get-MgBetaDeviceManagementComanagedDeviceSecurityBaselineStateSettingState', 
               'Get-MgBetaDeviceManagementComanagedDeviceSecurityBaselineStateSettingStateCount', 
               'Get-MgBetaDeviceManagementComanagedDeviceUser', 
               'Get-MgBetaDeviceManagementComanagedDeviceWindowsProtectionState', 
               'Get-MgBetaDeviceManagementComanagedDeviceWindowsProtectionStateDetectedMalwareState', 
               'Get-MgBetaDeviceManagementComanagedDeviceWindowsProtectionStateDetectedMalwareStateCount', 
               'Get-MgBetaDeviceManagementCompliancePolicy', 
               'Get-MgBetaDeviceManagementCompliancePolicyAssignment', 
               'Get-MgBetaDeviceManagementCompliancePolicyAssignmentCount', 
               'Get-MgBetaDeviceManagementCompliancePolicyCount', 
               'Get-MgBetaDeviceManagementCompliancePolicyScheduledActionForRule', 
               'Get-MgBetaDeviceManagementCompliancePolicyScheduledActionForRuleCount', 
               'Get-MgBetaDeviceManagementCompliancePolicyScheduledActionForRuleScheduledActionConfiguration', 
               'Get-MgBetaDeviceManagementCompliancePolicyScheduledActionForRuleScheduledActionConfigurationCount', 
               'Get-MgBetaDeviceManagementCompliancePolicySetting', 
               'Get-MgBetaDeviceManagementCompliancePolicySettingCount', 
               'Get-MgBetaDeviceManagementCompliancePolicySettingDefinition', 
               'Get-MgBetaDeviceManagementCompliancePolicySettingDefinitionCount', 
               'Get-MgBetaDeviceManagementComplianceSetting', 
               'Get-MgBetaDeviceManagementComplianceSettingCount', 
               'Get-MgBetaDeviceManagementConfigurationPolicy', 
               'Get-MgBetaDeviceManagementConfigurationPolicyAssignment', 
               'Get-MgBetaDeviceManagementConfigurationPolicyAssignmentCount', 
               'Get-MgBetaDeviceManagementConfigurationPolicyCount', 
               'Get-MgBetaDeviceManagementConfigurationPolicySetting', 
               'Get-MgBetaDeviceManagementConfigurationPolicySettingCount', 
               'Get-MgBetaDeviceManagementConfigurationPolicySettingDefinition', 
               'Get-MgBetaDeviceManagementConfigurationPolicySettingDefinitionCount', 
               'Get-MgBetaDeviceManagementConfigurationPolicyTemplate', 
               'Get-MgBetaDeviceManagementConfigurationPolicyTemplateCount', 
               'Get-MgBetaDeviceManagementConfigurationPolicyTemplateSettingDefinition', 
               'Get-MgBetaDeviceManagementConfigurationPolicyTemplateSettingDefinitionCount', 
               'Get-MgBetaDeviceManagementConfigurationPolicyTemplateSettingTemplate', 
               'Get-MgBetaDeviceManagementConfigurationPolicyTemplateSettingTemplateCount', 
               'Get-MgBetaDeviceManagementConfigurationSetting', 
               'Get-MgBetaDeviceManagementConfigurationSettingCount', 
               'Get-MgBetaDeviceManagementDataSharingConsent', 
               'Get-MgBetaDeviceManagementDataSharingConsentCount', 
               'Get-MgBetaDeviceManagementDerivedCredential', 
               'Get-MgBetaDeviceManagementDerivedCredentialCount', 
               'Get-MgBetaDeviceManagementDetectedApp', 
               'Get-MgBetaDeviceManagementDetectedAppCount', 
               'Get-MgBetaDeviceManagementDetectedAppManagedDevice', 
               'Get-MgBetaDeviceManagementDetectedAppManagedDeviceCount', 
               'Get-MgBetaDeviceManagementDeviceCategory', 
               'Get-MgBetaDeviceManagementDeviceCategoryCount', 
               'Get-MgBetaDeviceManagementDeviceCompliancePolicy', 
               'Get-MgBetaDeviceManagementDeviceCompliancePolicyAssignment', 
               'Get-MgBetaDeviceManagementDeviceCompliancePolicyAssignmentCount', 
               'Get-MgBetaDeviceManagementDeviceCompliancePolicyCount', 
               'Get-MgBetaDeviceManagementDeviceCompliancePolicyDeviceSettingStateSummary', 
               'Get-MgBetaDeviceManagementDeviceCompliancePolicyDeviceSettingStateSummaryCount', 
               'Get-MgBetaDeviceManagementDeviceCompliancePolicyDeviceStateSummary', 
               'Get-MgBetaDeviceManagementDeviceCompliancePolicyDeviceStatus', 
               'Get-MgBetaDeviceManagementDeviceCompliancePolicyDeviceStatusCount', 
               'Get-MgBetaDeviceManagementDeviceCompliancePolicyDeviceStatusOverview', 
               'Get-MgBetaDeviceManagementDeviceCompliancePolicyScheduledActionForRule', 
               'Get-MgBetaDeviceManagementDeviceCompliancePolicyScheduledActionForRuleCount', 
               'Get-MgBetaDeviceManagementDeviceCompliancePolicyScheduledActionForRuleScheduledActionConfiguration', 
               'Get-MgBetaDeviceManagementDeviceCompliancePolicyScheduledActionForRuleScheduledActionConfigurationCount', 
               'Get-MgBetaDeviceManagementDeviceCompliancePolicySettingStateSummary', 
               'Get-MgBetaDeviceManagementDeviceCompliancePolicySettingStateSummaryCount', 
               'Get-MgBetaDeviceManagementDeviceCompliancePolicySettingStateSummaryDeviceComplianceSettingState', 
               'Get-MgBetaDeviceManagementDeviceCompliancePolicySettingStateSummaryDeviceComplianceSettingStateCount', 
               'Get-MgBetaDeviceManagementDeviceCompliancePolicyUserStatus', 
               'Get-MgBetaDeviceManagementDeviceCompliancePolicyUserStatusCount', 
               'Get-MgBetaDeviceManagementDeviceCompliancePolicyUserStatusOverview', 
               'Get-MgBetaDeviceManagementDeviceConfiguration', 
               'Get-MgBetaDeviceManagementDeviceConfigurationAssignment', 
               'Get-MgBetaDeviceManagementDeviceConfigurationAssignmentCount', 
               'Get-MgBetaDeviceManagementDeviceConfigurationConflictSummary', 
               'Get-MgBetaDeviceManagementDeviceConfigurationConflictSummaryCount', 
               'Get-MgBetaDeviceManagementDeviceConfigurationCount', 
               'Get-MgBetaDeviceManagementDeviceConfigurationDeviceSettingStateSummary', 
               'Get-MgBetaDeviceManagementDeviceConfigurationDeviceSettingStateSummaryCount', 
               'Get-MgBetaDeviceManagementDeviceConfigurationDeviceStateSummary', 
               'Get-MgBetaDeviceManagementDeviceConfigurationDeviceStatus', 
               'Get-MgBetaDeviceManagementDeviceConfigurationDeviceStatusCount', 
               'Get-MgBetaDeviceManagementDeviceConfigurationDeviceStatusOverview', 
               'Get-MgBetaDeviceManagementDeviceConfigurationGroupAssignment', 
               'Get-MgBetaDeviceManagementDeviceConfigurationGroupAssignmentCount', 
               'Get-MgBetaDeviceManagementDeviceConfigurationGroupAssignmentDeviceConfiguration', 
               'Get-MgBetaDeviceManagementDeviceConfigurationUserStateSummary', 
               'Get-MgBetaDeviceManagementDeviceConfigurationUserStatus', 
               'Get-MgBetaDeviceManagementDeviceConfigurationUserStatusCount', 
               'Get-MgBetaDeviceManagementDeviceConfigurationUserStatusOverview', 
               'Get-MgBetaDeviceManagementDeviceHealthScript', 
               'Get-MgBetaDeviceManagementDeviceHealthScriptAssignment', 
               'Get-MgBetaDeviceManagementDeviceHealthScriptAssignmentCount', 
               'Get-MgBetaDeviceManagementDeviceHealthScriptCount', 
               'Get-MgBetaDeviceManagementDeviceHealthScriptDeviceRunState', 
               'Get-MgBetaDeviceManagementDeviceHealthScriptDeviceRunStateCount', 
               'Get-MgBetaDeviceManagementDeviceHealthScriptDeviceRunStateManagedDevice', 
               'Get-MgBetaDeviceManagementDeviceHealthScriptRunSummary', 
               'Get-MgBetaDeviceManagementDeviceShellScript', 
               'Get-MgBetaDeviceManagementDeviceShellScriptAssignment', 
               'Get-MgBetaDeviceManagementDeviceShellScriptAssignmentCount', 
               'Get-MgBetaDeviceManagementDeviceShellScriptCount', 
               'Get-MgBetaDeviceManagementDeviceShellScriptDeviceRunState', 
               'Get-MgBetaDeviceManagementDeviceShellScriptDeviceRunStateCount', 
               'Get-MgBetaDeviceManagementDeviceShellScriptDeviceRunStateManagedDevice', 
               'Get-MgBetaDeviceManagementDeviceShellScriptGroupAssignment', 
               'Get-MgBetaDeviceManagementDeviceShellScriptGroupAssignmentCount', 
               'Get-MgBetaDeviceManagementDeviceShellScriptRunSummary', 
               'Get-MgBetaDeviceManagementDeviceShellScriptUserRunState', 
               'Get-MgBetaDeviceManagementDeviceShellScriptUserRunStateCount', 
               'Get-MgBetaDeviceManagementDeviceShellScriptUserRunStateDeviceRunState', 
               'Get-MgBetaDeviceManagementEmbeddedSimActivationCodePool', 
               'Get-MgBetaDeviceManagementEmbeddedSimActivationCodePoolAssignment', 
               'Get-MgBetaDeviceManagementEmbeddedSimActivationCodePoolAssignmentCount', 
               'Get-MgBetaDeviceManagementEmbeddedSimActivationCodePoolCount', 
               'Get-MgBetaDeviceManagementEmbeddedSimActivationCodePoolDeviceState', 
               'Get-MgBetaDeviceManagementEmbeddedSimActivationCodePoolDeviceStateCount', 
               'Get-MgBetaDeviceManagementGroupPolicyConfiguration', 
               'Get-MgBetaDeviceManagementGroupPolicyConfigurationAssignment', 
               'Get-MgBetaDeviceManagementGroupPolicyConfigurationAssignmentCount', 
               'Get-MgBetaDeviceManagementGroupPolicyConfigurationCount', 
               'Get-MgBetaDeviceManagementGroupPolicyConfigurationDefinitionValue', 
               'Get-MgBetaDeviceManagementGroupPolicyConfigurationDefinitionValueCount', 
               'Get-MgBetaDeviceManagementGroupPolicyConfigurationDefinitionValueDefinition', 
               'Get-MgBetaDeviceManagementGroupPolicyConfigurationDefinitionValuePresentationValue', 
               'Get-MgBetaDeviceManagementIntent', 
               'Get-MgBetaDeviceManagementIntentAssignment', 
               'Get-MgBetaDeviceManagementIntentAssignmentCount', 
               'Get-MgBetaDeviceManagementIntentCategory', 
               'Get-MgBetaDeviceManagementIntentCategoryCount', 
               'Get-MgBetaDeviceManagementIntentCategorySetting', 
               'Get-MgBetaDeviceManagementIntentCategorySettingCount', 
               'Get-MgBetaDeviceManagementIntentCategorySettingDefinition', 
               'Get-MgBetaDeviceManagementIntentCategorySettingDefinitionCount', 
               'Get-MgBetaDeviceManagementIntentCount', 
               'Get-MgBetaDeviceManagementIntentDeviceSettingStateSummary', 
               'Get-MgBetaDeviceManagementIntentDeviceSettingStateSummaryCount', 
               'Get-MgBetaDeviceManagementIntentDeviceState', 
               'Get-MgBetaDeviceManagementIntentDeviceStateCount', 
               'Get-MgBetaDeviceManagementIntentDeviceStateSummary', 
               'Get-MgBetaDeviceManagementIntentSetting', 
               'Get-MgBetaDeviceManagementIntentSettingCount', 
               'Get-MgBetaDeviceManagementIntentUserState', 
               'Get-MgBetaDeviceManagementIntentUserStateCount', 
               'Get-MgBetaDeviceManagementIntentUserStateSummary', 
               'Get-MgBetaDeviceManagementMacOSSoftwareUpdateAccountSummary', 
               'Get-MgBetaDeviceManagementMacOSSoftwareUpdateAccountSummaryCategorySummary', 
               'Get-MgBetaDeviceManagementMacOSSoftwareUpdateAccountSummaryCategorySummaryCount', 
               'Get-MgBetaDeviceManagementMacOSSoftwareUpdateAccountSummaryCategorySummaryUpdateStateSummary', 
               'Get-MgBetaDeviceManagementMacOSSoftwareUpdateAccountSummaryCategorySummaryUpdateStateSummaryCount', 
               'Get-MgBetaDeviceManagementMacOSSoftwareUpdateAccountSummaryCount', 
               'Get-MgBetaDeviceManagementManagedDevice', 
               'Get-MgBetaDeviceManagementManagedDeviceAssignmentFilterEvaluationStatusDetail', 
               'Get-MgBetaDeviceManagementManagedDeviceAssignmentFilterEvaluationStatusDetailCount', 
               'Get-MgBetaDeviceManagementManagedDeviceCategory', 
               'Get-MgBetaDeviceManagementManagedDeviceCompliancePolicyState', 
               'Get-MgBetaDeviceManagementManagedDeviceCompliancePolicyStateCount', 
               'Get-MgBetaDeviceManagementManagedDeviceConfigurationState', 
               'Get-MgBetaDeviceManagementManagedDeviceConfigurationStateCount', 
               'Get-MgBetaDeviceManagementManagedDeviceCount', 
               'Get-MgBetaDeviceManagementManagedDeviceDetectedApp', 
               'Get-MgBetaDeviceManagementManagedDeviceDetectedAppCount', 
               'Get-MgBetaDeviceManagementManagedDeviceEncryptionState', 
               'Get-MgBetaDeviceManagementManagedDeviceEncryptionStateCount', 
               'Get-MgBetaDeviceManagementManagedDeviceHealthScriptState', 
               'Get-MgBetaDeviceManagementManagedDeviceHealthScriptStateCount', 
               'Get-MgBetaDeviceManagementManagedDeviceLogCollectionRequest', 
               'Get-MgBetaDeviceManagementManagedDeviceLogCollectionRequestCount', 
               'Get-MgBetaDeviceManagementManagedDeviceMobileAppConfigurationState', 
               'Get-MgBetaDeviceManagementManagedDeviceMobileAppConfigurationStateCount', 
               'Get-MgBetaDeviceManagementManagedDeviceOverview', 
               'Get-MgBetaDeviceManagementManagedDeviceSecurityBaselineState', 
               'Get-MgBetaDeviceManagementManagedDeviceSecurityBaselineStateCount', 
               'Get-MgBetaDeviceManagementManagedDeviceSecurityBaselineStateSettingState', 
               'Get-MgBetaDeviceManagementManagedDeviceSecurityBaselineStateSettingStateCount', 
               'Get-MgBetaDeviceManagementManagedDeviceUser', 
               'Get-MgBetaDeviceManagementManagedDeviceWindowsProtectionState', 
               'Get-MgBetaDeviceManagementManagedDeviceWindowsProtectionStateDetectedMalwareState', 
               'Get-MgBetaDeviceManagementManagedDeviceWindowsProtectionStateDetectedMalwareStateCount', 
               'Get-MgBetaDeviceManagementMicrosoftTunnelConfiguration', 
               'Get-MgBetaDeviceManagementMicrosoftTunnelConfigurationCount', 
               'Get-MgBetaDeviceManagementMicrosoftTunnelHealthThreshold', 
               'Get-MgBetaDeviceManagementMicrosoftTunnelHealthThresholdCount', 
               'Get-MgBetaDeviceManagementMicrosoftTunnelServerLogCollectionResponse', 
               'Get-MgBetaDeviceManagementMicrosoftTunnelServerLogCollectionResponseCount', 
               'Get-MgBetaDeviceManagementMicrosoftTunnelSite', 
               'Get-MgBetaDeviceManagementMicrosoftTunnelSiteCount', 
               'Get-MgBetaDeviceManagementMicrosoftTunnelSiteMicrosoftTunnelConfiguration', 
               'Get-MgBetaDeviceManagementMicrosoftTunnelSiteMicrosoftTunnelServer', 
               'Get-MgBetaDeviceManagementMicrosoftTunnelSiteMicrosoftTunnelServerCount', 
               'Get-MgBetaDeviceManagementMobileAppTroubleshootingEvent', 
               'Get-MgBetaDeviceManagementMobileAppTroubleshootingEventAppLogCollectionRequest', 
               'Get-MgBetaDeviceManagementMobileAppTroubleshootingEventAppLogCollectionRequestCount', 
               'Get-MgBetaDeviceManagementMobileAppTroubleshootingEventCount', 
               'Get-MgBetaDeviceManagementMonitoring', 
               'Get-MgBetaDeviceManagementMonitoringAlertRecord', 
               'Get-MgBetaDeviceManagementMonitoringAlertRecordCount', 
               'Get-MgBetaDeviceManagementMonitoringAlertRule', 
               'Get-MgBetaDeviceManagementMonitoringAlertRuleCount', 
               'Get-MgBetaDeviceManagementNotificationMessageTemplate', 
               'Get-MgBetaDeviceManagementNotificationMessageTemplateCount', 
               'Get-MgBetaDeviceManagementNotificationMessageTemplateLocalizedNotificationMessage', 
               'Get-MgBetaDeviceManagementNotificationMessageTemplateLocalizedNotificationMessageCount', 
               'Get-MgBetaDeviceManagementRemoteActionAudit', 
               'Get-MgBetaDeviceManagementRemoteActionAuditCount', 
               'Get-MgBetaDeviceManagementResourceAccessProfile', 
               'Get-MgBetaDeviceManagementResourceAccessProfileAssignment', 
               'Get-MgBetaDeviceManagementResourceAccessProfileAssignmentCount', 
               'Get-MgBetaDeviceManagementResourceAccessProfileCount', 
               'Get-MgBetaDeviceManagementReusableSetting', 
               'Get-MgBetaDeviceManagementReusableSettingCount', 
               'Get-MgBetaDeviceManagementScript', 
               'Get-MgBetaDeviceManagementScriptAssignment', 
               'Get-MgBetaDeviceManagementScriptAssignmentCount', 
               'Get-MgBetaDeviceManagementScriptCount', 
               'Get-MgBetaDeviceManagementScriptDeviceRunState', 
               'Get-MgBetaDeviceManagementScriptDeviceRunStateCount', 
               'Get-MgBetaDeviceManagementScriptDeviceRunStateManagedDevice', 
               'Get-MgBetaDeviceManagementScriptGroupAssignment', 
               'Get-MgBetaDeviceManagementScriptGroupAssignmentCount', 
               'Get-MgBetaDeviceManagementScriptRunSummary', 
               'Get-MgBetaDeviceManagementScriptUserRunState', 
               'Get-MgBetaDeviceManagementScriptUserRunStateCount', 
               'Get-MgBetaDeviceManagementScriptUserRunStateDeviceRunState', 
               'Get-MgBetaDeviceManagementSettingDefinition', 
               'Get-MgBetaDeviceManagementSettingDefinitionCount', 
               'Get-MgBetaDeviceManagementSoftwareUpdateStatusSummary', 
               'Get-MgBetaDeviceManagementTemplate', 
               'Get-MgBetaDeviceManagementTemplateCategory', 
               'Get-MgBetaDeviceManagementTemplateCategoryCount', 
               'Get-MgBetaDeviceManagementTemplateCategoryRecommendedSetting', 
               'Get-MgBetaDeviceManagementTemplateCategoryRecommendedSettingCount', 
               'Get-MgBetaDeviceManagementTemplateCategorySettingDefinition', 
               'Get-MgBetaDeviceManagementTemplateCategorySettingDefinitionCount', 
               'Get-MgBetaDeviceManagementTemplateCount', 
               'Get-MgBetaDeviceManagementTemplateMigratableTo', 
               'Get-MgBetaDeviceManagementTemplateMigratableToCategory', 
               'Get-MgBetaDeviceManagementTemplateMigratableToCategoryCount', 
               'Get-MgBetaDeviceManagementTemplateMigratableToCategoryRecommendedSetting', 
               'Get-MgBetaDeviceManagementTemplateMigratableToCategoryRecommendedSettingCount', 
               'Get-MgBetaDeviceManagementTemplateMigratableToCategorySettingDefinition', 
               'Get-MgBetaDeviceManagementTemplateMigratableToCategorySettingDefinitionCount', 
               'Get-MgBetaDeviceManagementTemplateMigratableToCount', 
               'Get-MgBetaDeviceManagementTemplateMigratableToSetting', 
               'Get-MgBetaDeviceManagementTemplateMigratableToSettingCount', 
               'Get-MgBetaDeviceManagementTemplateSetting', 
               'Get-MgBetaDeviceManagementTemplateSettingCount', 
               'Get-MgBetaDeviceManagementTroubleshootingEvent', 
               'Get-MgBetaDeviceManagementTroubleshootingEventCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticAnomaly', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticAnomalyCorrelationGroupOverview', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticAnomalyCorrelationGroupOverviewCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticAnomalyCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticAnomalyDevice', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticAnomalyDeviceCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformance', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersion', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionDetail', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionDetailCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionDeviceId', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionDeviceIdCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByOsversion', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByOsversionCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticAppHealthDeviceModelPerformance', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticAppHealthDeviceModelPerformanceCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticAppHealthDevicePerformance', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticAppHealthDevicePerformanceCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticAppHealthDevicePerformanceDetail', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticAppHealthDevicePerformanceDetailCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticAppHealthOSVersionPerformance', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticAppHealthOSVersionPerformanceCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticAppHealthOverview', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticAppHealthOverviewMetricValue', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticAppHealthOverviewMetricValueCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticBaseline', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticBaselineAppHealthMetric', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticBaselineBatteryHealthMetric', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticBaselineBestPracticeMetric', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticBaselineCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticBaselineDeviceBootPerformanceMetric', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticBaselineRebootAnalyticMetric', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticBaselineResourcePerformanceMetric', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticBaselineWorkFromAnywhereMetric', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthAppImpact', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthAppImpactCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthCapacityDetail', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthDeviceAppImpact', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthDeviceAppImpactCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthDevicePerformance', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthDevicePerformanceCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthDeviceRuntimeHistory', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthDeviceRuntimeHistoryCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthModelPerformance', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthModelPerformanceCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthOSPerformance', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthOSPerformanceCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthRuntimeDetail', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticCategory', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticCategoryCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticCategoryMetricValue', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticCategoryMetricValueCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticDeviceMetricHistory', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticDeviceMetricHistoryCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticDevicePerformance', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticDevicePerformanceCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticDeviceScope', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticDeviceScopeCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticDeviceScore', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticDeviceScoreCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticDeviceStartupHistory', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticDeviceStartupHistoryCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticDeviceStartupProcess', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticDeviceStartupProcessCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticDeviceStartupProcessPerformance', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticDeviceStartupProcessPerformanceCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticDeviceTimelineEvent', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticDeviceTimelineEventCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticDeviceWithoutCloudIdentity', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticDeviceWithoutCloudIdentityCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticImpactingProcess', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticImpactingProcessCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticMetricHistory', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticMetricHistoryCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticModelScore', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticModelScoreCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticNotAutopilotReadyDevice', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticNotAutopilotReadyDeviceCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticOverview', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticRemoteConnection', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticRemoteConnectionCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticResourcePerformance', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticResourcePerformanceCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticScoreHistory', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticScoreHistoryCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticWorkFromAnywhereHardwareReadinessMetric', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticWorkFromAnywhereMetric', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticWorkFromAnywhereMetricCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticWorkFromAnywhereMetricDevice', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticWorkFromAnywhereMetricDeviceCount', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticWorkFromAnywhereModelPerformance', 
               'Get-MgBetaDeviceManagementUserExperienceAnalyticWorkFromAnywhereModelPerformanceCount', 
               'Get-MgBetaDeviceManagementWindowsInformationProtectionAppLearningSummary', 
               'Get-MgBetaDeviceManagementWindowsInformationProtectionAppLearningSummaryCount', 
               'Get-MgBetaDeviceManagementWindowsInformationProtectionNetworkLearningSummary', 
               'Get-MgBetaDeviceManagementWindowsInformationProtectionNetworkLearningSummaryCount', 
               'Get-MgBetaDeviceManagementWindowsMalwareInformation', 
               'Get-MgBetaDeviceManagementWindowsMalwareInformationCount', 
               'Get-MgBetaDeviceManagementWindowsMalwareInformationDeviceMalwareState', 
               'Get-MgBetaDeviceManagementWindowsMalwareInformationDeviceMalwareStateCount', 
               'Get-MgBetaDeviceManagementWindowsQualityUpdateProfile', 
               'Get-MgBetaDeviceManagementWindowsQualityUpdateProfileAssignment', 
               'Get-MgBetaDeviceManagementWindowsQualityUpdateProfileAssignmentCount', 
               'Get-MgBetaDeviceManagementWindowsQualityUpdateProfileCount', 
               'New-MgBetaAdminEdgeInternetExplorerModeSiteList', 
               'New-MgBetaAdminEdgeInternetExplorerModeSiteListSharedCookie', 
               'New-MgBetaAdminEdgeInternetExplorerModeSiteListSite', 
               'New-MgBetaDeviceManagementAdvancedThreatProtectionOnboardingStateSummaryAdvancedThreatProtectionOnboardingDeviceSettingState', 
               'New-MgBetaDeviceManagementAndroidForWorkAppConfigurationSchema', 
               'New-MgBetaDeviceManagementAndroidManagedStoreAppConfigurationSchema', 
               'New-MgBetaDeviceManagementAssignmentFilter', 
               'New-MgBetaDeviceManagementCategory', 
               'New-MgBetaDeviceManagementCategorySettingDefinition', 
               'New-MgBetaDeviceManagementComanagedDevice', 
               'New-MgBetaDeviceManagementComanagedDeviceAssignmentFilterEvaluationStatusDetail', 
               'New-MgBetaDeviceManagementComanagedDeviceCompliancePolicyState', 
               'New-MgBetaDeviceManagementComanagedDeviceConfigurationState', 
               'New-MgBetaDeviceManagementComanagedDeviceHealthScriptState', 
               'New-MgBetaDeviceManagementComanagedDeviceManagedDeviceMobileAppConfigurationState', 
               'New-MgBetaDeviceManagementComanagedDeviceSecurityBaselineState', 
               'New-MgBetaDeviceManagementComanagedDeviceSecurityBaselineStateSettingState', 
               'New-MgBetaDeviceManagementComanagedDeviceWindowsProtectionStateDetectedMalwareState', 
               'New-MgBetaDeviceManagementCompliancePolicy', 
               'New-MgBetaDeviceManagementCompliancePolicyAssignment', 
               'New-MgBetaDeviceManagementCompliancePolicyScheduledActionForRule', 
               'New-MgBetaDeviceManagementCompliancePolicyScheduledActionForRuleScheduledActionConfiguration', 
               'New-MgBetaDeviceManagementCompliancePolicySetting', 
               'New-MgBetaDeviceManagementComplianceSetting', 
               'New-MgBetaDeviceManagementConfigurationPolicy', 
               'New-MgBetaDeviceManagementConfigurationPolicyAssignment', 
               'New-MgBetaDeviceManagementConfigurationPolicySetting', 
               'New-MgBetaDeviceManagementConfigurationPolicyTemplate', 
               'New-MgBetaDeviceManagementConfigurationPolicyTemplateSettingDefinition', 
               'New-MgBetaDeviceManagementConfigurationPolicyTemplateSettingTemplate', 
               'New-MgBetaDeviceManagementConfigurationSetting', 
               'New-MgBetaDeviceManagementDataSharingConsent', 
               'New-MgBetaDeviceManagementDerivedCredential', 
               'New-MgBetaDeviceManagementDetectedApp', 
               'New-MgBetaDeviceManagementDeviceCategory', 
               'New-MgBetaDeviceManagementDeviceCompliancePolicy', 
               'New-MgBetaDeviceManagementDeviceCompliancePolicyAssignment', 
               'New-MgBetaDeviceManagementDeviceCompliancePolicyDeviceSettingStateSummary', 
               'New-MgBetaDeviceManagementDeviceCompliancePolicyDeviceStatus', 
               'New-MgBetaDeviceManagementDeviceCompliancePolicyScheduledActionForRule', 
               'New-MgBetaDeviceManagementDeviceCompliancePolicyScheduledActionForRuleScheduledActionConfiguration', 
               'New-MgBetaDeviceManagementDeviceCompliancePolicySettingStateSummary', 
               'New-MgBetaDeviceManagementDeviceCompliancePolicySettingStateSummaryDeviceComplianceSettingState', 
               'New-MgBetaDeviceManagementDeviceCompliancePolicyUserStatus', 
               'New-MgBetaDeviceManagementDeviceConfiguration', 
               'New-MgBetaDeviceManagementDeviceConfigurationAssignment', 
               'New-MgBetaDeviceManagementDeviceConfigurationConflictSummary', 
               'New-MgBetaDeviceManagementDeviceConfigurationDeviceSettingStateSummary', 
               'New-MgBetaDeviceManagementDeviceConfigurationDeviceStatus', 
               'New-MgBetaDeviceManagementDeviceConfigurationGroupAssignment', 
               'New-MgBetaDeviceManagementDeviceConfigurationUserStatus', 
               'New-MgBetaDeviceManagementDeviceHealthScript', 
               'New-MgBetaDeviceManagementDeviceHealthScriptAssignment', 
               'New-MgBetaDeviceManagementDeviceHealthScriptDeviceRunState', 
               'New-MgBetaDeviceManagementDeviceShellScript', 
               'New-MgBetaDeviceManagementDeviceShellScriptAssignment', 
               'New-MgBetaDeviceManagementDeviceShellScriptDeviceRunState', 
               'New-MgBetaDeviceManagementDeviceShellScriptGroupAssignment', 
               'New-MgBetaDeviceManagementDeviceShellScriptUserRunState', 
               'New-MgBetaDeviceManagementDeviceShellScriptUserRunStateDeviceRunState', 
               'New-MgBetaDeviceManagementEmbeddedSimActivationCodePool', 
               'New-MgBetaDeviceManagementEmbeddedSimActivationCodePoolAssignment', 
               'New-MgBetaDeviceManagementEmbeddedSimActivationCodePoolDeviceState', 
               'New-MgBetaDeviceManagementGroupPolicyConfiguration', 
               'New-MgBetaDeviceManagementGroupPolicyConfigurationAssignment', 
               'New-MgBetaDeviceManagementGroupPolicyConfigurationDefinitionValue', 
               'New-MgBetaDeviceManagementGroupPolicyConfigurationDefinitionValuePresentationValue', 
               'New-MgBetaDeviceManagementIntent', 
               'New-MgBetaDeviceManagementIntentAssignment', 
               'New-MgBetaDeviceManagementIntentCategory', 
               'New-MgBetaDeviceManagementIntentCategorySetting', 
               'New-MgBetaDeviceManagementIntentCategorySettingDefinition', 
               'New-MgBetaDeviceManagementIntentDeviceSettingStateSummary', 
               'New-MgBetaDeviceManagementIntentDeviceState', 
               'New-MgBetaDeviceManagementIntentSetting', 
               'New-MgBetaDeviceManagementIntentUserState', 
               'New-MgBetaDeviceManagementMacOSSoftwareUpdateAccountSummary', 
               'New-MgBetaDeviceManagementMacOSSoftwareUpdateAccountSummaryCategorySummary', 
               'New-MgBetaDeviceManagementMacOSSoftwareUpdateAccountSummaryCategorySummaryUpdateStateSummary', 
               'New-MgBetaDeviceManagementManagedDevice', 
               'New-MgBetaDeviceManagementManagedDeviceAssignmentFilterEvaluationStatusDetail', 
               'New-MgBetaDeviceManagementManagedDeviceCompliancePolicyState', 
               'New-MgBetaDeviceManagementManagedDeviceConfigurationState', 
               'New-MgBetaDeviceManagementManagedDeviceEncryptionState', 
               'New-MgBetaDeviceManagementManagedDeviceHealthScriptState', 
               'New-MgBetaDeviceManagementManagedDeviceMobileAppConfigurationState', 
               'New-MgBetaDeviceManagementManagedDeviceSecurityBaselineState', 
               'New-MgBetaDeviceManagementManagedDeviceSecurityBaselineStateSettingState', 
               'New-MgBetaDeviceManagementManagedDeviceWindowsProtectionStateDetectedMalwareState', 
               'New-MgBetaDeviceManagementMicrosoftTunnelConfiguration', 
               'New-MgBetaDeviceManagementMicrosoftTunnelHealthThreshold', 
               'New-MgBetaDeviceManagementMicrosoftTunnelServerLogCollectionResponse', 
               'New-MgBetaDeviceManagementMicrosoftTunnelSite', 
               'New-MgBetaDeviceManagementMicrosoftTunnelSiteMicrosoftTunnelServer', 
               'New-MgBetaDeviceManagementMobileAppTroubleshootingEvent', 
               'New-MgBetaDeviceManagementMobileAppTroubleshootingEventAppLogCollectionRequest', 
               'New-MgBetaDeviceManagementMonitoringAlertRecord', 
               'New-MgBetaDeviceManagementMonitoringAlertRule', 
               'New-MgBetaDeviceManagementNotificationMessageTemplate', 
               'New-MgBetaDeviceManagementNotificationMessageTemplateLocalizedNotificationMessage', 
               'New-MgBetaDeviceManagementRemoteActionAudit', 
               'New-MgBetaDeviceManagementResourceAccessProfile', 
               'New-MgBetaDeviceManagementResourceAccessProfileAssignment', 
               'New-MgBetaDeviceManagementReusableSetting', 
               'New-MgBetaDeviceManagementScript', 
               'New-MgBetaDeviceManagementScriptAssignment', 
               'New-MgBetaDeviceManagementScriptDeviceRunState', 
               'New-MgBetaDeviceManagementScriptGroupAssignment', 
               'New-MgBetaDeviceManagementScriptUserRunState', 
               'New-MgBetaDeviceManagementScriptUserRunStateDeviceRunState', 
               'New-MgBetaDeviceManagementSettingDefinition', 
               'New-MgBetaDeviceManagementTemplate', 
               'New-MgBetaDeviceManagementTemplateCategory', 
               'New-MgBetaDeviceManagementTemplateCategoryRecommendedSetting', 
               'New-MgBetaDeviceManagementTemplateCategorySettingDefinition', 
               'New-MgBetaDeviceManagementTemplateMigratableTo', 
               'New-MgBetaDeviceManagementTemplateMigratableToCategory', 
               'New-MgBetaDeviceManagementTemplateMigratableToCategoryRecommendedSetting', 
               'New-MgBetaDeviceManagementTemplateMigratableToCategorySettingDefinition', 
               'New-MgBetaDeviceManagementTemplateMigratableToSetting', 
               'New-MgBetaDeviceManagementTemplateSetting', 
               'New-MgBetaDeviceManagementTroubleshootingEvent', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticAnomaly', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticAnomalyCorrelationGroupOverview', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticAnomalyDevice', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformance', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersion', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionDetail', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionDeviceId', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByOsversion', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticAppHealthDeviceModelPerformance', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticAppHealthDevicePerformance', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticAppHealthDevicePerformanceDetail', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticAppHealthOSVersionPerformance', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticAppHealthOverviewMetricValue', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticBaseline', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthAppImpact', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthDeviceAppImpact', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthDevicePerformance', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthDeviceRuntimeHistory', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthModelPerformance', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthOSPerformance', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticCategory', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticCategoryMetricValue', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticDeviceMetricHistory', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticDevicePerformance', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticDeviceScope', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticDeviceScore', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticDeviceStartupHistory', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticDeviceStartupProcess', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticDeviceStartupProcessPerformance', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticDeviceTimelineEvent', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticDeviceWithoutCloudIdentity', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticImpactingProcess', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticMetricHistory', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticModelScore', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticNotAutopilotReadyDevice', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticRemoteConnection', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticResourcePerformance', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticScoreHistory', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticWorkFromAnywhereMetric', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticWorkFromAnywhereMetricDevice', 
               'New-MgBetaDeviceManagementUserExperienceAnalyticWorkFromAnywhereModelPerformance', 
               'New-MgBetaDeviceManagementWindowsInformationProtectionAppLearningSummary', 
               'New-MgBetaDeviceManagementWindowsInformationProtectionNetworkLearningSummary', 
               'New-MgBetaDeviceManagementWindowsMalwareInformation', 
               'New-MgBetaDeviceManagementWindowsMalwareInformationDeviceMalwareState', 
               'New-MgBetaDeviceManagementWindowsQualityUpdateProfile', 
               'New-MgBetaDeviceManagementWindowsQualityUpdateProfileAssignment', 
               'Remove-MgBetaAdminEdge', 
               'Remove-MgBetaAdminEdgeInternetExplorerMode', 
               'Remove-MgBetaAdminEdgeInternetExplorerModeSiteList', 
               'Remove-MgBetaAdminEdgeInternetExplorerModeSiteListSharedCookie', 
               'Remove-MgBetaAdminEdgeInternetExplorerModeSiteListSite', 
               'Remove-MgBetaDeviceManagementAdvancedThreatProtectionOnboardingStateSummary', 
               'Remove-MgBetaDeviceManagementAdvancedThreatProtectionOnboardingStateSummaryAdvancedThreatProtectionOnboardingDeviceSettingState', 
               'Remove-MgBetaDeviceManagementAndroidForWorkAppConfigurationSchema', 
               'Remove-MgBetaDeviceManagementAndroidForWorkSetting', 
               'Remove-MgBetaDeviceManagementAndroidManagedStoreAccountEnterpriseSetting', 
               'Remove-MgBetaDeviceManagementAndroidManagedStoreAppConfigurationSchema', 
               'Remove-MgBetaDeviceManagementAssignmentFilter', 
               'Remove-MgBetaDeviceManagementCategory', 
               'Remove-MgBetaDeviceManagementCategorySettingDefinition', 
               'Remove-MgBetaDeviceManagementComanagedDevice', 
               'Remove-MgBetaDeviceManagementComanagedDeviceAssignmentFilterEvaluationStatusDetail', 
               'Remove-MgBetaDeviceManagementComanagedDeviceCategory', 
               'Remove-MgBetaDeviceManagementComanagedDeviceCompliancePolicyState', 
               'Remove-MgBetaDeviceManagementComanagedDeviceConfigurationState', 
               'Remove-MgBetaDeviceManagementComanagedDeviceHealthScriptState', 
               'Remove-MgBetaDeviceManagementComanagedDeviceLogCollectionRequest', 
               'Remove-MgBetaDeviceManagementComanagedDeviceManagedDeviceMobileAppConfigurationState', 
               'Remove-MgBetaDeviceManagementComanagedDeviceSecurityBaselineState', 
               'Remove-MgBetaDeviceManagementComanagedDeviceSecurityBaselineStateSettingState', 
               'Remove-MgBetaDeviceManagementComanagedDeviceWindowsProtectionState', 
               'Remove-MgBetaDeviceManagementComanagedDeviceWindowsProtectionStateDetectedMalwareState', 
               'Remove-MgBetaDeviceManagementCompliancePolicy', 
               'Remove-MgBetaDeviceManagementCompliancePolicyAssignment', 
               'Remove-MgBetaDeviceManagementCompliancePolicyScheduledActionForRule', 
               'Remove-MgBetaDeviceManagementCompliancePolicyScheduledActionForRuleScheduledActionConfiguration', 
               'Remove-MgBetaDeviceManagementCompliancePolicySetting', 
               'Remove-MgBetaDeviceManagementComplianceSetting', 
               'Remove-MgBetaDeviceManagementConfigurationPolicy', 
               'Remove-MgBetaDeviceManagementConfigurationPolicyAssignment', 
               'Remove-MgBetaDeviceManagementConfigurationPolicySetting', 
               'Remove-MgBetaDeviceManagementConfigurationPolicyTemplate', 
               'Remove-MgBetaDeviceManagementConfigurationPolicyTemplateSettingDefinition', 
               'Remove-MgBetaDeviceManagementConfigurationPolicyTemplateSettingTemplate', 
               'Remove-MgBetaDeviceManagementConfigurationSetting', 
               'Remove-MgBetaDeviceManagementDataSharingConsent', 
               'Remove-MgBetaDeviceManagementDerivedCredential', 
               'Remove-MgBetaDeviceManagementDetectedApp', 
               'Remove-MgBetaDeviceManagementDeviceCategory', 
               'Remove-MgBetaDeviceManagementDeviceCompliancePolicy', 
               'Remove-MgBetaDeviceManagementDeviceCompliancePolicyAssignment', 
               'Remove-MgBetaDeviceManagementDeviceCompliancePolicyDeviceSettingStateSummary', 
               'Remove-MgBetaDeviceManagementDeviceCompliancePolicyDeviceStateSummary', 
               'Remove-MgBetaDeviceManagementDeviceCompliancePolicyDeviceStatus', 
               'Remove-MgBetaDeviceManagementDeviceCompliancePolicyDeviceStatusOverview', 
               'Remove-MgBetaDeviceManagementDeviceCompliancePolicyScheduledActionForRule', 
               'Remove-MgBetaDeviceManagementDeviceCompliancePolicyScheduledActionForRuleScheduledActionConfiguration', 
               'Remove-MgBetaDeviceManagementDeviceCompliancePolicySettingStateSummary', 
               'Remove-MgBetaDeviceManagementDeviceCompliancePolicySettingStateSummaryDeviceComplianceSettingState', 
               'Remove-MgBetaDeviceManagementDeviceCompliancePolicyUserStatus', 
               'Remove-MgBetaDeviceManagementDeviceCompliancePolicyUserStatusOverview', 
               'Remove-MgBetaDeviceManagementDeviceConfiguration', 
               'Remove-MgBetaDeviceManagementDeviceConfigurationAssignment', 
               'Remove-MgBetaDeviceManagementDeviceConfigurationConflictSummary', 
               'Remove-MgBetaDeviceManagementDeviceConfigurationDeviceSettingStateSummary', 
               'Remove-MgBetaDeviceManagementDeviceConfigurationDeviceStateSummary', 
               'Remove-MgBetaDeviceManagementDeviceConfigurationDeviceStatus', 
               'Remove-MgBetaDeviceManagementDeviceConfigurationDeviceStatusOverview', 
               'Remove-MgBetaDeviceManagementDeviceConfigurationGroupAssignment', 
               'Remove-MgBetaDeviceManagementDeviceConfigurationUserStateSummary', 
               'Remove-MgBetaDeviceManagementDeviceConfigurationUserStatus', 
               'Remove-MgBetaDeviceManagementDeviceConfigurationUserStatusOverview', 
               'Remove-MgBetaDeviceManagementDeviceHealthScript', 
               'Remove-MgBetaDeviceManagementDeviceHealthScriptAssignment', 
               'Remove-MgBetaDeviceManagementDeviceHealthScriptDeviceRunState', 
               'Remove-MgBetaDeviceManagementDeviceHealthScriptRunSummary', 
               'Remove-MgBetaDeviceManagementDeviceShellScript', 
               'Remove-MgBetaDeviceManagementDeviceShellScriptAssignment', 
               'Remove-MgBetaDeviceManagementDeviceShellScriptDeviceRunState', 
               'Remove-MgBetaDeviceManagementDeviceShellScriptGroupAssignment', 
               'Remove-MgBetaDeviceManagementDeviceShellScriptUserRunState', 
               'Remove-MgBetaDeviceManagementDeviceShellScriptUserRunStateDeviceRunState', 
               'Remove-MgBetaDeviceManagementEmbeddedSimActivationCodePool', 
               'Remove-MgBetaDeviceManagementEmbeddedSimActivationCodePoolAssignment', 
               'Remove-MgBetaDeviceManagementEmbeddedSimActivationCodePoolDeviceState', 
               'Remove-MgBetaDeviceManagementGroupPolicyConfiguration', 
               'Remove-MgBetaDeviceManagementGroupPolicyConfigurationAssignment', 
               'Remove-MgBetaDeviceManagementGroupPolicyConfigurationDefinitionValue', 
               'Remove-MgBetaDeviceManagementGroupPolicyConfigurationDefinitionValuePresentationValue', 
               'Remove-MgBetaDeviceManagementIntent', 
               'Remove-MgBetaDeviceManagementIntentAssignment', 
               'Remove-MgBetaDeviceManagementIntentCategory', 
               'Remove-MgBetaDeviceManagementIntentCategorySetting', 
               'Remove-MgBetaDeviceManagementIntentCategorySettingDefinition', 
               'Remove-MgBetaDeviceManagementIntentDeviceSettingStateSummary', 
               'Remove-MgBetaDeviceManagementIntentDeviceState', 
               'Remove-MgBetaDeviceManagementIntentDeviceStateSummary', 
               'Remove-MgBetaDeviceManagementIntentSetting', 
               'Remove-MgBetaDeviceManagementIntentUserState', 
               'Remove-MgBetaDeviceManagementIntentUserStateSummary', 
               'Remove-MgBetaDeviceManagementMacOSSoftwareUpdateAccountSummary', 
               'Remove-MgBetaDeviceManagementMacOSSoftwareUpdateAccountSummaryCategorySummary', 
               'Remove-MgBetaDeviceManagementMacOSSoftwareUpdateAccountSummaryCategorySummaryUpdateStateSummary', 
               'Remove-MgBetaDeviceManagementManagedDevice', 
               'Remove-MgBetaDeviceManagementManagedDeviceAssignmentFilterEvaluationStatusDetail', 
               'Remove-MgBetaDeviceManagementManagedDeviceCategory', 
               'Remove-MgBetaDeviceManagementManagedDeviceCompliancePolicyState', 
               'Remove-MgBetaDeviceManagementManagedDeviceConfigurationState', 
               'Remove-MgBetaDeviceManagementManagedDeviceEncryptionState', 
               'Remove-MgBetaDeviceManagementManagedDeviceHealthScriptState', 
               'Remove-MgBetaDeviceManagementManagedDeviceLogCollectionRequest', 
               'Remove-MgBetaDeviceManagementManagedDeviceMobileAppConfigurationState', 
               'Remove-MgBetaDeviceManagementManagedDeviceSecurityBaselineState', 
               'Remove-MgBetaDeviceManagementManagedDeviceSecurityBaselineStateSettingState', 
               'Remove-MgBetaDeviceManagementManagedDeviceWindowsProtectionState', 
               'Remove-MgBetaDeviceManagementManagedDeviceWindowsProtectionStateDetectedMalwareState', 
               'Remove-MgBetaDeviceManagementMicrosoftTunnelConfiguration', 
               'Remove-MgBetaDeviceManagementMicrosoftTunnelHealthThreshold', 
               'Remove-MgBetaDeviceManagementMicrosoftTunnelServerLogCollectionResponse', 
               'Remove-MgBetaDeviceManagementMicrosoftTunnelSite', 
               'Remove-MgBetaDeviceManagementMicrosoftTunnelSiteMicrosoftTunnelConfiguration', 
               'Remove-MgBetaDeviceManagementMicrosoftTunnelSiteMicrosoftTunnelServer', 
               'Remove-MgBetaDeviceManagementMobileAppTroubleshootingEvent', 
               'Remove-MgBetaDeviceManagementMobileAppTroubleshootingEventAppLogCollectionRequest', 
               'Remove-MgBetaDeviceManagementMonitoring', 
               'Remove-MgBetaDeviceManagementMonitoringAlertRecord', 
               'Remove-MgBetaDeviceManagementMonitoringAlertRule', 
               'Remove-MgBetaDeviceManagementNotificationMessageTemplate', 
               'Remove-MgBetaDeviceManagementNotificationMessageTemplateLocalizedNotificationMessage', 
               'Remove-MgBetaDeviceManagementRemoteActionAudit', 
               'Remove-MgBetaDeviceManagementResourceAccessProfile', 
               'Remove-MgBetaDeviceManagementResourceAccessProfileAssignment', 
               'Remove-MgBetaDeviceManagementReusableSetting', 
               'Remove-MgBetaDeviceManagementScript', 
               'Remove-MgBetaDeviceManagementScriptAssignment', 
               'Remove-MgBetaDeviceManagementScriptDeviceRunState', 
               'Remove-MgBetaDeviceManagementScriptGroupAssignment', 
               'Remove-MgBetaDeviceManagementScriptUserRunState', 
               'Remove-MgBetaDeviceManagementScriptUserRunStateDeviceRunState', 
               'Remove-MgBetaDeviceManagementSettingDefinition', 
               'Remove-MgBetaDeviceManagementTemplate', 
               'Remove-MgBetaDeviceManagementTemplateCategory', 
               'Remove-MgBetaDeviceManagementTemplateCategoryRecommendedSetting', 
               'Remove-MgBetaDeviceManagementTemplateCategorySettingDefinition', 
               'Remove-MgBetaDeviceManagementTemplateMigratableTo', 
               'Remove-MgBetaDeviceManagementTemplateMigratableToCategory', 
               'Remove-MgBetaDeviceManagementTemplateMigratableToCategoryRecommendedSetting', 
               'Remove-MgBetaDeviceManagementTemplateMigratableToCategorySettingDefinition', 
               'Remove-MgBetaDeviceManagementTemplateMigratableToSetting', 
               'Remove-MgBetaDeviceManagementTemplateSetting', 
               'Remove-MgBetaDeviceManagementTroubleshootingEvent', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticAnomaly', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticAnomalyCorrelationGroupOverview', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticAnomalyDevice', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformance', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersion', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionDetail', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionDeviceId', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByOsversion', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticAppHealthDeviceModelPerformance', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticAppHealthDevicePerformance', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticAppHealthDevicePerformanceDetail', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticAppHealthOSVersionPerformance', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticAppHealthOverview', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticAppHealthOverviewMetricValue', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticBaseline', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthAppImpact', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthCapacityDetail', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthDeviceAppImpact', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthDevicePerformance', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthDeviceRuntimeHistory', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthModelPerformance', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthOSPerformance', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthRuntimeDetail', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticCategory', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticCategoryMetricValue', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticDeviceMetricHistory', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticDevicePerformance', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticDeviceScope', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticDeviceScore', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticDeviceStartupHistory', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticDeviceStartupProcess', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticDeviceStartupProcessPerformance', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticDeviceTimelineEvent', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticDeviceWithoutCloudIdentity', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticImpactingProcess', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticMetricHistory', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticModelScore', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticNotAutopilotReadyDevice', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticOverview', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticRemoteConnection', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticResourcePerformance', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticScoreHistory', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticWorkFromAnywhereHardwareReadinessMetric', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticWorkFromAnywhereMetric', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticWorkFromAnywhereMetricDevice', 
               'Remove-MgBetaDeviceManagementUserExperienceAnalyticWorkFromAnywhereModelPerformance', 
               'Remove-MgBetaDeviceManagementWindowsInformationProtectionAppLearningSummary', 
               'Remove-MgBetaDeviceManagementWindowsInformationProtectionNetworkLearningSummary', 
               'Remove-MgBetaDeviceManagementWindowsMalwareInformation', 
               'Remove-MgBetaDeviceManagementWindowsMalwareInformationDeviceMalwareState', 
               'Remove-MgBetaDeviceManagementWindowsQualityUpdateProfile', 
               'Remove-MgBetaDeviceManagementWindowsQualityUpdateProfileAssignment', 
               'Update-MgBetaAdminEdge', 
               'Update-MgBetaAdminEdgeInternetExplorerMode', 
               'Update-MgBetaAdminEdgeInternetExplorerModeSiteList', 
               'Update-MgBetaAdminEdgeInternetExplorerModeSiteListSharedCookie', 
               'Update-MgBetaAdminEdgeInternetExplorerModeSiteListSite', 
               'Update-MgBetaDeviceManagement', 
               'Update-MgBetaDeviceManagementAdvancedThreatProtectionOnboardingStateSummary', 
               'Update-MgBetaDeviceManagementAdvancedThreatProtectionOnboardingStateSummaryAdvancedThreatProtectionOnboardingDeviceSettingState', 
               'Update-MgBetaDeviceManagementAndroidForWorkAppConfigurationSchema', 
               'Update-MgBetaDeviceManagementAndroidForWorkSetting', 
               'Update-MgBetaDeviceManagementAndroidManagedStoreAccountEnterpriseSetting', 
               'Update-MgBetaDeviceManagementAndroidManagedStoreAppConfigurationSchema', 
               'Update-MgBetaDeviceManagementAssignmentFilter', 
               'Update-MgBetaDeviceManagementCategory', 
               'Update-MgBetaDeviceManagementCategorySettingDefinition', 
               'Update-MgBetaDeviceManagementComanagedDeviceAssignmentFilterEvaluationStatusDetail', 
               'Update-MgBetaDeviceManagementComanagedDeviceCategory', 
               'Update-MgBetaDeviceManagementComanagedDeviceCompliancePolicyState', 
               'Update-MgBetaDeviceManagementComanagedDeviceConfigurationState', 
               'Update-MgBetaDeviceManagementComanagedDeviceHealthScriptState', 
               'Update-MgBetaDeviceManagementComanagedDeviceLogCollectionRequest', 
               'Update-MgBetaDeviceManagementComanagedDeviceManagedDeviceMobileAppConfigurationState', 
               'Update-MgBetaDeviceManagementComanagedDeviceSecurityBaselineState', 
               'Update-MgBetaDeviceManagementComanagedDeviceSecurityBaselineStateSettingState', 
               'Update-MgBetaDeviceManagementComanagedDeviceWindowsProtectionState', 
               'Update-MgBetaDeviceManagementComanagedDeviceWindowsProtectionStateDetectedMalwareState', 
               'Update-MgBetaDeviceManagementCompliancePolicy', 
               'Update-MgBetaDeviceManagementCompliancePolicyAssignment', 
               'Update-MgBetaDeviceManagementCompliancePolicyScheduledActionForRule', 
               'Update-MgBetaDeviceManagementCompliancePolicyScheduledActionForRuleScheduledActionConfiguration', 
               'Update-MgBetaDeviceManagementCompliancePolicySetting', 
               'Update-MgBetaDeviceManagementComplianceSetting', 
               'Update-MgBetaDeviceManagementConfigurationPolicy', 
               'Update-MgBetaDeviceManagementConfigurationPolicyAssignment', 
               'Update-MgBetaDeviceManagementConfigurationPolicySetting', 
               'Update-MgBetaDeviceManagementConfigurationPolicyTemplate', 
               'Update-MgBetaDeviceManagementConfigurationPolicyTemplateSettingDefinition', 
               'Update-MgBetaDeviceManagementConfigurationPolicyTemplateSettingTemplate', 
               'Update-MgBetaDeviceManagementConfigurationSetting', 
               'Update-MgBetaDeviceManagementDataSharingConsent', 
               'Update-MgBetaDeviceManagementDerivedCredential', 
               'Update-MgBetaDeviceManagementDetectedApp', 
               'Update-MgBetaDeviceManagementDeviceCategory', 
               'Update-MgBetaDeviceManagementDeviceCompliancePolicy', 
               'Update-MgBetaDeviceManagementDeviceCompliancePolicyAssignment', 
               'Update-MgBetaDeviceManagementDeviceCompliancePolicyDeviceSettingStateSummary', 
               'Update-MgBetaDeviceManagementDeviceCompliancePolicyDeviceStateSummary', 
               'Update-MgBetaDeviceManagementDeviceCompliancePolicyDeviceStatus', 
               'Update-MgBetaDeviceManagementDeviceCompliancePolicyDeviceStatusOverview', 
               'Update-MgBetaDeviceManagementDeviceCompliancePolicyScheduledActionForRule', 
               'Update-MgBetaDeviceManagementDeviceCompliancePolicyScheduledActionForRuleScheduledActionConfiguration', 
               'Update-MgBetaDeviceManagementDeviceCompliancePolicySettingStateSummary', 
               'Update-MgBetaDeviceManagementDeviceCompliancePolicySettingStateSummaryDeviceComplianceSettingState', 
               'Update-MgBetaDeviceManagementDeviceCompliancePolicyUserStatus', 
               'Update-MgBetaDeviceManagementDeviceCompliancePolicyUserStatusOverview', 
               'Update-MgBetaDeviceManagementDeviceConfiguration', 
               'Update-MgBetaDeviceManagementDeviceConfigurationAssignment', 
               'Update-MgBetaDeviceManagementDeviceConfigurationConflictSummary', 
               'Update-MgBetaDeviceManagementDeviceConfigurationDeviceSettingStateSummary', 
               'Update-MgBetaDeviceManagementDeviceConfigurationDeviceStateSummary', 
               'Update-MgBetaDeviceManagementDeviceConfigurationDeviceStatus', 
               'Update-MgBetaDeviceManagementDeviceConfigurationDeviceStatusOverview', 
               'Update-MgBetaDeviceManagementDeviceConfigurationGroupAssignment', 
               'Update-MgBetaDeviceManagementDeviceConfigurationUserStateSummary', 
               'Update-MgBetaDeviceManagementDeviceConfigurationUserStatus', 
               'Update-MgBetaDeviceManagementDeviceConfigurationUserStatusOverview', 
               'Update-MgBetaDeviceManagementDeviceHealthScript', 
               'Update-MgBetaDeviceManagementDeviceHealthScriptAssignment', 
               'Update-MgBetaDeviceManagementDeviceHealthScriptDeviceRunState', 
               'Update-MgBetaDeviceManagementDeviceHealthScriptRunSummary', 
               'Update-MgBetaDeviceManagementDeviceShellScript', 
               'Update-MgBetaDeviceManagementDeviceShellScriptAssignment', 
               'Update-MgBetaDeviceManagementDeviceShellScriptDeviceRunState', 
               'Update-MgBetaDeviceManagementDeviceShellScriptGroupAssignment', 
               'Update-MgBetaDeviceManagementDeviceShellScriptUserRunState', 
               'Update-MgBetaDeviceManagementDeviceShellScriptUserRunStateDeviceRunState', 
               'Update-MgBetaDeviceManagementEmbeddedSimActivationCodePool', 
               'Update-MgBetaDeviceManagementEmbeddedSimActivationCodePoolAssignment', 
               'Update-MgBetaDeviceManagementEmbeddedSimActivationCodePoolDeviceState', 
               'Update-MgBetaDeviceManagementGroupPolicyConfiguration', 
               'Update-MgBetaDeviceManagementGroupPolicyConfigurationAssignment', 
               'Update-MgBetaDeviceManagementGroupPolicyConfigurationDefinitionValue', 
               'Update-MgBetaDeviceManagementGroupPolicyConfigurationDefinitionValuePresentationValue', 
               'Update-MgBetaDeviceManagementIntent', 
               'Update-MgBetaDeviceManagementIntentAssignment', 
               'Update-MgBetaDeviceManagementIntentCategory', 
               'Update-MgBetaDeviceManagementIntentCategorySetting', 
               'Update-MgBetaDeviceManagementIntentCategorySettingDefinition', 
               'Update-MgBetaDeviceManagementIntentDeviceSettingStateSummary', 
               'Update-MgBetaDeviceManagementIntentDeviceState', 
               'Update-MgBetaDeviceManagementIntentDeviceStateSummary', 
               'Update-MgBetaDeviceManagementIntentSetting', 
               'Update-MgBetaDeviceManagementIntentUserState', 
               'Update-MgBetaDeviceManagementIntentUserStateSummary', 
               'Update-MgBetaDeviceManagementMacOSSoftwareUpdateAccountSummary', 
               'Update-MgBetaDeviceManagementMacOSSoftwareUpdateAccountSummaryCategorySummary', 
               'Update-MgBetaDeviceManagementMacOSSoftwareUpdateAccountSummaryCategorySummaryStateSummary', 
               'Update-MgBetaDeviceManagementManagedDevice', 
               'Update-MgBetaDeviceManagementManagedDeviceAssignmentFilterEvaluationStatusDetail', 
               'Update-MgBetaDeviceManagementManagedDeviceCategory', 
               'Update-MgBetaDeviceManagementManagedDeviceCompliancePolicyState', 
               'Update-MgBetaDeviceManagementManagedDeviceConfigurationState', 
               'Update-MgBetaDeviceManagementManagedDeviceEncryptionState', 
               'Update-MgBetaDeviceManagementManagedDeviceHealthScriptState', 
               'Update-MgBetaDeviceManagementManagedDeviceLogCollectionRequest', 
               'Update-MgBetaDeviceManagementManagedDeviceMobileAppConfigurationState', 
               'Update-MgBetaDeviceManagementManagedDeviceSecurityBaselineState', 
               'Update-MgBetaDeviceManagementManagedDeviceSecurityBaselineStateSettingState', 
               'Update-MgBetaDeviceManagementManagedDeviceWindowsProtectionState', 
               'Update-MgBetaDeviceManagementManagedDeviceWindowsProtectionStateDetectedMalwareState', 
               'Update-MgBetaDeviceManagementMicrosoftTunnelConfiguration', 
               'Update-MgBetaDeviceManagementMicrosoftTunnelHealthThreshold', 
               'Update-MgBetaDeviceManagementMicrosoftTunnelServerLogCollectionResponse', 
               'Update-MgBetaDeviceManagementMicrosoftTunnelSite', 
               'Update-MgBetaDeviceManagementMicrosoftTunnelSiteMicrosoftTunnelConfiguration', 
               'Update-MgBetaDeviceManagementMicrosoftTunnelSiteMicrosoftTunnelServer', 
               'Update-MgBetaDeviceManagementMobileAppTroubleshootingEvent', 
               'Update-MgBetaDeviceManagementMobileAppTroubleshootingEventAppLogCollectionRequest', 
               'Update-MgBetaDeviceManagementMonitoring', 
               'Update-MgBetaDeviceManagementMonitoringAlertRecord', 
               'Update-MgBetaDeviceManagementMonitoringAlertRule', 
               'Update-MgBetaDeviceManagementNotificationMessageTemplate', 
               'Update-MgBetaDeviceManagementNotificationMessageTemplateLocalizedNotificationMessage', 
               'Update-MgBetaDeviceManagementRemoteActionAudit', 
               'Update-MgBetaDeviceManagementResourceAccessProfile', 
               'Update-MgBetaDeviceManagementResourceAccessProfileAssignment', 
               'Update-MgBetaDeviceManagementReusableSetting', 
               'Update-MgBetaDeviceManagementScript', 
               'Update-MgBetaDeviceManagementScriptAssignment', 
               'Update-MgBetaDeviceManagementScriptDeviceRunState', 
               'Update-MgBetaDeviceManagementScriptGroupAssignment', 
               'Update-MgBetaDeviceManagementScriptUserRunState', 
               'Update-MgBetaDeviceManagementScriptUserRunStateDeviceRunState', 
               'Update-MgBetaDeviceManagementSettingDefinition', 
               'Update-MgBetaDeviceManagementTemplate', 
               'Update-MgBetaDeviceManagementTemplateCategory', 
               'Update-MgBetaDeviceManagementTemplateCategoryRecommendedSetting', 
               'Update-MgBetaDeviceManagementTemplateCategorySettingDefinition', 
               'Update-MgBetaDeviceManagementTemplateMigratableTo', 
               'Update-MgBetaDeviceManagementTemplateMigratableToCategory', 
               'Update-MgBetaDeviceManagementTemplateMigratableToCategoryRecommendedSetting', 
               'Update-MgBetaDeviceManagementTemplateMigratableToCategorySettingDefinition', 
               'Update-MgBetaDeviceManagementTemplateMigratableToSetting', 
               'Update-MgBetaDeviceManagementTemplateSetting', 
               'Update-MgBetaDeviceManagementTroubleshootingEvent', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticAnomaly', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticAnomalyCorrelationGroupOverview', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticAnomalyDevice', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformance', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersion', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionDetail', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByAppVersionDeviceId', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticAppHealthApplicationPerformanceByOsversion', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticAppHealthDeviceModelPerformance', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticAppHealthDevicePerformance', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticAppHealthDevicePerformanceDetail', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticAppHealthOSVersionPerformance', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticAppHealthOverview', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticAppHealthOverviewMetricValue', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticBaseline', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthAppImpact', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthCapacityDetail', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthDeviceAppImpact', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthDevicePerformance', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthDeviceRuntimeHistory', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthModelPerformance', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthOSPerformance', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticBatteryHealthRuntimeDetail', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticCategory', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticCategoryMetricValue', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticDeviceMetricHistory', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticDevicePerformance', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticDeviceScope', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticDeviceScore', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticDeviceStartupHistory', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticDeviceStartupProcess', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticDeviceStartupProcessPerformance', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticDeviceTimelineEvent', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticDeviceWithoutCloudIdentity', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticImpactingProcess', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticMetricHistory', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticModelScore', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticNotAutopilotReadyDevice', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticOverview', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticRemoteConnection', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticResourcePerformance', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticScoreHistory', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticWorkFromAnywhereHardwareReadinessMetric', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticWorkFromAnywhereMetric', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticWorkFromAnywhereMetricDevice', 
               'Update-MgBetaDeviceManagementUserExperienceAnalyticWorkFromAnywhereModelPerformance', 
               'Update-MgBetaDeviceManagementWindowsInformationProtectionAppLearningSummary', 
               'Update-MgBetaDeviceManagementWindowsInformationProtectionNetworkLearningSummary', 
               'Update-MgBetaDeviceManagementWindowsMalwareInformation', 
               'Update-MgBetaDeviceManagementWindowsMalwareInformationDeviceMalwareState', 
               'Update-MgBetaDeviceManagementWindowsQualityUpdateProfile', 
               'Update-MgBetaDeviceManagementWindowsQualityUpdateProfileAssignment'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/dev/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIInzgYJKoZIhvcNAQcCoIInvzCCJ7sCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCBQQRcCnws9LiLO
# cnGQ/Q6j+u8ke/JAW85kNHANWSpYxKCCDYUwggYDMIID66ADAgECAhMzAAADri01
# UchTj1UdAAAAAAOuMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjMxMTE2MTkwODU5WhcNMjQxMTE0MTkwODU5WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQD0IPymNjfDEKg+YyE6SjDvJwKW1+pieqTjAY0CnOHZ1Nj5irGjNZPMlQ4HfxXG
# yAVCZcEWE4x2sZgam872R1s0+TAelOtbqFmoW4suJHAYoTHhkznNVKpscm5fZ899
# QnReZv5WtWwbD8HAFXbPPStW2JKCqPcZ54Y6wbuWV9bKtKPImqbkMcTejTgEAj82
# 6GQc6/Th66Koka8cUIvz59e/IP04DGrh9wkq2jIFvQ8EDegw1B4KyJTIs76+hmpV
# M5SwBZjRs3liOQrierkNVo11WuujB3kBf2CbPoP9MlOyyezqkMIbTRj4OHeKlamd
# WaSFhwHLJRIQpfc8sLwOSIBBAgMBAAGjggGCMIIBfjAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQUhx/vdKmXhwc4WiWXbsf0I53h8T8w
# VAYDVR0RBE0wS6RJMEcxLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJh
# dGlvbnMgTGltaXRlZDEWMBQGA1UEBRMNMjMwMDEyKzUwMTgzNjAfBgNVHSMEGDAW
# gBRIbmTlUAXTgqoXNzcitW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8v
# d3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIw
# MTEtMDctMDguY3JsMGEGCCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDov
# L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDEx
# XzIwMTEtMDctMDguY3J0MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIB
# AGrJYDUS7s8o0yNprGXRXuAnRcHKxSjFmW4wclcUTYsQZkhnbMwthWM6cAYb/h2W
# 5GNKtlmj/y/CThe3y/o0EH2h+jwfU/9eJ0fK1ZO/2WD0xi777qU+a7l8KjMPdwjY
# 0tk9bYEGEZfYPRHy1AGPQVuZlG4i5ymJDsMrcIcqV8pxzsw/yk/O4y/nlOjHz4oV
# APU0br5t9tgD8E08GSDi3I6H57Ftod9w26h0MlQiOr10Xqhr5iPLS7SlQwj8HW37
# ybqsmjQpKhmWul6xiXSNGGm36GarHy4Q1egYlxhlUnk3ZKSr3QtWIo1GGL03hT57
# xzjL25fKiZQX/q+II8nuG5M0Qmjvl6Egltr4hZ3e3FQRzRHfLoNPq3ELpxbWdH8t
# Nuj0j/x9Crnfwbki8n57mJKI5JVWRWTSLmbTcDDLkTZlJLg9V1BIJwXGY3i2kR9i
# 5HsADL8YlW0gMWVSlKB1eiSlK6LmFi0rVH16dde+j5T/EaQtFz6qngN7d1lvO7uk
# 6rtX+MLKG4LDRsQgBTi6sIYiKntMjoYFHMPvI/OMUip5ljtLitVbkFGfagSqmbxK
# 7rJMhC8wiTzHanBg1Rrbff1niBbnFbbV4UDmYumjs1FIpFCazk6AADXxoKCo5TsO
# zSHqr9gHgGYQC2hMyX9MGLIpowYCURx3L7kUiGbOiMwaMIIHejCCBWKgAwIBAgIK
# YQ6Q0gAAAAAAAzANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNV
# BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
# c29mdCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlm
# aWNhdGUgQXV0aG9yaXR5IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEw
# OTA5WjB+MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYD
# VQQDEx9NaWNyb3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG
# 9w0BAQEFAAOCAg8AMIICCgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+la
# UKq4BjgaBEm6f8MMHt03a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc
# 6Whe0t+bU7IKLMOv2akrrnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4D
# dato88tt8zpcoRb0RrrgOGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+
# lD3v++MrWhAfTVYoonpy4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nk
# kDstrjNYxbc+/jLTswM9sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6
# A4aN91/w0FK/jJSHvMAhdCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmd
# X4jiJV3TIUs+UsS1Vz8kA/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL
# 5zmhD+kjSbwYuER8ReTBw3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zd
# sGbiwZeBe+3W7UvnSSmnEyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3
# T8HhhUSJxAlMxdSlQy90lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS
# 4NaIjAsCAwEAAaOCAe0wggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRI
# bmTlUAXTgqoXNzcitW2oynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTAL
# BgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBD
# uRQFTuHqp8cx0SOJNDBaBgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jv
# c29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFf
# MDNfMjIuY3JsMF4GCCsGAQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFf
# MDNfMjIuY3J0MIGfBgNVHSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEF
# BQcCARYzaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1h
# cnljcHMuaHRtMEAGCCsGAQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkA
# YwB5AF8AcwB0AGEAdABlAG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn
# 8oalmOBUeRou09h0ZyKbC5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7
# v0epo/Np22O/IjWll11lhJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0b
# pdS1HXeUOeLpZMlEPXh6I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/
# KmtYSWMfCWluWpiW5IP0wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvy
# CInWH8MyGOLwxS3OW560STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBp
# mLJZiWhub6e3dMNABQamASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJi
# hsMdYzaXht/a8/jyFqGaJ+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYb
# BL7fQccOKO7eZS/sl/ahXJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbS
# oqKfenoi+kiVH6v7RyOA9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sL
# gOppO6/8MO0ETI7f33VtY5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtX
# cVZOSEXAQsmbdlsKgEhr/Xmfwb1tbWrJUnMTDXpQzTGCGZ8wghmbAgEBMIGVMH4x
# CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
# b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01p
# Y3Jvc29mdCBDb2RlIFNpZ25pbmcgUENBIDIwMTECEzMAAAOuLTVRyFOPVR0AAAAA
# A64wDQYJYIZIAWUDBAIBBQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQw
# HAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIGUL
# W74Cm/6kTZVws4wPd19EBeblkMt5GnsKikOEL36jMEIGCisGAQQBgjcCAQwxNDAy
# oBSAEgBNAGkAYwByAG8AcwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20wDQYJKoZIhvcNAQEBBQAEggEAJy2hHm1ygU8UC8hp4wSzaFVu+701cKx0URbT
# IX8lTVn4os8uvl4sehbITGQdPF4Kw8QWOMgv1AO4I4PzKx8VYfRnSVqXnTWDqiWe
# s9eBspJFlJiw70a1Y6oxKj1wkDmWUk4LmzATgjBweEy7vbkBii06oLSLcbxTwgi1
# MP2wFp5tQM+36jBdZEOThySJn4Vms8AIwJ59nu76atnQnQqVn6s5KV25VlRwNbpU
# 4AMJLqYy+LPBdMRytbuAPp3A940KjXPqPltJ9CApEVNZIGTolOYBXKdsntPMzFth
# lMciFephjwCXI0FG2Zxi2mFdGEnjZQsDwTTJC3iPfytihZQFgqGCFykwghclBgor
# BgEEAYI3AwMBMYIXFTCCFxEGCSqGSIb3DQEHAqCCFwIwghb+AgEDMQ8wDQYJYIZI
# AWUDBAIBBQAwggFZBgsqhkiG9w0BCRABBKCCAUgEggFEMIIBQAIBAQYKKwYBBAGE
# WQoDATAxMA0GCWCGSAFlAwQCAQUABCCZdP2CJAcoKTwJ0ILasnLasFHPAxyd1iB3
# NQ0EiIJgYgIGZYLWLGW9GBMyMDI0MDExNjAwMzIxMS43MDFaMASAAgH0oIHYpIHV
# MIHSMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQL
# EyRNaWNyb3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJjAkBgNVBAsT
# HVRoYWxlcyBUU1MgRVNOOjJBRDQtNEI5Mi1GQTAxMSUwIwYDVQQDExxNaWNyb3Nv
# ZnQgVGltZS1TdGFtcCBTZXJ2aWNloIIReDCCBycwggUPoAMCAQICEzMAAAHenkie
# lp8oRD0AAQAAAd4wDQYJKoZIhvcNAQELBQAwfDELMAkGA1UEBhMCVVMxEzARBgNV
# BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
# c29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAg
# UENBIDIwMTAwHhcNMjMxMDEyMTkwNzEyWhcNMjUwMTEwMTkwNzEyWjCB0jELMAkG
# A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQx
# HjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWljcm9z
# b2Z0IElyZWxhbmQgT3BlcmF0aW9ucyBMaW1pdGVkMSYwJAYDVQQLEx1UaGFsZXMg
# VFNTIEVTTjoyQUQ0LTRCOTItRkEwMTElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUt
# U3RhbXAgU2VydmljZTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALSB
# 9ByF9UIDhA6xFrOniw/xsDl8sSi9rOCOXSSO4VMQjnNGAo5VHx0iijMEMH9LY2SU
# IBkVQS0Ml6kR+TagkUPbaEpwjhQ1mprhRgJT/jlSnic42VDAo0en4JI6xnXoAoWo
# KySY8/ROIKdpphgI7OJb4XHk1P3sX2pNZ32LDY1ktchK1/hWyPlblaXAHRu0E3yn
# vwrS8/bcorANO6DjuysyS9zUmr+w3H3AEvSgs2ReuLj2pkBcfW1UPCFudLd7IPZ2
# RC4odQcEPnY12jypYPnS6yZAs0pLpq0KRFUyB1x6x6OU73sudiHON16mE0l6LLT9
# OmGo0S94Bxg3N/3aE6fUbnVoemVc7FkFLum8KkZcbQ7cOHSAWGJxdCvo5OtUtRdS
# qf85FklCXIIkg4sm7nM9TktUVfO0kp6kx7mysgD0Qrxx6/5oaqnwOTWLNzK+BCi1
# G7nUD1pteuXvQp8fE1KpTjnG/1OJeehwKNNPjGt98V0BmogZTe3SxBkOeOQyLA++
# 5Hyg/L68pe+DrZoZPXJaGU/iBiFmL+ul/Oi3d83zLAHlHQmH/VGNBfRwP+ixvqhy
# k/EebwuXVJY+rTyfbRfuh9n0AaMhhNxxg6tGKyZS4EAEiDxrF9mAZEy8e8rf6dlK
# IX5d3aQLo9fDda1ZTOw+XAcAvj2/N3DLVGZlHnHlAgMBAAGjggFJMIIBRTAdBgNV
# HQ4EFgQUazAmbxseaapgdxzK8Os+naPQEsgwHwYDVR0jBBgwFoAUn6cVXQBeYl2D
# 9OXSZacbUzUZ6XIwXwYDVR0fBFgwVjBUoFKgUIZOaHR0cDovL3d3dy5taWNyb3Nv
# ZnQuY29tL3BraW9wcy9jcmwvTWljcm9zb2Z0JTIwVGltZS1TdGFtcCUyMFBDQSUy
# MDIwMTAoMSkuY3JsMGwGCCsGAQUFBwEBBGAwXjBcBggrBgEFBQcwAoZQaHR0cDov
# L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jZXJ0cy9NaWNyb3NvZnQlMjBUaW1l
# LVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcnQwDAYDVR0TAQH/BAIwADAWBgNVHSUB
# Af8EDDAKBggrBgEFBQcDCDAOBgNVHQ8BAf8EBAMCB4AwDQYJKoZIhvcNAQELBQAD
# ggIBAOKUwHsXDacGOvUIgs5HDgPs0LZ1qyHS6C6wfKlLaD36tZfbWt1x+GMiazSu
# y+GsxiVHzkhMW+FqK8gruLQWN/sOCX+fGUgT9LT21cRIpcZj4/ZFIvwtkBcsCz1X
# EUsXYOSJUPitY7E8bbldmmhYZ29p+XQpIcsG/q+YjkqBW9mw0ru1MfxMTQs9MTDi
# D28gAVGrPA3NykiSChvdqS7VX+/LcEz9Ubzto/w28WA8HOCHqBTbDRHmiP7MIj+S
# QmI9VIayYsIGRjvelmNa0OvbU9CJSz/NfMEgf2NHMZUYW8KqWEjIjPfHIKxWlNMY
# huWfWRSHZCKyIANA0aJL4soHQtzzZ2MnNfjYY851wHYjGgwUj/hlLRgQO5S30Zx7
# 8GqBKfylp25aOWJ/qPhC+DXM2gXajIXbl+jpGcVANwtFFujCJRdZbeH1R+Q41Fjg
# Bg4m3OTFDGot5DSuVkQgjku7pOVPtldE46QlDg/2WhPpTQxXH64sP1GfkAwUtt6r
# rZM/PCwRG6girYmnTRLLsicBhoYLh+EEFjVviXAGTk6pnu8jx/4WPWu0jsz7yFzg
# 82/FMqCk9wK3LvyLAyDHN+FxbHAxtgwad7oLQPM0WGERdB1umPCIiYsSf/j79EqH
# doNwQYROVm+ZX10RX3n6bRmAnskeNhi0wnVaeVogLMdGD+nqMIIHcTCCBVmgAwIB
# AgITMwAAABXF52ueAptJmQAAAAAAFTANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UE
# BhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
# BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0
# IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IDIwMTAwHhcNMjEwOTMwMTgyMjI1
# WhcNMzAwOTMwMTgzMjI1WjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
# Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
# cmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDCC
# AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAOThpkzntHIhC3miy9ckeb0O
# 1YLT/e6cBwfSqWxOdcjKNVf2AX9sSuDivbk+F2Az/1xPx2b3lVNxWuJ+Slr+uDZn
# hUYjDLWNE893MsAQGOhgfWpSg0S3po5GawcU88V29YZQ3MFEyHFcUTE3oAo4bo3t
# 1w/YJlN8OWECesSq/XJprx2rrPY2vjUmZNqYO7oaezOtgFt+jBAcnVL+tuhiJdxq
# D89d9P6OU8/W7IVWTe/dvI2k45GPsjksUZzpcGkNyjYtcI4xyDUoveO0hyTD4MmP
# frVUj9z6BVWYbWg7mka97aSueik3rMvrg0XnRm7KMtXAhjBcTyziYrLNueKNiOSW
# rAFKu75xqRdbZ2De+JKRHh09/SDPc31BmkZ1zcRfNN0Sidb9pSB9fvzZnkXftnIv
# 231fgLrbqn427DZM9ituqBJR6L8FA6PRc6ZNN3SUHDSCD/AQ8rdHGO2n6Jl8P0zb
# r17C89XYcz1DTsEzOUyOArxCaC4Q6oRRRuLRvWoYWmEBc8pnol7XKHYC4jMYcten
# IPDC+hIK12NvDMk2ZItboKaDIV1fMHSRlJTYuVD5C4lh8zYGNRiER9vcG9H9stQc
# xWv2XFJRXRLbJbqvUAV6bMURHXLvjflSxIUXk8A8FdsaN8cIFRg/eKtFtvUeh17a
# j54WcmnGrnu3tz5q4i6tAgMBAAGjggHdMIIB2TASBgkrBgEEAYI3FQEEBQIDAQAB
# MCMGCSsGAQQBgjcVAgQWBBQqp1L+ZMSavoKRPEY1Kc8Q/y8E7jAdBgNVHQ4EFgQU
# n6cVXQBeYl2D9OXSZacbUzUZ6XIwXAYDVR0gBFUwUzBRBgwrBgEEAYI3TIN9AQEw
# QTA/BggrBgEFBQcCARYzaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9E
# b2NzL1JlcG9zaXRvcnkuaHRtMBMGA1UdJQQMMAoGCCsGAQUFBwMIMBkGCSsGAQQB
# gjcUAgQMHgoAUwB1AGIAQwBBMAsGA1UdDwQEAwIBhjAPBgNVHRMBAf8EBTADAQH/
# MB8GA1UdIwQYMBaAFNX2VsuP6KJcYmjRPZSQW9fOmhjEMFYGA1UdHwRPME0wS6BJ
# oEeGRWh0dHA6Ly9jcmwubWljcm9zb2Z0LmNvbS9wa2kvY3JsL3Byb2R1Y3RzL01p
# Y1Jvb0NlckF1dF8yMDEwLTA2LTIzLmNybDBaBggrBgEFBQcBAQROMEwwSgYIKwYB
# BQUHMAKGPmh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMvTWljUm9v
# Q2VyQXV0XzIwMTAtMDYtMjMuY3J0MA0GCSqGSIb3DQEBCwUAA4ICAQCdVX38Kq3h
# LB9nATEkW+Geckv8qW/qXBS2Pk5HZHixBpOXPTEztTnXwnE2P9pkbHzQdTltuw8x
# 5MKP+2zRoZQYIu7pZmc6U03dmLq2HnjYNi6cqYJWAAOwBb6J6Gngugnue99qb74p
# y27YP0h1AdkY3m2CDPVtI1TkeFN1JFe53Z/zjj3G82jfZfakVqr3lbYoVSfQJL1A
# oL8ZthISEV09J+BAljis9/kpicO8F7BUhUKz/AyeixmJ5/ALaoHCgRlCGVJ1ijbC
# HcNhcy4sa3tuPywJeBTpkbKpW99Jo3QMvOyRgNI95ko+ZjtPu4b6MhrZlvSP9pEB
# 9s7GdP32THJvEKt1MMU0sHrYUP4KWN1APMdUbZ1jdEgssU5HLcEUBHG/ZPkkvnNt
# yo4JvbMBV0lUZNlz138eW0QBjloZkWsNn6Qo3GcZKCS6OEuabvshVGtqRRFHqfG3
# rsjoiV5PndLQTHa1V1QJsWkBRH58oWFsc/4Ku+xBZj1p/cvBQUl+fpO+y/g75LcV
# v7TOPqUxUYS8vwLBgqJ7Fx0ViY1w/ue10CgaiQuPNtq6TPmb/wrpNPgkNWcr4A24
# 5oyZ1uEi6vAnQj0llOZ0dFtq0Z4+7X6gMTN9vMvpe784cETRkPHIqzqKOghif9lw
# Y1NNje6CbaUFEMFxBmoQtB1VM1izoXBm8qGCAtQwggI9AgEBMIIBAKGB2KSB1TCB
# 0jELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
# ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMk
# TWljcm9zb2Z0IElyZWxhbmQgT3BlcmF0aW9ucyBMaW1pdGVkMSYwJAYDVQQLEx1U
# aGFsZXMgVFNTIEVTTjoyQUQ0LTRCOTItRkEwMTElMCMGA1UEAxMcTWljcm9zb2Z0
# IFRpbWUtU3RhbXAgU2VydmljZaIjCgEBMAcGBSsOAwIaAxUAaKBSisy4y86pl8Xy
# 22CJZExE2vOggYMwgYCkfjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
# Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
# cmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDAN
# BgkqhkiG9w0BAQUFAAIFAOlQQl0wIhgPMjAyNDAxMTYwNzQ2MzdaGA8yMDI0MDEx
# NzA3NDYzN1owdDA6BgorBgEEAYRZCgQBMSwwKjAKAgUA6VBCXQIBADAHAgEAAgIO
# 9TAHAgEAAgIRKDAKAgUA6VGT3QIBADA2BgorBgEEAYRZCgQCMSgwJjAMBgorBgEE
# AYRZCgMCoAowCAIBAAIDB6EgoQowCAIBAAIDAYagMA0GCSqGSIb3DQEBBQUAA4GB
# AA1GBVF0K8qZyqhMgkHmog2t4jJJbu6wHKPF261Yu/XoWdvSYfOlwxN12OkcbwTz
# PU5ZYK2jy+9NCD635yWWsU110r3f432TCckXkKHg0vZYam+v7UofW9dK8Zg+6io1
# 3ShfB1BLY9HpdNKtyYj6lSL426CnlOzL2+hEhpuVli4rMYIEDTCCBAkCAQEwgZMw
# fDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
# ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMd
# TWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTACEzMAAAHenkielp8oRD0AAQAA
# Ad4wDQYJYIZIAWUDBAIBBQCgggFKMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRAB
# BDAvBgkqhkiG9w0BCQQxIgQg5HiC509rK9wv+SKnh7H7etf3OyajOgtkRB320h+g
# HokwgfoGCyqGSIb3DQEJEAIvMYHqMIHnMIHkMIG9BCCOPiOfDcFeEBBJAn/mC3Mg
# rT5w/U2z81LYD44Hc34dezCBmDCBgKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQI
# EwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3Nv
# ZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBD
# QSAyMDEwAhMzAAAB3p5InpafKEQ9AAEAAAHeMCIEIPbaGk4PbuFW9+AtVTtGvA5y
# caNNLFqqLXUDZNElw00gMA0GCSqGSIb3DQEBCwUABIICACQxcaasO1WHGp5obJvd
# IrwvVJLA6I+R92ioiOvaLqjSCxLtNK5xPKNaV5SmJ/xct3dNPhgIIosFwbW+AHhg
# NbX7hX5bXf7z9PrsjeDufnC31wy/LjtjpFotToMDTWG1U8mqvCVreLCXkmg0Ixmy
# s9NePLEc/qPA+vt46l4Bg3Wep7VWGLFtYXEjEUz879lRP9nAqLnwjBkG4iJJAOw6
# iM4SvSoO0qkzn15sBDIC7Nide7CO647Iym9B1oFVTG1eOpJeLUTEwOdeTYUf8bj4
# pPNw+JJbotOqdYk2FW9yNcOcPFUJvCq21lFIDCQ/DIWWvmqcXjaMgKErx9D3OO+i
# JQZoEicsaf8+wEYzCoxcFYM8a0jz+vZ9ailUIXaWlIZ5JGLoH1ykcRLOGboDX6wz
# UlmcqcZBNNdG5AJv8MUoG7JyXLObG4W4FSD+T2SrBkQFsKDZEYF/PwrzzUE+Mi0n
# X/bC/gdPd9wBB4CpSuODN3aTCd6ccmkzARz3bHXGXq3U8nbHTD1g9Ow5BMApsPBg
# Z7RLC/q2yv+v842s9i6fp2NdvLnClUpU454NVZaX8QB6m7Q+gVx6PB+0BUpAa8Id
# CBlpb1eoYkNyIbK+PelPpwwdgVI5dRNBTslPC4VIpDJhtKyfpdXQnhN70sED3LbH
# UcQkvv/RzWy+rAI4MwFZgikY
# SIG # End signature block
