<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(MSBuildThisFileDirectory)..\..\..\Repo.props" />
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <TargetFrameworks>netstandard2.0;net6.0;net472</TargetFrameworks>
    <RootNamespace>Microsoft.Graph.PowerShell.Authentication.Core</RootNamespace>
    <Version>2.40.0</Version>
    <!-- Suppress .NET Target Framework Moniker (TFM) Support Build Warnings -->
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
  </PropertyGroup>
  <PropertyGroup>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>
  <PropertyGroup Condition="'$(SignAssembly)' == 'true'">
    <DefineConstants>$(DefineConstants);SIGNED_BUILD</DefineConstants>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <Reference Include="System.Net.Http" />
  </ItemGroup>
  <Target Name="CopyFiles" AfterTargets="Build">
    <Copy SourceFiles="@(PreLoadAssemblies)" DestinationFolder="$(OutputPath)/publish" />
  </Target>
</Project>