// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Microsoft.Graph.PowerShell.Security.Client.Models.Security
{
    /// <summary>
    /// Represents an individual audit log record.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuditLogRecord : global::Microsoft.Graph.PowerShell.Security.Client.Models.Entity, IParsable
    {
        /// <summary>The collection of administrative units associated with the record.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AdministrativeUnits { get; set; }
#nullable restore
#else
        public List<string> AdministrativeUnits { get; set; }
#endif
        /// <summary>The audit data associated with the record.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Microsoft.Graph.PowerShell.Security.Client.Models.Security.AuditData? AuditData { get; set; }
#nullable restore
#else
        public global::Microsoft.Graph.PowerShell.Security.Client.Models.Security.AuditData AuditData { get; set; }
#endif
        /// <summary>The type of the audit log record.</summary>
        public global::Microsoft.Graph.PowerShell.Security.Client.Models.Security.AuditLogRecordType? AuditLogRecordType { get; set; }
        /// <summary>The IP address of the client that performed the activity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientIp { get; set; }
#nullable restore
#else
        public string ClientIp { get; set; }
#endif
        /// <summary>The date and time when the activity was performed.</summary>
        public DateTimeOffset? CreatedDateTime { get; set; }
        /// <summary>The identifier of the object that was affected by the activity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ObjectId { get; set; }
#nullable restore
#else
        public string ObjectId { get; set; }
#endif
        /// <summary>The name of the activity that was performed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Operation { get; set; }
#nullable restore
#else
        public string Operation { get; set; }
#endif
        /// <summary>The GUID of the organization&apos;s Microsoft 365 tenant.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; set; }
#nullable restore
#else
        public string OrganizationId { get; set; }
#endif
        /// <summary>The Microsoft 365 service where the activity occurred.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Service { get; set; }
#nullable restore
#else
        public string Service { get; set; }
#endif
        /// <summary>The identifier of the user, system account, service, or application that performed the activity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>The user principal name of the user who performed the activity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserPrincipalName { get; set; }
#nullable restore
#else
        public string UserPrincipalName { get; set; }
#endif
        /// <summary>The type of user who performed the activity. Possible values are: regular, reserved, admin, dcAdmin, system, application, servicePrincipal, customPolicy, systemPolicy, partnerTechnician, guest, unknownFutureValue.</summary>
        public global::Microsoft.Graph.PowerShell.Security.Client.Models.Security.AuditLogUserType? UserType { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Microsoft.Graph.PowerShell.Security.Client.Models.Security.AuditLogRecord"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Microsoft.Graph.PowerShell.Security.Client.Models.Security.AuditLogRecord CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Microsoft.Graph.PowerShell.Security.Client.Models.Security.AuditLogRecord();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "administrativeUnits", n => { AdministrativeUnits = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "auditData", n => { AuditData = n.GetObjectValue<global::Microsoft.Graph.PowerShell.Security.Client.Models.Security.AuditData>(global::Microsoft.Graph.PowerShell.Security.Client.Models.Security.AuditData.CreateFromDiscriminatorValue); } },
                { "auditLogRecordType", n => { AuditLogRecordType = n.GetEnumValue<global::Microsoft.Graph.PowerShell.Security.Client.Models.Security.AuditLogRecordType>(); } },
                { "clientIp", n => { ClientIp = n.GetStringValue(); } },
                { "createdDateTime", n => { CreatedDateTime = n.GetDateTimeOffsetValue(); } },
                { "objectId", n => { ObjectId = n.GetStringValue(); } },
                { "operation", n => { Operation = n.GetStringValue(); } },
                { "organizationId", n => { OrganizationId = n.GetStringValue(); } },
                { "service", n => { Service = n.GetStringValue(); } },
                { "userId", n => { UserId = n.GetStringValue(); } },
                { "userPrincipalName", n => { UserPrincipalName = n.GetStringValue(); } },
                { "userType", n => { UserType = n.GetEnumValue<global::Microsoft.Graph.PowerShell.Security.Client.Models.Security.AuditLogUserType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfPrimitiveValues<string>("administrativeUnits", AdministrativeUnits);
            writer.WriteObjectValue<global::Microsoft.Graph.PowerShell.Security.Client.Models.Security.AuditData>("auditData", AuditData);
            writer.WriteEnumValue<global::Microsoft.Graph.PowerShell.Security.Client.Models.Security.AuditLogRecordType>("auditLogRecordType", AuditLogRecordType);
            writer.WriteStringValue("clientIp", ClientIp);
            writer.WriteDateTimeOffsetValue("createdDateTime", CreatedDateTime);
            writer.WriteStringValue("objectId", ObjectId);
            writer.WriteStringValue("operation", Operation);
            writer.WriteStringValue("organizationId", OrganizationId);
            writer.WriteStringValue("service", Service);
            writer.WriteStringValue("userId", UserId);
            writer.WriteStringValue("userPrincipalName", UserPrincipalName);
            writer.WriteEnumValue<global::Microsoft.Graph.PowerShell.Security.Client.Models.Security.AuditLogUserType>("userType", UserType);
        }
    }
}
#pragma warning restore CS0618
