// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Microsoft.Graph.PowerShell.Security.Client.Models.Security
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DataSourceHoldStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "notApplied")]
        #pragma warning disable CS1591
        NotApplied,
        #pragma warning restore CS1591
        [EnumMember(Value = "applied")]
        #pragma warning disable CS1591
        Applied,
        #pragma warning restore CS1591
        [EnumMember(Value = "applying")]
        #pragma warning disable CS1591
        Applying,
        #pragma warning restore CS1591
        [EnumMember(Value = "removing")]
        #pragma warning disable CS1591
        Removing,
        #pragma warning restore CS1591
        [EnumMember(Value = "partial")]
        #pragma warning disable CS1591
        Partial,
        #pragma warning restore CS1591
        [EnumMember(Value = "unknownFutureValue")]
        #pragma warning disable CS1591
        UnknownFutureValue,
        #pragma warning restore CS1591
    }
}
