// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Microsoft.Graph.PowerShell.Security.Client.Models.Security
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    [Flags]
    #pragma warning disable CS1591
    public enum ItemsToInclude
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "searchHits")]
        #pragma warning disable CS1591
        SearchHits = 1,
        #pragma warning restore CS1591
        [EnumMember(Value = "partiallyIndexed")]
        #pragma warning disable CS1591
        PartiallyIndexed = 2,
        #pragma warning restore CS1591
        [EnumMember(Value = "unknownFutureValue")]
        #pragma warning disable CS1591
        UnknownFutureValue = 4,
        #pragma warning restore CS1591
    }
}
