// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Microsoft.Graph.PowerShell.Compliance.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CourseStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "notStarted")]
        #pragma warning disable CS1591
        NotStarted,
        #pragma warning restore CS1591
        [EnumMember(Value = "inProgress")]
        #pragma warning disable CS1591
        InProgress,
        #pragma warning restore CS1591
        [EnumMember(Value = "completed")]
        #pragma warning disable CS1591
        Completed,
        #pragma warning restore CS1591
        [EnumMember(Value = "unknownFutureValue")]
        #pragma warning disable CS1591
        UnknownFutureValue,
        #pragma warning restore CS1591
    }
}
