// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Microsoft.Graph.PowerShell.Identity.DirectoryManagement.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CertificateAuthorityDetail : global::Microsoft.Graph.PowerShell.Identity.DirectoryManagement.Client.Models.DirectoryObject, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The public key of the certificate authority.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public byte[]? Certificate { get; set; }
#nullable restore
#else
        public byte[] Certificate { get; set; }
#endif
        /// <summary>The type of certificate authority. The possible values are: root, intermediate, unknownFutureValue. Supports $filter (eq).</summary>
        public global::Microsoft.Graph.PowerShell.Identity.DirectoryManagement.Client.Models.CertificateAuthorityType? CertificateAuthorityType { get; set; }
        /// <summary>The URL to check if the certificate is revoked.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CertificateRevocationListUrl { get; set; }
#nullable restore
#else
        public string CertificateRevocationListUrl { get; set; }
#endif
        /// <summary>The date and time when the certificate authority was created.</summary>
        public DateTimeOffset? CreatedDateTime { get; set; }
        /// <summary>The deltaCertificateRevocationListUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeltaCertificateRevocationListUrl { get; set; }
#nullable restore
#else
        public string DeltaCertificateRevocationListUrl { get; set; }
#endif
        /// <summary>The display name of the certificate authority.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>The date and time when the certificate authority expires. Supports $filter (eq) and $orderby.</summary>
        public DateTimeOffset? ExpirationDateTime { get; set; }
        /// <summary>Indicates whether the certificate picker presents the certificate authority to the user to use for authentication. Default value is false. Optional.</summary>
        public bool? IsIssuerHintEnabled { get; set; }
        /// <summary>The issuer of the certificate authority.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Issuer { get; set; }
#nullable restore
#else
        public string Issuer { get; set; }
#endif
        /// <summary>The subject key identifier of certificate authority.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IssuerSubjectKeyIdentifier { get; set; }
#nullable restore
#else
        public string IssuerSubjectKeyIdentifier { get; set; }
#endif
        /// <summary>The thumbprint of certificate authority certificate. Supports $filter (eq, startswith).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Thumbprint { get; set; }
#nullable restore
#else
        public string Thumbprint { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Microsoft.Graph.PowerShell.Identity.DirectoryManagement.Client.Models.CertificateAuthorityDetail"/> and sets the default values.
        /// </summary>
        public CertificateAuthorityDetail() : base()
        {
            OdataType = "#microsoft.graph.certificateAuthorityDetail";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Microsoft.Graph.PowerShell.Identity.DirectoryManagement.Client.Models.CertificateAuthorityDetail"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Microsoft.Graph.PowerShell.Identity.DirectoryManagement.Client.Models.CertificateAuthorityDetail CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Microsoft.Graph.PowerShell.Identity.DirectoryManagement.Client.Models.CertificateAuthorityDetail();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "certificate", n => { Certificate = n.GetByteArrayValue(); } },
                { "certificateAuthorityType", n => { CertificateAuthorityType = n.GetEnumValue<global::Microsoft.Graph.PowerShell.Identity.DirectoryManagement.Client.Models.CertificateAuthorityType>(); } },
                { "certificateRevocationListUrl", n => { CertificateRevocationListUrl = n.GetStringValue(); } },
                { "createdDateTime", n => { CreatedDateTime = n.GetDateTimeOffsetValue(); } },
                { "deltaCertificateRevocationListUrl", n => { DeltaCertificateRevocationListUrl = n.GetStringValue(); } },
                { "displayName", n => { DisplayName = n.GetStringValue(); } },
                { "expirationDateTime", n => { ExpirationDateTime = n.GetDateTimeOffsetValue(); } },
                { "isIssuerHintEnabled", n => { IsIssuerHintEnabled = n.GetBoolValue(); } },
                { "issuer", n => { Issuer = n.GetStringValue(); } },
                { "issuerSubjectKeyIdentifier", n => { IssuerSubjectKeyIdentifier = n.GetStringValue(); } },
                { "thumbprint", n => { Thumbprint = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteByteArrayValue("certificate", Certificate);
            writer.WriteEnumValue<global::Microsoft.Graph.PowerShell.Identity.DirectoryManagement.Client.Models.CertificateAuthorityType>("certificateAuthorityType", CertificateAuthorityType);
            writer.WriteStringValue("certificateRevocationListUrl", CertificateRevocationListUrl);
            writer.WriteDateTimeOffsetValue("createdDateTime", CreatedDateTime);
            writer.WriteStringValue("deltaCertificateRevocationListUrl", DeltaCertificateRevocationListUrl);
            writer.WriteStringValue("displayName", DisplayName);
            writer.WriteDateTimeOffsetValue("expirationDateTime", ExpirationDateTime);
            writer.WriteBoolValue("isIssuerHintEnabled", IsIssuerHintEnabled);
            writer.WriteStringValue("issuer", Issuer);
            writer.WriteStringValue("issuerSubjectKeyIdentifier", IssuerSubjectKeyIdentifier);
            writer.WriteStringValue("thumbprint", Thumbprint);
        }
    }
}
#pragma warning restore CS0618
