// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Microsoft.Graph.PowerShell.Applications.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PrinterDocumentConfiguration : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The collate property</summary>
        public bool? Collate { get; set; }
        /// <summary>The colorMode property</summary>
        public global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrintColorMode? ColorMode { get; set; }
        /// <summary>The copies property</summary>
        public int? Copies { get; set; }
        /// <summary>The dpi property</summary>
        public int? Dpi { get; set; }
        /// <summary>The duplexMode property</summary>
        public global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrintDuplexMode? DuplexMode { get; set; }
        /// <summary>The feedDirection property</summary>
        public global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrinterFeedDirection? FeedDirection { get; set; }
        /// <summary>The feedOrientation property</summary>
        public global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrinterFeedOrientation? FeedOrientation { get; set; }
        /// <summary>The finishings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrintFinishing?>? Finishings { get; set; }
#nullable restore
#else
        public List<global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrintFinishing?> Finishings { get; set; }
#endif
        /// <summary>The fitPdfToPage property</summary>
        public bool? FitPdfToPage { get; set; }
        /// <summary>The inputBin property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InputBin { get; set; }
#nullable restore
#else
        public string InputBin { get; set; }
#endif
        /// <summary>The margin property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrintMargin? Margin { get; set; }
#nullable restore
#else
        public global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrintMargin Margin { get; set; }
#endif
        /// <summary>The mediaSize property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MediaSize { get; set; }
#nullable restore
#else
        public string MediaSize { get; set; }
#endif
        /// <summary>The mediaType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MediaType { get; set; }
#nullable restore
#else
        public string MediaType { get; set; }
#endif
        /// <summary>The multipageLayout property</summary>
        public global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrintMultipageLayout? MultipageLayout { get; set; }
        /// <summary>The OdataType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OdataType { get; set; }
#nullable restore
#else
        public string OdataType { get; set; }
#endif
        /// <summary>The orientation property</summary>
        public global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrintOrientation? Orientation { get; set; }
        /// <summary>The outputBin property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OutputBin { get; set; }
#nullable restore
#else
        public string OutputBin { get; set; }
#endif
        /// <summary>The pageRanges property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Microsoft.Graph.PowerShell.Applications.Client.Models.IntegerRange>? PageRanges { get; set; }
#nullable restore
#else
        public List<global::Microsoft.Graph.PowerShell.Applications.Client.Models.IntegerRange> PageRanges { get; set; }
#endif
        /// <summary>The pagesPerSheet property</summary>
        public int? PagesPerSheet { get; set; }
        /// <summary>The quality property</summary>
        public global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrintQuality? Quality { get; set; }
        /// <summary>The scaling property</summary>
        public global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrintScaling? Scaling { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrinterDocumentConfiguration"/> and sets the default values.
        /// </summary>
        public PrinterDocumentConfiguration()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrinterDocumentConfiguration"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrinterDocumentConfiguration CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrinterDocumentConfiguration();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "collate", n => { Collate = n.GetBoolValue(); } },
                { "colorMode", n => { ColorMode = n.GetEnumValue<global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrintColorMode>(); } },
                { "copies", n => { Copies = n.GetIntValue(); } },
                { "dpi", n => { Dpi = n.GetIntValue(); } },
                { "duplexMode", n => { DuplexMode = n.GetEnumValue<global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrintDuplexMode>(); } },
                { "feedDirection", n => { FeedDirection = n.GetEnumValue<global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrinterFeedDirection>(); } },
                { "feedOrientation", n => { FeedOrientation = n.GetEnumValue<global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrinterFeedOrientation>(); } },
                { "finishings", n => { Finishings = n.GetCollectionOfEnumValues<global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrintFinishing>()?.AsList(); } },
                { "fitPdfToPage", n => { FitPdfToPage = n.GetBoolValue(); } },
                { "inputBin", n => { InputBin = n.GetStringValue(); } },
                { "margin", n => { Margin = n.GetObjectValue<global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrintMargin>(global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrintMargin.CreateFromDiscriminatorValue); } },
                { "mediaSize", n => { MediaSize = n.GetStringValue(); } },
                { "mediaType", n => { MediaType = n.GetStringValue(); } },
                { "multipageLayout", n => { MultipageLayout = n.GetEnumValue<global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrintMultipageLayout>(); } },
                { "@odata.type", n => { OdataType = n.GetStringValue(); } },
                { "orientation", n => { Orientation = n.GetEnumValue<global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrintOrientation>(); } },
                { "outputBin", n => { OutputBin = n.GetStringValue(); } },
                { "pageRanges", n => { PageRanges = n.GetCollectionOfObjectValues<global::Microsoft.Graph.PowerShell.Applications.Client.Models.IntegerRange>(global::Microsoft.Graph.PowerShell.Applications.Client.Models.IntegerRange.CreateFromDiscriminatorValue)?.AsList(); } },
                { "pagesPerSheet", n => { PagesPerSheet = n.GetIntValue(); } },
                { "quality", n => { Quality = n.GetEnumValue<global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrintQuality>(); } },
                { "scaling", n => { Scaling = n.GetEnumValue<global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrintScaling>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("collate", Collate);
            writer.WriteEnumValue<global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrintColorMode>("colorMode", ColorMode);
            writer.WriteIntValue("copies", Copies);
            writer.WriteIntValue("dpi", Dpi);
            writer.WriteEnumValue<global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrintDuplexMode>("duplexMode", DuplexMode);
            writer.WriteEnumValue<global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrinterFeedDirection>("feedDirection", FeedDirection);
            writer.WriteEnumValue<global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrinterFeedOrientation>("feedOrientation", FeedOrientation);
            writer.WriteCollectionOfEnumValues<global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrintFinishing>("finishings", Finishings);
            writer.WriteBoolValue("fitPdfToPage", FitPdfToPage);
            writer.WriteStringValue("inputBin", InputBin);
            writer.WriteObjectValue<global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrintMargin>("margin", Margin);
            writer.WriteStringValue("mediaSize", MediaSize);
            writer.WriteStringValue("mediaType", MediaType);
            writer.WriteEnumValue<global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrintMultipageLayout>("multipageLayout", MultipageLayout);
            writer.WriteStringValue("@odata.type", OdataType);
            writer.WriteEnumValue<global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrintOrientation>("orientation", Orientation);
            writer.WriteStringValue("outputBin", OutputBin);
            writer.WriteCollectionOfObjectValues<global::Microsoft.Graph.PowerShell.Applications.Client.Models.IntegerRange>("pageRanges", PageRanges);
            writer.WriteIntValue("pagesPerSheet", PagesPerSheet);
            writer.WriteEnumValue<global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrintQuality>("quality", Quality);
            writer.WriteEnumValue<global::Microsoft.Graph.PowerShell.Applications.Client.Models.PrintScaling>("scaling", Scaling);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
