name: Publish Docker image
on:
  workflow_dispatch:
  push:
    tags: ["*"]
env:
  REGISTRY: msgraphprod.azurecr.io
  IMAGE_NAME: public/microsoftgraph/powershell
jobs:
  push_to_registry:
    environment:
      name: acr
    name: Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Login to GitHub package feed
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          registry: ${{ env.REGISTRY }}

      - name: Get truncated run number
        id: getversion
        run: |
          $version = $Env:GITHUB_REF.replace("refs/tags/", "")
          Write-Output "version=$version" >> $Env:GITHUB_OUTPUT
        shell: pwsh
      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0
      - name: Push to GitHub Packages - Release
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          push: true
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.getversion.outputs.version }}
          build-args: |
            VERSION=${{ steps.getversion.outputs.version }}
